import type { Receita } from './tipos';

export const PRATOS: Receita[] = [
  {
    nome: 'Filé de frango grelhado',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'frango',
    tags: ['grelhado', 'fit', 'classico'],
    ingredientes: [
      { item: 'File de frango sem osso', unid: 'kg', porPessoa: 0.15 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003, opcional: true },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.004, opcional: true },
      { item: 'Sal', unid: 'kg', porPessoa: 0.003, opcional: true },
    ],
    preparo: [
      'Tempere os filés com alho, sal e um fio de óleo e deixe pegar gosto.',
      'Aqueça bem a chapa ou grelha.',
      'Grelhe cada lado até dourar e o centro ficar cozido.',
      'Reserve aquecido para o serviço.',
    ],
    rendimentoPorcaoG: 180,
    tempoMin: 30,
    complexidade: 'baixa',
    obsOperacional: 'Grelhe em levas e mantenha em banho-maria para não ressecar.',
    nutricao: { kcal: 250, prot: 38, carb: 1, gord: 9, fibra: 0, sodio: 360 },
    substituicoes: ['Trocar filé por peito de frango em bifes finos'],
    adequacaoRefeitorio: 94,
  },
  {
    nome: 'Filé de frango ao molho de tomate',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'frango',
    tags: ['ao-molho', 'comfort', 'classico'],
    ingredientes: [
      { item: 'File de frango sem osso', unid: 'kg', porPessoa: 0.15 },
      { item: 'Molho de tomate', unid: 'un', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003, opcional: true },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.004, opcional: true },
    ],
    preparo: [
      'Sele os filés temperados na panela e reserve.',
      'Refogue cebola e alho no mesmo fundo.',
      'Acrescente o molho de tomate e deixe apurar.',
      'Volte os filés ao molho e cozinhe até ficarem macios.',
    ],
    rendimentoPorcaoG: 210,
    tempoMin: 40,
    complexidade: 'baixa',
    obsOperacional: 'O molho rende e mantém o frango úmido na espera.',
    nutricao: { kcal: 280, prot: 36, carb: 9, gord: 10, fibra: 2, sodio: 520 },
    substituicoes: ['Usar sobrecoxa desossada para versão econômica'],
    adequacaoRefeitorio: 93,
  },
  {
    nome: 'Frango assado com batatas',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'frango',
    tags: ['assado', 'comfort', 'classico'],
    ingredientes: [
      { item: 'Frango inteiro', unid: 'kg', porPessoa: 0.18 },
      { item: 'Batata', unid: 'kg', porPessoa: 0.06 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003, opcional: true },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.004, opcional: true },
      { item: 'Sal', unid: 'kg', porPessoa: 0.003, opcional: true },
    ],
    preparo: [
      'Corte o frango em pedaços e tempere bem.',
      'Disponha em assadeira com as batatas em cubos.',
      'Regue com óleo e leve ao forno quente.',
      'Asse virando na metade até dourar por igual.',
    ],
    rendimentoPorcaoG: 240,
    tempoMin: 60,
    complexidade: 'media',
    obsOperacional: 'Asse em assadeiras grandes; batata absorve o sabor do frango.',
    nutricao: { kcal: 360, prot: 30, carb: 18, gord: 18, fibra: 2, sodio: 480 },
    substituicoes: ['Trocar frango inteiro por coxa e sobrecoxa'],
    adequacaoRefeitorio: 90,
  },
  {
    nome: 'Frango à parmegiana',
    categoria: 'principal',
    classe: 'premium',
    proteina: 'frango',
    tags: ['empanado', 'ao-molho', 'comfort'],
    ingredientes: [
      { item: 'File de frango sem osso', unid: 'kg', porPessoa: 0.15 },
      { item: 'Farinha de trigo', unid: 'kg', porPessoa: 0.02 },
      { item: 'Ovos', unid: 'un', porPessoa: 0.5 },
      { item: 'Molho de tomate', unid: 'un', porPessoa: 0.03 },
      { item: 'Mussarela', unid: 'kg', porPessoa: 0.04 },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.006, opcional: true },
    ],
    preparo: [
      'Passe os filés por farinha e ovo e frite até dourar.',
      'Disponha em assadeira e cubra com molho de tomate.',
      'Distribua a mussarela por cima.',
      'Leve ao forno até gratinar o queijo.',
    ],
    rendimentoPorcaoG: 250,
    tempoMin: 55,
    complexidade: 'alta',
    obsOperacional: 'Empane em linha; gratine perto da hora do serviço.',
    nutricao: { kcal: 420, prot: 38, carb: 18, gord: 22, fibra: 2, sodio: 700 },
    substituicoes: ['Assar empanado em vez de fritar para reduzir gordura'],
    adequacaoRefeitorio: 84,
  },
  {
    nome: 'Frango à milanesa',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'frango',
    tags: ['empanado', 'comfort', 'classico'],
    ingredientes: [
      { item: 'File de frango sem osso', unid: 'kg', porPessoa: 0.15 },
      { item: 'Farinha de trigo', unid: 'kg', porPessoa: 0.025 },
      { item: 'Ovos', unid: 'un', porPessoa: 0.5 },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.008, opcional: true },
      { item: 'Sal', unid: 'kg', porPessoa: 0.003, opcional: true },
    ],
    preparo: [
      'Tempere os filés e passe por farinha, ovo e farinha de rosca.',
      'Aqueça o óleo para fritura.',
      'Frite os filés até ficarem dourados e crocantes.',
      'Escorra sobre papel antes de servir.',
    ],
    rendimentoPorcaoG: 200,
    tempoMin: 45,
    complexidade: 'media',
    obsOperacional: 'Sirva o quanto antes para manter a crocância.',
    nutricao: { kcal: 380, prot: 35, carb: 16, gord: 19, fibra: 1, sodio: 460 },
    substituicoes: ['Empanar no forno com fio de óleo para versão mais leve'],
    adequacaoRefeitorio: 86,
  },
  {
    nome: 'Frango xadrez',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'frango',
    tags: ['refogado', 'oriental', 'com-legumes'],
    ingredientes: [
      { item: 'Peito de Frango', unid: 'kg', porPessoa: 0.14 },
      { item: 'Pimentão', unid: 'kg', porPessoa: 0.04 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003, opcional: true },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.004, opcional: true },
    ],
    preparo: [
      'Corte o frango em cubos e tempere.',
      'Salteie os cubos em fogo alto até dourar.',
      'Acrescente cebola e pimentão em pedaços e refogue rápido.',
      'Finalize com molho shoyu e ajuste o ponto.',
    ],
    rendimentoPorcaoG: 200,
    tempoMin: 35,
    complexidade: 'media',
    obsOperacional: 'Refogue em fogo alto e por levas para os legumes ficarem firmes.',
    nutricao: { kcal: 290, prot: 33, carb: 10, gord: 12, fibra: 3, sodio: 620 },
    substituicoes: ['Acrescentar castanha de caju para versão tradicional'],
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Frango ao curry',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'frango',
    tags: ['ao-molho', 'cremoso', 'temperado'],
    ingredientes: [
      { item: 'Peito de Frango', unid: 'kg', porPessoa: 0.15 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Creme de Leite', unid: 'un', porPessoa: 0.03 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003, opcional: true },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.004, opcional: true },
    ],
    preparo: [
      'Sele os cubos de frango temperados e reserve.',
      'Refogue cebola e alho com curry em pó.',
      'Adicione um pouco de água e deixe formar molho.',
      'Volte o frango, incorpore o creme de leite e aqueça sem ferver.',
    ],
    rendimentoPorcaoG: 210,
    tempoMin: 40,
    complexidade: 'media',
    obsOperacional: 'Adicione o creme por último para o molho não talhar.',
    nutricao: { kcal: 320, prot: 34, carb: 8, gord: 16, fibra: 1, sodio: 500 },
    substituicoes: ['Usar leite de coco no lugar do creme de leite'],
    adequacaoRefeitorio: 85,
  },
  {
    nome: 'Fricassê de frango',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'frango',
    tags: ['ao-molho', 'cremoso', 'comfort'],
    ingredientes: [
      { item: 'Peito de Frango', unid: 'kg', porPessoa: 0.15 },
      { item: 'Creme de Leite', unid: 'un', porPessoa: 0.03 },
      { item: 'Milho (lata)', unid: 'lata', porPessoa: 0.04 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Mussarela', unid: 'kg', porPessoa: 0.03 },
    ],
    preparo: [
      'Cozinhe e desfie o peito de frango.',
      'Refogue cebola e misture com o frango.',
      'Acrescente milho e creme de leite formando creme.',
      'Cubra com mussarela e gratine no forno.',
    ],
    rendimentoPorcaoG: 230,
    tempoMin: 50,
    complexidade: 'media',
    obsOperacional: 'Monte em assadeiras e gratine próximo ao serviço.',
    nutricao: { kcal: 360, prot: 30, carb: 16, gord: 18, fibra: 2, sodio: 560 },
    substituicoes: ['Cobrir com batata palha em vez de queijo'],
    adequacaoRefeitorio: 87,
  },
  {
    nome: 'Frango ensopado com legumes',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'frango',
    tags: ['ensopado', 'com-legumes', 'comfort'],
    ingredientes: [
      { item: 'Sobre coxa', unid: 'kg', porPessoa: 0.16 },
      { item: 'Batata', unid: 'kg', porPessoa: 0.05 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.04 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
    ],
    preparo: [
      'Refogue a sobrecoxa temperada com cebola e tomate.',
      'Cubra com água e deixe cozinhar parcialmente.',
      'Acrescente batata e cenoura em pedaços.',
      'Cozinhe até os legumes ficarem macios e o caldo encorpar.',
    ],
    rendimentoPorcaoG: 250,
    tempoMin: 55,
    complexidade: 'baixa',
    obsOperacional: 'Caldo encorpado rende bem em panelão.',
    nutricao: { kcal: 330, prot: 28, carb: 16, gord: 16, fibra: 3, sodio: 470 },
    substituicoes: ['Trocar sobrecoxa por coxa de frango'],
    adequacaoRefeitorio: 92,
  },
  {
    nome: 'Sobrecoxa assada com ervas',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'frango',
    tags: ['assado', 'classico', 'comfort'],
    ingredientes: [
      { item: 'Sobre coxa', unid: 'kg', porPessoa: 0.17 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003, opcional: true },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.004, opcional: true },
      { item: 'Sal', unid: 'kg', porPessoa: 0.003, opcional: true },
    ],
    preparo: [
      'Tempere as sobrecoxas com alho, sal e ervas.',
      'Disponha em assadeira com a pele para cima.',
      'Asse em forno quente regando com o próprio caldo.',
      'Doure bem antes de servir.',
    ],
    rendimentoPorcaoG: 200,
    tempoMin: 55,
    complexidade: 'baixa',
    obsOperacional: 'Peça econômica e suculenta; ótimo rendimento no forno.',
    nutricao: { kcal: 340, prot: 29, carb: 1, gord: 24, fibra: 0, sodio: 420 },
    substituicoes: ['Usar coxa de frango com ajuste no tempo'],
    adequacaoRefeitorio: 91,
  },
  {
    nome: 'Frango ao molho pardo',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'frango',
    tags: ['ao-molho', 'regional', 'comfort'],
    ingredientes: [
      { item: 'Frango inteiro', unid: 'kg', porPessoa: 0.18 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.03 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003, opcional: true },
      { item: 'Cheiro-verde', unid: 'mç', porPessoa: 0.01, opcional: true },
    ],
    preparo: [
      'Refogue os pedaços de frango com cebola, alho e tomate.',
      'Cubra com água e cozinhe até ficar macio.',
      'Apure o molho escuro até encorpar.',
      'Finalize com cheiro-verde.',
    ],
    rendimentoPorcaoG: 240,
    tempoMin: 60,
    complexidade: 'media',
    obsOperacional: 'Prato regional rústico; bom para servir com arroz branco.',
    nutricao: { kcal: 320, prot: 30, carb: 6, gord: 18, fibra: 2, sodio: 450 },
    substituicoes: ['Usar somente coxa e sobrecoxa para mais sabor'],
    adequacaoRefeitorio: 86,
  },
  {
    nome: 'Frango com quiabo',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'frango',
    tags: ['refogado', 'mineira', 'regional'],
    ingredientes: [
      { item: 'Sobre coxa', unid: 'kg', porPessoa: 0.16 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.03 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003, opcional: true },
      { item: 'Cheiro-verde', unid: 'mç', porPessoa: 0.01, opcional: true },
    ],
    preparo: [
      'Refogue a sobrecoxa temperada com cebola, alho e tomate.',
      'Cubra com água e cozinhe até quase macio.',
      'Acrescente o quiabo selado à parte.',
      'Cozinhe rapidamente e finalize com cheiro-verde.',
    ],
    rendimentoPorcaoG: 230,
    tempoMin: 55,
    complexidade: 'media',
    obsOperacional: 'Sele o quiabo antes para reduzir a baba.',
    nutricao: { kcal: 310, prot: 28, carb: 8, gord: 17, fibra: 4, sodio: 440 },
    substituicoes: ['Trocar sobrecoxa por frango caipira em pedaços'],
    adequacaoRefeitorio: 84,
  },
  {
    nome: 'Frango com creme de milho',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'frango',
    tags: ['ao-molho', 'cremoso', 'comfort'],
    ingredientes: [
      { item: 'Peito de Frango', unid: 'kg', porPessoa: 0.15 },
      { item: 'Milho (lata)', unid: 'lata', porPessoa: 0.05 },
      { item: 'Creme de Leite', unid: 'un', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Leite', unid: 'lt', porPessoa: 0.02, opcional: true },
    ],
    preparo: [
      'Sele os cubos de frango e refogue com cebola.',
      'Bata parte do milho com leite formando creme.',
      'Junte ao frango com o restante do milho.',
      'Finalize com creme de leite e aqueça bem.',
    ],
    rendimentoPorcaoG: 220,
    tempoMin: 40,
    complexidade: 'media',
    obsOperacional: 'O creme de milho dá rendimento e maciez ao prato.',
    nutricao: { kcal: 330, prot: 32, carb: 16, gord: 14, fibra: 2, sodio: 480 },
    substituicoes: ['Gratinar com mussarela por cima'],
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Strogonoff de frango',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'frango',
    tags: ['ao-molho', 'cremoso', 'classico'],
    ingredientes: [
      { item: 'Peito de Frango', unid: 'kg', porPessoa: 0.15 },
      { item: 'Creme de Leite', unid: 'un', porPessoa: 0.04 },
      { item: 'Molho de tomate', unid: 'un', porPessoa: 0.02 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003, opcional: true },
    ],
    preparo: [
      'Salteie os cubos de frango temperados.',
      'Refogue cebola e acrescente molho de tomate e mostarda.',
      'Deixe apurar e volte o frango.',
      'Finalize com o creme de leite sem deixar ferver.',
    ],
    rendimentoPorcaoG: 220,
    tempoMin: 40,
    complexidade: 'baixa',
    obsOperacional: 'Clássico de alta aceitação; serve com arroz e batata palha.',
    nutricao: { kcal: 350, prot: 34, carb: 9, gord: 18, fibra: 1, sodio: 540 },
    substituicoes: ['Adicionar champignon fatiado'],
    adequacaoRefeitorio: 93,
  },
  {
    nome: 'Frango agridoce',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'frango',
    tags: ['oriental', 'ao-molho', 'com-legumes'],
    ingredientes: [
      { item: 'Peito de Frango', unid: 'kg', porPessoa: 0.14 },
      { item: 'Pimentão', unid: 'kg', porPessoa: 0.04 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Farinha de trigo', unid: 'kg', porPessoa: 0.015 },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.006, opcional: true },
    ],
    preparo: [
      'Empane levemente os cubos de frango e frite.',
      'Refogue pimentão e cebola em pedaços.',
      'Prepare o molho agridoce com vinagre e açúcar.',
      'Misture tudo e deixe envolver o frango.',
    ],
    rendimentoPorcaoG: 210,
    tempoMin: 45,
    complexidade: 'media',
    obsOperacional: 'Adicione abacaxi em cubos para a versão tradicional.',
    nutricao: { kcal: 360, prot: 30, carb: 22, gord: 16, fibra: 2, sodio: 580 },
    substituicoes: ['Servir sem empanar para versão mais leve'],
    adequacaoRefeitorio: 83,
  },
  {
    nome: 'Cubos de frango ao alho e óleo',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'frango',
    tags: ['refogado', 'fit', 'classico'],
    ingredientes: [
      { item: 'Peito de Frango', unid: 'kg', porPessoa: 0.16 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.005 },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.006, opcional: true },
      { item: 'Cheiro-verde', unid: 'mç', porPessoa: 0.01, opcional: true },
      { item: 'Sal', unid: 'kg', porPessoa: 0.003, opcional: true },
    ],
    preparo: [
      'Corte o peito em cubos e tempere.',
      'Doure o alho no óleo sem queimar.',
      'Salteie os cubos de frango em fogo alto até dourar.',
      'Finalize com cheiro-verde.',
    ],
    rendimentoPorcaoG: 190,
    tempoMin: 30,
    complexidade: 'baixa',
    obsOperacional: 'Refogue por levas para dourar bem sem cozinhar na água.',
    nutricao: { kcal: 270, prot: 37, carb: 2, gord: 12, fibra: 0, sodio: 380 },
    substituicoes: ['Acrescentar brócolis salteado'],
    adequacaoRefeitorio: 92,
  },
  {
    nome: 'Coxa de frango assada na laranja',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'frango',
    tags: ['assado', 'comfort', 'classico'],
    ingredientes: [
      { item: 'Sobre coxa', unid: 'kg', porPessoa: 0.17 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003, opcional: true },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.004, opcional: true },
      { item: 'Sal', unid: 'kg', porPessoa: 0.003, opcional: true },
    ],
    preparo: [
      'Tempere as coxas com alho, sal e suco de laranja.',
      'Deixe marinar e disponha em assadeira.',
      'Asse em forno quente regando com a marinada.',
      'Doure até a pele ficar caramelizada.',
    ],
    rendimentoPorcaoG: 200,
    tempoMin: 60,
    complexidade: 'baixa',
    obsOperacional: 'A laranja caramela bem no forno e dá brilho à pele.',
    nutricao: { kcal: 330, prot: 28, carb: 6, gord: 21, fibra: 0, sodio: 420 },
    substituicoes: ['Substituir laranja por limão para versão cítrica'],
    adequacaoRefeitorio: 89,
  },
  {
    nome: 'Frango desfiado refogado',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'frango',
    tags: ['refogado', 'comfort', 'classico'],
    ingredientes: [
      { item: 'Peito de Frango', unid: 'kg', porPessoa: 0.15 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.03 },
      { item: 'Pimentão', unid: 'kg', porPessoa: 0.02 },
      { item: 'Cheiro-verde', unid: 'mç', porPessoa: 0.01, opcional: true },
    ],
    preparo: [
      'Cozinhe o peito e desfie.',
      'Refogue cebola, tomate e pimentão.',
      'Acrescente o frango desfiado e ajuste o tempero.',
      'Apure e finalize com cheiro-verde.',
    ],
    rendimentoPorcaoG: 200,
    tempoMin: 40,
    complexidade: 'baixa',
    obsOperacional: 'Versátil para recheios e acompanhamentos; ótimo rendimento.',
    nutricao: { kcal: 250, prot: 34, carb: 7, gord: 9, fibra: 2, sodio: 420 },
    substituicoes: ['Aproveitar sobras de frango assado'],
    adequacaoRefeitorio: 91,
  },
  {
    nome: 'Peito de frango recheado com queijo',
    categoria: 'principal',
    classe: 'premium',
    proteina: 'frango',
    tags: ['assado', 'recheado', 'comfort'],
    ingredientes: [
      { item: 'Peito de Frango', unid: 'kg', porPessoa: 0.16 },
      { item: 'Mussarela', unid: 'kg', porPessoa: 0.03 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.02 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003, opcional: true },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.004, opcional: true },
    ],
    preparo: [
      'Abra o peito em bolso e tempere.',
      'Recheie com mussarela e tomate.',
      'Feche, sele na frigideira e disponha em assadeira.',
      'Finalize no forno até o frango cozinhar por completo.',
    ],
    rendimentoPorcaoG: 210,
    tempoMin: 50,
    complexidade: 'alta',
    obsOperacional: 'Prenda com palito; recheie em linha de produção.',
    nutricao: { kcal: 330, prot: 40, carb: 3, gord: 17, fibra: 1, sodio: 520 },
    substituicoes: ['Rechear com presunto e queijo'],
    adequacaoRefeitorio: 82,
  },
  {
    nome: 'Frango à cubana',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'frango',
    tags: ['ao-molho', 'tropical', 'comfort'],
    ingredientes: [
      { item: 'Peito de Frango', unid: 'kg', porPessoa: 0.15 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Pimentão', unid: 'kg', porPessoa: 0.02 },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.004, opcional: true },
    ],
    preparo: [
      'Sele os cubos de frango temperados.',
      'Refogue cebola, pimentão e tomate.',
      'Acrescente o frango e cozinhe no molho.',
      'Adicione frutas como banana e passas e aqueça.',
    ],
    rendimentoPorcaoG: 220,
    tempoMin: 45,
    complexidade: 'media',
    obsOperacional: 'Equilibre o doce das frutas com o tempero salgado.',
    nutricao: { kcal: 320, prot: 32, carb: 18, gord: 12, fibra: 3, sodio: 460 },
    substituicoes: ['Usar abacaxi no lugar da banana'],
    adequacaoRefeitorio: 80,
  },
  {
    nome: 'Frango ao molho mostarda',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'frango',
    tags: ['ao-molho', 'cremoso', 'classico'],
    ingredientes: [
      { item: 'File de frango sem osso', unid: 'kg', porPessoa: 0.15 },
      { item: 'Creme de Leite', unid: 'un', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003, opcional: true },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.004, opcional: true },
    ],
    preparo: [
      'Sele os filés temperados e reserve.',
      'Refogue cebola e alho na mesma panela.',
      'Acrescente mostarda e um pouco de água.',
      'Volte o frango, junte o creme de leite e aqueça sem ferver.',
    ],
    rendimentoPorcaoG: 210,
    tempoMin: 40,
    complexidade: 'media',
    obsOperacional: 'A mostarda dá sabor marcante e molho sedoso.',
    nutricao: { kcal: 320, prot: 36, carb: 5, gord: 16, fibra: 0, sodio: 540 },
    substituicoes: ['Acrescentar mel para versão mostarda e mel'],
    adequacaoRefeitorio: 86,
  },
  {
    nome: 'Frango à passarinho',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'frango',
    tags: ['frito', 'classico', 'comfort'],
    ingredientes: [
      { item: 'Frango inteiro', unid: 'kg', porPessoa: 0.18 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.005 },
      { item: 'Farinha de trigo', unid: 'kg', porPessoa: 0.02 },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.01, opcional: true },
      { item: 'Cheiro-verde', unid: 'mç', porPessoa: 0.01, opcional: true },
    ],
    preparo: [
      'Corte o frango em pedaços pequenos e tempere com alho.',
      'Passe levemente na farinha de trigo.',
      'Frite em óleo quente até dourar.',
      'Finalize com alho frito e cheiro-verde.',
    ],
    rendimentoPorcaoG: 200,
    tempoMin: 45,
    complexidade: 'media',
    obsOperacional: 'Frite por levas; mantenha aquecido em estufa.',
    nutricao: { kcal: 380, prot: 30, carb: 10, gord: 24, fibra: 0, sodio: 440 },
    substituicoes: ['Usar coxinha da asa para porções menores'],
    adequacaoRefeitorio: 85,
  },
  {
    nome: 'Frango ao molho de ervas finas',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'frango',
    tags: ['ao-molho', 'cremoso', 'fit'],
    ingredientes: [
      { item: 'File de frango sem osso', unid: 'kg', porPessoa: 0.15 },
      { item: 'Creme de Leite', unid: 'un', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003, opcional: true },
      { item: 'Cheiro-verde', unid: 'mç', porPessoa: 0.01, opcional: true },
    ],
    preparo: [
      'Sele os filés temperados com ervas.',
      'Refogue cebola e alho na panela.',
      'Adicione ervas frescas e um pouco de caldo.',
      'Incorpore o creme de leite e volte o frango.',
    ],
    rendimentoPorcaoG: 205,
    tempoMin: 38,
    complexidade: 'media',
    obsOperacional: 'Use ervas frescas no fim para preservar o aroma.',
    nutricao: { kcal: 300, prot: 36, carb: 4, gord: 14, fibra: 0, sodio: 420 },
    substituicoes: ['Reduzir o creme e usar caldo para versão mais leve'],
    adequacaoRefeitorio: 87,
  },
  {
    nome: 'Frango cremoso com cenoura',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'frango',
    tags: ['ao-molho', 'com-legumes', 'cremoso'],
    ingredientes: [
      { item: 'Peito de Frango', unid: 'kg', porPessoa: 0.15 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.05 },
      { item: 'Creme de Leite', unid: 'un', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Cheiro-verde', unid: 'mç', porPessoa: 0.01, opcional: true },
    ],
    preparo: [
      'Sele os cubos de frango e reserve.',
      'Refogue cebola e a cenoura em rodelas.',
      'Acrescente água e cozinhe a cenoura até amaciar.',
      'Volte o frango, junte o creme e finalize com cheiro-verde.',
    ],
    rendimentoPorcaoG: 220,
    tempoMin: 42,
    complexidade: 'baixa',
    obsOperacional: 'A cenoura dá cor e adoça naturalmente o molho.',
    nutricao: { kcal: 310, prot: 33, carb: 12, gord: 14, fibra: 2, sodio: 440 },
    substituicoes: ['Adicionar ervilha para mais cor'],
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Frango à mineira',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'frango',
    tags: ['refogado', 'mineira', 'regional'],
    ingredientes: [
      { item: 'Sobre coxa', unid: 'kg', porPessoa: 0.16 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.02 },
      { item: 'Cheiro-verde', unid: 'mç', porPessoa: 0.01, opcional: true },
    ],
    preparo: [
      'Tempere a sobrecoxa em pedaços com alho e sal.',
      'Refogue bem com cebola e tomate.',
      'Cubra com água e cozinhe até soltar do osso.',
      'Apure o caldo e finalize com cheiro-verde.',
    ],
    rendimentoPorcaoG: 230,
    tempoMin: 55,
    complexidade: 'baixa',
    obsOperacional: 'Sabor caseiro rústico; bom com angu ou arroz.',
    nutricao: { kcal: 330, prot: 29, carb: 5, gord: 20, fibra: 1, sodio: 460 },
    substituicoes: ['Usar frango caipira para sabor mais intenso'],
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Frango teriyaki',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'frango',
    tags: ['oriental', 'grelhado', 'ao-molho'],
    ingredientes: [
      { item: 'Peito de Frango', unid: 'kg', porPessoa: 0.15 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003, opcional: true },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.004, opcional: true },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
    ],
    preparo: [
      'Grelhe os filés de frango temperados.',
      'Prepare o molho com shoyu, açúcar e gengibre.',
      'Reduza o molho até ficar brilhante.',
      'Envolva o frango no molho até glacear.',
    ],
    rendimentoPorcaoG: 200,
    tempoMin: 38,
    complexidade: 'media',
    obsOperacional: 'Reduza o molho separadamente e glaceie perto do serviço.',
    nutricao: { kcal: 290, prot: 35, carb: 14, gord: 9, fibra: 0, sodio: 720 },
    substituicoes: ['Usar sobrecoxa desossada para mais suculência'],
    adequacaoRefeitorio: 84,
  },
  {
    nome: 'Frango ao molho de cebola caramelizada',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'frango',
    tags: ['ao-molho', 'comfort', 'classico'],
    ingredientes: [
      { item: 'Sobre coxa', unid: 'kg', porPessoa: 0.16 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.05 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003, opcional: true },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.004, opcional: true },
    ],
    preparo: [
      'Sele a sobrecoxa temperada e reserve.',
      'Caramelize bastante cebola em fogo baixo.',
      'Acrescente caldo e deixe formar molho.',
      'Volte o frango e cozinhe até ficar macio.',
    ],
    rendimentoPorcaoG: 225,
    tempoMin: 50,
    complexidade: 'media',
    obsOperacional: 'A cebola caramelizada adoça o molho naturalmente.',
    nutricao: { kcal: 330, prot: 28, carb: 9, gord: 20, fibra: 2, sodio: 440 },
    substituicoes: ['Usar coxa de frango no lugar da sobrecoxa'],
    adequacaoRefeitorio: 87,
  },
  {
    nome: 'Peru assado temperado',
    categoria: 'principal',
    classe: 'premium',
    proteina: 'frango',
    tags: ['assado', 'festivo', 'classico'],
    ingredientes: [
      { item: 'Peito de Frango', unid: 'kg', porPessoa: 0.16 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.004, opcional: true },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Sal', unid: 'kg', porPessoa: 0.003, opcional: true },
    ],
    preparo: [
      'Tempere o peito de peru com alho, ervas e sal.',
      'Deixe marinar e disponha em assadeira.',
      'Asse coberto para manter a umidade.',
      'Finalize sem cobertura para dourar.',
    ],
    rendimentoPorcaoG: 200,
    tempoMin: 70,
    complexidade: 'media',
    obsOperacional: 'Fatie fino após descansar; ótimo em datas comemorativas.',
    nutricao: { kcal: 260, prot: 39, carb: 2, gord: 10, fibra: 0, sodio: 480 },
    substituicoes: ['Substituir peru por peito de chester'],
    adequacaoRefeitorio: 81,
  },
  {
    nome: 'Frango aos quatro queijos',
    categoria: 'principal',
    classe: 'premium',
    proteina: 'frango',
    tags: ['ao-molho', 'cremoso', 'comfort'],
    ingredientes: [
      { item: 'File de frango sem osso', unid: 'kg', porPessoa: 0.15 },
      { item: 'Creme de Leite', unid: 'un', porPessoa: 0.03 },
      { item: 'Mussarela', unid: 'kg', porPessoa: 0.03 },
      { item: 'Leite', unid: 'lt', porPessoa: 0.02 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
    ],
    preparo: [
      'Sele os filés temperados e disponha em assadeira.',
      'Prepare o molho branco com leite e creme.',
      'Acrescente os queijos até derreter.',
      'Cubra o frango com o molho e gratine.',
    ],
    rendimentoPorcaoG: 230,
    tempoMin: 50,
    complexidade: 'alta',
    obsOperacional: 'Monte e gratine perto da hora do serviço.',
    nutricao: { kcal: 410, prot: 37, carb: 8, gord: 25, fibra: 0, sodio: 640 },
    substituicoes: ['Reduzir queijos e usar requeijão para versão mais simples'],
    adequacaoRefeitorio: 80,
  },
  {
    nome: 'Frango grelhado com legumes salteados',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'frango',
    tags: ['grelhado', 'com-legumes', 'fit'],
    ingredientes: [
      { item: 'Peito de Frango', unid: 'kg', porPessoa: 0.15 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.04 },
      { item: 'Pimentão', unid: 'kg', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.004, opcional: true },
    ],
    preparo: [
      'Grelhe os filés de frango temperados.',
      'Corte os legumes em tiras.',
      'Salteie os legumes em fogo alto mantendo firmes.',
      'Sirva o frango sobre os legumes salteados.',
    ],
    rendimentoPorcaoG: 220,
    tempoMin: 35,
    complexidade: 'baixa',
    obsOperacional: 'Opção leve e colorida; salteie os legumes por levas.',
    nutricao: { kcal: 280, prot: 35, carb: 10, gord: 10, fibra: 3, sodio: 380 },
    substituicoes: ['Variar os legumes conforme disponibilidade'],
    adequacaoRefeitorio: 90,
  },
];
