import type { Receita } from './tipos';

export const PRATOS: Receita[] = [
  {
    nome: 'Bife acebolado',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'bovina',
    tags: ['comfort', 'classico'],
    ingredientes: [
      { item: 'Patinho', unid: 'kg', porPessoa: 0.15 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.05 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004, opcional: true },
      { item: 'Óleo', unid: 'ml', porPessoa: 8 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Tempere os bifes com sal e alho e deixe pegar gosto.',
      'Aqueça a chapa com um fio de óleo e sele os bifes dos dois lados.',
      'Corte a cebola em rodelas e refogue à parte até ficar macia e dourada.',
      'Cubra os bifes com a cebola e mantenha aquecido até servir.',
    ],
    rendimentoPorcaoG: 200,
    tempoMin: 40,
    complexidade: 'media',
    obsOperacional: 'Sele em lotes na chapa para não soltar água; finalize a cebola separada.',
    nutricao: { kcal: 330, prot: 30, carb: 6, gord: 20, fibra: 1, sodio: 480 },
    substituicoes: ['Trocar patinho por coxão mole', 'Cebola roxa no lugar da branca'],
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Bife à role',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'bovina',
    tags: ['recheado', 'classico'],
    ingredientes: [
      { item: 'Patinho', unid: 'kg', porPessoa: 0.14 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.04 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Molho de tomate', unid: 'un', porPessoa: 0.03 },
      { item: 'Óleo', unid: 'ml', porPessoa: 8 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Abra os bifes finos, tempere e recheie com tiras de cenoura e cebola.',
      'Enrole cada bife e prenda com palito ou barbante culinário.',
      'Doure os rolinhos no óleo até selar por igual.',
      'Adicione o molho de tomate, tampe e cozinhe em fogo baixo até a carne amaciar.',
    ],
    rendimentoPorcaoG: 210,
    tempoMin: 60,
    complexidade: 'alta',
    obsOperacional: 'Montagem é o gargalo; pré-prepare os rolinhos na véspera refrigerados.',
    nutricao: { kcal: 340, prot: 29, carb: 9, gord: 19, fibra: 2, sodio: 540 },
    substituicoes: ['Recheio com bacon', 'Coxão mole no lugar do patinho'],
    adequacaoRefeitorio: 76,
  },
  {
    nome: 'Carne de panela',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'bovina',
    tags: ['comfort', 'ensopado'],
    ingredientes: [
      { item: 'Acém', unid: 'kg', porPessoa: 0.15 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.03 },
      { item: 'Óleo', unid: 'ml', porPessoa: 8 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Corte o acém em pedaços médios e tempere com alho e sal.',
      'Doure bem a carne no óleo dentro da panela de pressão.',
      'Acrescente cebola e tomate picados e refogue até murchar.',
      'Cubra com água quente e cozinhe na pressão até a carne ficar macia.',
    ],
    rendimentoPorcaoG: 220,
    tempoMin: 70,
    complexidade: 'media',
    obsOperacional: 'Use pressão para o acém; reaproveite o caldo como molho na hora de servir.',
    nutricao: { kcal: 310, prot: 28, carb: 5, gord: 18, fibra: 1, sodio: 460 },
    substituicoes: ['Músculo no lugar do acém', 'Adicionar batata para render mais'],
    adequacaoRefeitorio: 90,
  },
  {
    nome: 'Picadinho de carne',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'bovina',
    tags: ['comfort', 'ensopado'],
    ingredientes: [
      { item: 'Patinho', unid: 'kg', porPessoa: 0.14 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.03 },
      { item: 'Óleo', unid: 'ml', porPessoa: 8 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Corte a carne em cubos pequenos e tempere com alho e sal.',
      'Refogue a cebola e o tomate no óleo até formar base.',
      'Junte a carne e mexa até selar e soltar o próprio caldo.',
      'Cozinhe em fogo médio até reduzir e formar um molho encorpado.',
    ],
    rendimentoPorcaoG: 200,
    tempoMin: 55,
    complexidade: 'baixa',
    obsOperacional: 'Cubos pequenos cozinham rápido; bom para reaproveitar aparas de corte.',
    nutricao: { kcal: 300, prot: 28, carb: 5, gord: 17, fibra: 1, sodio: 450 },
    substituicoes: ['Acém em cubos', 'Acrescentar ervilha para cor'],
    adequacaoRefeitorio: 89,
  },
  {
    nome: 'Carne moída refogada',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'bovina',
    tags: ['moida', 'comfort'],
    ingredientes: [
      { item: 'Carne Moída', unid: 'kg', porPessoa: 0.12 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.03 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Refogue alho e cebola no óleo até dourar.',
      'Adicione a carne moída e mexa para soltar os grumos.',
      'Junte o tomate picado e tempere com sal.',
      'Cozinhe até secar o líquido e a carne ficar soltinha.',
    ],
    rendimentoPorcaoG: 180,
    tempoMin: 35,
    complexidade: 'baixa',
    obsOperacional: 'Drene a gordura liberada antes de servir para não encharcar.',
    nutricao: { kcal: 290, prot: 25, carb: 5, gord: 18, fibra: 1, sodio: 440 },
    substituicoes: ['Acém moído', 'Adicionar cenoura ralada'],
    adequacaoRefeitorio: 90,
  },
  {
    nome: 'Cubos de acém ao molho',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'bovina',
    tags: ['molho', 'ensopado'],
    ingredientes: [
      { item: 'Acém', unid: 'kg', porPessoa: 0.15 },
      { item: 'Molho de tomate', unid: 'un', porPessoa: 0.04 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Óleo', unid: 'ml', porPessoa: 8 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Corte o acém em cubos e doure na panela de pressão.',
      'Refogue cebola e alho junto com a carne.',
      'Adicione o molho de tomate e água e cozinhe na pressão até amaciar.',
      'Abra a panela e reduza o molho em fogo aberto até encorpar.',
    ],
    rendimentoPorcaoG: 220,
    tempoMin: 65,
    complexidade: 'media',
    obsOperacional: 'Molho de tomate pronto agiliza o serviço em alto volume.',
    nutricao: { kcal: 320, prot: 27, carb: 8, gord: 18, fibra: 1, sodio: 560 },
    substituicoes: ['Músculo em cubos', 'Patinho para textura mais firme'],
    adequacaoRefeitorio: 89,
  },
  {
    nome: 'Estrogonofe de carne',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'bovina',
    tags: ['molho', 'comfort'],
    ingredientes: [
      { item: 'Tiras de Carne', unid: 'kg', porPessoa: 0.14 },
      { item: 'Creme de Leite', unid: 'un', porPessoa: 0.03 },
      { item: 'Molho de tomate', unid: 'un', porPessoa: 0.02 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Óleo', unid: 'ml', porPessoa: 8 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Sele as tiras de carne em fogo alto e reserve.',
      'Refogue a cebola e devolva a carne à panela.',
      'Acrescente o molho de tomate e deixe apurar.',
      'Desligue o fogo, incorpore o creme de leite e aqueça sem ferver.',
    ],
    rendimentoPorcaoG: 200,
    tempoMin: 45,
    complexidade: 'media',
    obsOperacional: 'Adicione o creme de leite no fim para não talhar no banho-maria.',
    nutricao: { kcal: 360, prot: 27, carb: 7, gord: 24, fibra: 1, sodio: 560 },
    substituicoes: ['Patinho em tiras', 'Champignon a gosto'],
    adequacaoRefeitorio: 86,
  },
  {
    nome: 'Carne com batata',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'bovina',
    tags: ['ensopado', 'comfort'],
    ingredientes: [
      { item: 'Acém', unid: 'kg', porPessoa: 0.14 },
      { item: 'Batata', unid: 'kg', porPessoa: 0.06 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Óleo', unid: 'ml', porPessoa: 8 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Doure a carne em cubos na pressão e refogue com cebola e alho.',
      'Cubra com água quente e cozinhe na pressão até amaciar.',
      'Adicione a batata em pedaços e cozinhe na panela aberta.',
      'Ajuste o sal e deixe o caldo encorpar ligeiramente.',
    ],
    rendimentoPorcaoG: 240,
    tempoMin: 70,
    complexidade: 'media',
    obsOperacional: 'Acrescente a batata só no fim para não desmanchar no transporte.',
    nutricao: { kcal: 320, prot: 26, carb: 14, gord: 16, fibra: 2, sodio: 470 },
    substituicoes: ['Músculo no lugar do acém', 'Mandioquinha no lugar da batata'],
    adequacaoRefeitorio: 90,
  },
  {
    nome: 'Carne com mandioca',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'bovina',
    tags: ['regional', 'ensopado'],
    ingredientes: [
      { item: 'Músculo', unid: 'kg', porPessoa: 0.14 },
      { item: 'Mandioca', unid: 'kg', porPessoa: 0.06 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Óleo', unid: 'ml', porPessoa: 8 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Doure o músculo em cubos na pressão com alho e cebola.',
      'Cubra com água e cozinhe na pressão até a carne soltar.',
      'Junte a mandioca em pedaços e cozinhe até ficar macia.',
      'Deixe parte da mandioca desmanchar para engrossar o caldo.',
    ],
    rendimentoPorcaoG: 250,
    tempoMin: 80,
    complexidade: 'media',
    obsOperacional: 'Cozinhe a mandioca separada se a carne já estiver no ponto, evita virar purê.',
    nutricao: { kcal: 330, prot: 26, carb: 16, gord: 16, fibra: 2, sodio: 480 },
    substituicoes: ['Acém no lugar do músculo', 'Inhame no lugar da mandioca'],
    adequacaoRefeitorio: 86,
  },
  {
    nome: 'Carne assada fatiada',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'bovina',
    tags: ['assado', 'forno'],
    ingredientes: [
      { item: 'Lagarto', unid: 'kg', porPessoa: 0.15 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Óleo', unid: 'ml', porPessoa: 8 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Tempere a peça de lagarto com alho, sal e cebola e deixe marinar.',
      'Sele a peça inteira na panela para dourar a superfície.',
      'Asse coberto no forno com um pouco de líquido até ficar macia.',
      'Deixe descansar antes de fatiar fino contra as fibras.',
    ],
    rendimentoPorcaoG: 200,
    tempoMin: 85,
    complexidade: 'media',
    obsOperacional: 'Fatie só na hora do serviço; o caldo do assado vira molho coado.',
    nutricao: { kcal: 320, prot: 31, carb: 3, gord: 19, fibra: 0, sodio: 450 },
    substituicoes: ['Coxão duro no lugar do lagarto', 'Patinho em peça'],
    adequacaoRefeitorio: 84,
  },
  {
    nome: 'Costela ao molho',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'bovina',
    tags: ['molho', 'comfort'],
    ingredientes: [
      { item: 'Costela Bovina', unid: 'kg', porPessoa: 0.16 },
      { item: 'Molho de tomate', unid: 'un', porPessoa: 0.04 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Tempere a costela e doure os pedaços na pressão.',
      'Refogue cebola e alho e adicione o molho de tomate.',
      'Cubra com água e cozinhe na pressão até a carne soltar do osso.',
      'Reduza o molho na panela aberta até ganhar corpo.',
    ],
    rendimentoPorcaoG: 230,
    tempoMin: 90,
    complexidade: 'media',
    obsOperacional: 'Costela rende menos por causa do osso; calcule porção com folga.',
    nutricao: { kcal: 420, prot: 26, carb: 8, gord: 30, fibra: 1, sodio: 580 },
    substituicoes: ['Acém ao molho para baratear', 'Costela minga'],
    adequacaoRefeitorio: 80,
  },
  {
    nome: 'Almôndegas ao sugo',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'bovina',
    tags: ['moida', 'molho'],
    ingredientes: [
      { item: 'Carne Moída', unid: 'kg', porPessoa: 0.12 },
      { item: 'Molho de tomate', unid: 'un', porPessoa: 0.04 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Tempere a carne moída e modele as almôndegas.',
      'Doure as bolinhas no óleo até firmar por fora.',
      'Prepare o molho com cebola, alho e molho de tomate.',
      'Cozinhe as almôndegas no molho em fogo baixo até ficarem macias.',
    ],
    rendimentoPorcaoG: 200,
    tempoMin: 50,
    complexidade: 'media',
    obsOperacional: 'Padronize o tamanho com porcionador para cozimento uniforme.',
    nutricao: { kcal: 320, prot: 25, carb: 9, gord: 20, fibra: 1, sodio: 590 },
    substituicoes: ['Acém moído', 'Adicionar farinha de rosca à massa'],
    adequacaoRefeitorio: 85,
  },
  {
    nome: 'Carne com legumes',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'bovina',
    tags: ['ensopado', 'leve'],
    ingredientes: [
      { item: 'Patinho', unid: 'kg', porPessoa: 0.13 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.04 },
      { item: 'Ervilha', unid: 'kg', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Óleo', unid: 'ml', porPessoa: 8 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Corte a carne em cubos e doure com cebola.',
      'Cubra com água e cozinhe até começar a amaciar.',
      'Adicione a cenoura em cubos e cozinhe até quase no ponto.',
      'Finalize com a ervilha e ajuste o sal.',
    ],
    rendimentoPorcaoG: 230,
    tempoMin: 55,
    complexidade: 'media',
    obsOperacional: 'Acrescente os legumes em ordem de cozimento para manter a textura.',
    nutricao: { kcal: 300, prot: 27, carb: 10, gord: 15, fibra: 3, sodio: 440 },
    substituicoes: ['Acém no lugar do patinho', 'Vagem no lugar da ervilha'],
    adequacaoRefeitorio: 87,
  },
  {
    nome: 'Iscas de carne acebolada',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'bovina',
    tags: ['classico', 'rapido'],
    ingredientes: [
      { item: 'Tiras de Carne', unid: 'kg', porPessoa: 0.14 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.05 },
      { item: 'Pimentão', unid: 'kg', porPessoa: 0.03, opcional: true },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Óleo', unid: 'ml', porPessoa: 8 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Tempere as iscas com alho e sal.',
      'Sele as tiras em fogo alto sem amontoar na panela.',
      'Acrescente cebola e pimentão em tiras e refogue rápido.',
      'Salteie até a cebola murchar mantendo a carne suculenta.',
    ],
    rendimentoPorcaoG: 190,
    tempoMin: 40,
    complexidade: 'baixa',
    obsOperacional: 'Trabalhe em lotes no fogo alto para selar e não cozinhar na água.',
    nutricao: { kcal: 310, prot: 28, carb: 6, gord: 18, fibra: 1, sodio: 450 },
    substituicoes: ['Patinho em tiras', 'Sem pimentão para perfil mais neutro'],
    adequacaoRefeitorio: 86,
  },
  {
    nome: 'Fraldinha assada',
    categoria: 'principal',
    classe: 'premium',
    proteina: 'bovina',
    tags: ['assado', 'premium'],
    ingredientes: [
      { item: 'Fraldinha', unid: 'kg', porPessoa: 0.15 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.005 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Tempere a fraldinha com alho e sal grosso.',
      'Sele a peça em fogo forte para formar crosta.',
      'Leve ao forno alto até atingir o ponto desejado.',
      'Deixe descansar e fatie fino contra as fibras.',
    ],
    rendimentoPorcaoG: 190,
    tempoMin: 55,
    complexidade: 'media',
    obsOperacional: 'Corte sempre contra a fibra; ponto ao malpassado mantém maciez.',
    nutricao: { kcal: 380, prot: 30, carb: 2, gord: 27, fibra: 0, sodio: 460 },
    substituicoes: ['Maminha no lugar da fraldinha', 'Alcatra em peça'],
    adequacaoRefeitorio: 78,
  },
  {
    nome: 'Cupim assado',
    categoria: 'principal',
    classe: 'premium',
    proteina: 'bovina',
    tags: ['assado', 'premium'],
    ingredientes: [
      { item: 'Cupim', unid: 'kg', porPessoa: 0.16 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.005 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Tempere o cupim com alho, sal e cebola.',
      'Embale em papel alumínio com um pouco de líquido.',
      'Asse em forno baixo por tempo longo até ficar muito macio.',
      'Abra, doure a superfície e fatie para servir.',
    ],
    rendimentoPorcaoG: 200,
    tempoMin: 90,
    complexidade: 'alta',
    obsOperacional: 'Cozimento lento é essencial; programe com antecedência no forno.',
    nutricao: { kcal: 440, prot: 26, carb: 2, gord: 34, fibra: 0, sodio: 470 },
    substituicoes: ['Acém assado para baratear', 'Costela desossada'],
    adequacaoRefeitorio: 74,
  },
  {
    nome: 'Carne seca com abóbora',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'bovina',
    tags: ['regional', 'nordestina'],
    ingredientes: [
      { item: 'Carne Seca', unid: 'kg', porPessoa: 0.13 },
      { item: 'Abóbora', unid: 'kg', porPessoa: 0.06 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Óleo', unid: 'ml', porPessoa: 8 },
    ],
    preparo: [
      'Dessalgue a carne seca trocando a água várias vezes.',
      'Cozinhe na pressão até amaciar e desfie grosseiramente.',
      'Refogue cebola e alho e devolva a carne desfiada.',
      'Adicione a abóbora em cubos e cozinhe até desmanchar levemente.',
    ],
    rendimentoPorcaoG: 230,
    tempoMin: 80,
    complexidade: 'media',
    obsOperacional: 'O dessalgue precisa começar na véspera; não acrescente sal extra.',
    nutricao: { kcal: 330, prot: 30, carb: 10, gord: 18, fibra: 2, sodio: 780 },
    substituicoes: ['Charque no lugar da carne seca', 'Mandioca no lugar da abóbora'],
    adequacaoRefeitorio: 82,
  },
  {
    nome: 'Ensopado de músculo',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'bovina',
    tags: ['ensopado', 'comfort'],
    ingredientes: [
      { item: 'Músculo', unid: 'kg', porPessoa: 0.15 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.04 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Óleo', unid: 'ml', porPessoa: 8 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Doure o músculo em cubos na pressão.',
      'Refogue com cebola, alho e tomate.',
      'Cubra com água quente e cozinhe na pressão até a carne ficar gelatinosa.',
      'Junte a cenoura e cozinhe na panela aberta até o caldo encorpar.',
    ],
    rendimentoPorcaoG: 240,
    tempoMin: 80,
    complexidade: 'media',
    obsOperacional: 'O colágeno do músculo dá caldo encorpado; ótimo para servir com arroz.',
    nutricao: { kcal: 300, prot: 27, carb: 7, gord: 16, fibra: 2, sodio: 460 },
    substituicoes: ['Acém no lugar do músculo', 'Adicionar batata'],
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Boi à jardineira',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'bovina',
    tags: ['ensopado', 'colorido'],
    ingredientes: [
      { item: 'Acém', unid: 'kg', porPessoa: 0.14 },
      { item: 'Batata', unid: 'kg', porPessoa: 0.04 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.04 },
      { item: 'Ervilha', unid: 'kg', porPessoa: 0.02 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Óleo', unid: 'ml', porPessoa: 8 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Doure a carne em cubos e refogue com cebola.',
      'Cozinhe na pressão com água até amaciar.',
      'Acrescente batata e cenoura em cubos e cozinhe na panela aberta.',
      'Finalize com a ervilha e ajuste o tempero.',
    ],
    rendimentoPorcaoG: 250,
    tempoMin: 70,
    complexidade: 'media',
    obsOperacional: 'Padronize o corte dos legumes em cubos para cozimento parelho.',
    nutricao: { kcal: 320, prot: 26, carb: 16, gord: 15, fibra: 3, sodio: 470 },
    substituicoes: ['Patinho no lugar do acém', 'Vagem no lugar da ervilha'],
    adequacaoRefeitorio: 86,
  },
  {
    nome: 'Carne ao molho madeira',
    categoria: 'principal',
    classe: 'premium',
    proteina: 'bovina',
    tags: ['molho', 'premium'],
    ingredientes: [
      { item: 'Patinho', unid: 'kg', porPessoa: 0.14 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Molho de tomate', unid: 'un', porPessoa: 0.02 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Óleo', unid: 'ml', porPessoa: 8 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Sele os medalhões ou cubos de patinho em fogo alto.',
      'Refogue cebola e prepare a base de molho escuro.',
      'Adicione molho de tomate e caldo e deixe reduzir.',
      'Volte a carne ao molho e aqueça até nappar.',
    ],
    rendimentoPorcaoG: 200,
    tempoMin: 55,
    complexidade: 'media',
    obsOperacional: 'Champignon fatiado é opcional; o molho deve ficar brilhante e encorpado.',
    nutricao: { kcal: 350, prot: 29, carb: 9, gord: 21, fibra: 1, sodio: 600 },
    substituicoes: ['Filé mignon em ocasião especial', 'Coxão mole'],
    adequacaoRefeitorio: 80,
  },
  {
    nome: 'Bife à milanesa',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'bovina',
    tags: ['empanado', 'comfort'],
    ingredientes: [
      { item: 'Patinho', unid: 'kg', porPessoa: 0.14 },
      { item: 'Ovo', unid: 'un', porPessoa: 0.5 },
      { item: 'Farinha de Rosca', unid: 'kg', porPessoa: 0.03 },
      { item: 'Óleo', unid: 'ml', porPessoa: 15 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Tempere os bifes finos com sal e alho.',
      'Passe na farinha de trigo, no ovo batido e na farinha de rosca.',
      'Frite em óleo quente até dourar dos dois lados.',
      'Escorra sobre papel e mantenha aquecido em forno baixo.',
    ],
    rendimentoPorcaoG: 190,
    tempoMin: 50,
    complexidade: 'media',
    obsOperacional: 'Empanar em linha de produção; fritar em lotes para manter a crocância.',
    nutricao: { kcal: 400, prot: 28, carb: 18, gord: 24, fibra: 1, sodio: 520 },
    substituicoes: ['Coxão mole no lugar do patinho', 'Assar no forno para versão leve'],
    adequacaoRefeitorio: 82,
  },
  {
    nome: 'Carne moída com ervilha',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'bovina',
    tags: ['moida', 'comfort'],
    ingredientes: [
      { item: 'Carne Moída', unid: 'kg', porPessoa: 0.12 },
      { item: 'Ervilha', unid: 'kg', porPessoa: 0.04 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.03 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Refogue cebola e alho no óleo.',
      'Adicione a carne moída e solte os grumos.',
      'Junte o tomate e cozinhe até formar molho.',
      'Acrescente a ervilha e aqueça por alguns minutos.',
    ],
    rendimentoPorcaoG: 190,
    tempoMin: 35,
    complexidade: 'baixa',
    obsOperacional: 'Ervilha congelada vai no fim para manter cor e textura.',
    nutricao: { kcal: 300, prot: 25, carb: 8, gord: 17, fibra: 2, sodio: 450 },
    substituicoes: ['Acém moído', 'Milho no lugar da ervilha'],
    adequacaoRefeitorio: 89,
  },
  {
    nome: 'Lagarto ao molho',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'bovina',
    tags: ['molho', 'fatiado'],
    ingredientes: [
      { item: 'Lagarto', unid: 'kg', porPessoa: 0.15 },
      { item: 'Molho de tomate', unid: 'un', porPessoa: 0.04 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Sele a peça de lagarto inteira na pressão.',
      'Refogue cebola e alho e adicione o molho de tomate.',
      'Cozinhe na pressão com água até a peça ficar macia.',
      'Deixe esfriar levemente, fatie fino e devolva ao molho.',
    ],
    rendimentoPorcaoG: 210,
    tempoMin: 80,
    complexidade: 'media',
    obsOperacional: 'Fatiar frio sai mais uniforme; reaquecer as fatias no molho.',
    nutricao: { kcal: 320, prot: 31, carb: 8, gord: 17, fibra: 1, sodio: 560 },
    substituicoes: ['Coxão duro no lugar do lagarto', 'Patinho em peça'],
    adequacaoRefeitorio: 84,
  },
  {
    nome: 'Hambúrguer caseiro de panela',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'bovina',
    tags: ['moida', 'comfort'],
    ingredientes: [
      { item: 'Carne Moída', unid: 'kg', porPessoa: 0.13 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Molho de tomate', unid: 'un', porPessoa: 0.03 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Tempere a carne moída e modele os discos.',
      'Sele os hambúrgueres na chapa dos dois lados.',
      'Prepare um molho rápido com cebola e molho de tomate.',
      'Banhe os discos no molho e mantenha aquecido para servir.',
    ],
    rendimentoPorcaoG: 190,
    tempoMin: 45,
    complexidade: 'media',
    obsOperacional: 'Use porcionador para discos iguais; servir ao molho evita ressecar.',
    nutricao: { kcal: 330, prot: 26, carb: 7, gord: 21, fibra: 1, sodio: 560 },
    substituicoes: ['Acém moído', 'Servir sem molho, grelhado'],
    adequacaoRefeitorio: 84,
  },
  {
    nome: 'Carne desfiada ao tomate',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'bovina',
    tags: ['desfiada', 'molho'],
    ingredientes: [
      { item: 'Acém', unid: 'kg', porPessoa: 0.15 },
      { item: 'Molho de tomate', unid: 'un', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Pimentão', unid: 'kg', porPessoa: 0.03, opcional: true },
      { item: 'Óleo', unid: 'ml', porPessoa: 8 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Cozinhe o acém na pressão até ficar bem macio.',
      'Desfie a carne ainda morna com dois garfos.',
      'Refogue cebola e pimentão e adicione o molho de tomate.',
      'Junte a carne desfiada e apure até incorporar o molho.',
    ],
    rendimentoPorcaoG: 210,
    tempoMin: 75,
    complexidade: 'media',
    obsOperacional: 'Desfie morno; aproveite o caldo do cozimento no refogado.',
    nutricao: { kcal: 300, prot: 28, carb: 7, gord: 16, fibra: 1, sodio: 520 },
    substituicoes: ['Músculo no lugar do acém', 'Patinho desfiado'],
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Acém ao molho de cebola',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'bovina',
    tags: ['molho', 'ensopado'],
    ingredientes: [
      { item: 'Acém', unid: 'kg', porPessoa: 0.15 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.06 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Óleo', unid: 'ml', porPessoa: 8 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Doure o acém em cubos na pressão.',
      'Adicione bastante cebola e deixe murchar com a carne.',
      'Cubra com água e cozinhe na pressão até amaciar.',
      'Abra e reduza até a cebola formar um molho natural.',
    ],
    rendimentoPorcaoG: 220,
    tempoMin: 70,
    complexidade: 'media',
    obsOperacional: 'A cebola em volume dá doçura ao molho sem ingredientes extras.',
    nutricao: { kcal: 310, prot: 27, carb: 7, gord: 18, fibra: 1, sodio: 440 },
    substituicoes: ['Músculo no lugar do acém', 'Patinho em cubos'],
    adequacaoRefeitorio: 89,
  },
  {
    nome: 'Bife role de panela ao tomate',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'bovina',
    tags: ['molho', 'classico'],
    ingredientes: [
      { item: 'Coxão Mole', unid: 'kg', porPessoa: 0.15 },
      { item: 'Molho de tomate', unid: 'un', porPessoa: 0.04 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Óleo', unid: 'ml', porPessoa: 8 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Corte os bifes em pedaços e tempere.',
      'Doure a carne na panela e reserve.',
      'Refogue cebola e alho e adicione o molho de tomate.',
      'Cozinhe a carne no molho em fogo baixo até ficar macia.',
    ],
    rendimentoPorcaoG: 210,
    tempoMin: 60,
    complexidade: 'media',
    obsOperacional: 'Cozimento lento no molho amacia cortes magros sem ressecar.',
    nutricao: { kcal: 320, prot: 30, carb: 8, gord: 17, fibra: 1, sodio: 560 },
    substituicoes: ['Patinho no lugar do coxão mole', 'Acém para baratear'],
    adequacaoRefeitorio: 85,
  },
  {
    nome: 'Patinho grelhado ao alho',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'bovina',
    tags: ['grelhado', 'leve'],
    ingredientes: [
      { item: 'Patinho', unid: 'kg', porPessoa: 0.15 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.006 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Tempere os bifes com alho amassado e sal.',
      'Aqueça bem a chapa com pouco óleo.',
      'Grelhe os bifes rapidamente dos dois lados.',
      'Finalize com lascas de alho dourado por cima.',
    ],
    rendimentoPorcaoG: 180,
    tempoMin: 35,
    complexidade: 'baixa',
    obsOperacional: 'Chapa bem quente sela e mantém suculência; não fure os bifes.',
    nutricao: { kcal: 290, prot: 32, carb: 2, gord: 16, fibra: 0, sodio: 420 },
    substituicoes: ['Alcatra em ocasião premium', 'Coxão mole'],
    adequacaoRefeitorio: 86,
  },
  {
    nome: 'Cubos de carne com pimentão',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'bovina',
    tags: ['refogado', 'colorido'],
    ingredientes: [
      { item: 'Patinho', unid: 'kg', porPessoa: 0.14 },
      { item: 'Pimentão', unid: 'kg', porPessoa: 0.05 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.03 },
      { item: 'Óleo', unid: 'ml', porPessoa: 8 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Corte a carne em cubos e sele em fogo alto.',
      'Refogue cebola e tomate até formar base.',
      'Adicione os pimentões em tiras e mantenha crocantes.',
      'Cozinhe rapidamente até a carne ficar no ponto.',
    ],
    rendimentoPorcaoG: 200,
    tempoMin: 45,
    complexidade: 'baixa',
    obsOperacional: 'Pimentão entra no fim para manter cor viva e textura.',
    nutricao: { kcal: 300, prot: 28, carb: 7, gord: 16, fibra: 2, sodio: 440 },
    substituicoes: ['Tiras de carne no lugar dos cubos', 'Acém em cubos'],
    adequacaoRefeitorio: 86,
  },
  {
    nome: 'Carne moída com cenoura',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'bovina',
    tags: ['moida', 'comfort'],
    ingredientes: [
      { item: 'Carne Moída', unid: 'kg', porPessoa: 0.12 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.04 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.03 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Refogue cebola e alho no óleo.',
      'Adicione a carne moída e solte os grumos.',
      'Junte a cenoura ralada e o tomate picado.',
      'Cozinhe até a cenoura amaciar e o líquido reduzir.',
    ],
    rendimentoPorcaoG: 190,
    tempoMin: 35,
    complexidade: 'baixa',
    obsOperacional: 'Cenoura ralada cozinha rápido e rende mais a carne.',
    nutricao: { kcal: 290, prot: 25, carb: 8, gord: 16, fibra: 2, sodio: 440 },
    substituicoes: ['Acém moído', 'Adicionar ervilha'],
    adequacaoRefeitorio: 90,
  },
];
