import type { Receita } from './tipos';

export const PRATOS: Receita[] = [
  {
    nome: 'Feijoada Completa',
    categoria: 'principal',
    classe: 'premium',
    proteina: 'suina',
    tags: ['regional', 'prato-unico', 'comfort'],
    ingredientes: [
      { item: 'Feijão Preto', unid: 'kg', porPessoa: 0.05 },
      { item: 'Acém', unid: 'kg', porPessoa: 0.06 },
      { item: 'Linguiça Calabresa', unid: 'kg', porPessoa: 0.04 },
      { item: 'Bacon', unid: 'kg', porPessoa: 0.02 },
      { item: 'Arroz', unid: 'kg', porPessoa: 0.07 },
      { item: 'Couve', unid: 'mç', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.01 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Farinha de mandioca', unid: 'kg', porPessoa: 0.02, opcional: true },
    ],
    preparo: [
      'Deixe o feijão preto de molho na véspera e cozinhe com as carnes salgadas dessalgadas.',
      'Refogue cebola e alho, junte a calabresa e o bacon dourados ao caldo de feijão.',
      'Cozinhe em fogo baixo até encorpar e as carnes ficarem macias.',
      'Sirva com arroz branco, couve refogada e farofa.',
    ],
    rendimentoPorcaoG: 420,
    tempoMin: 120,
    complexidade: 'alta',
    obsOperacional: 'Dessalgue as carnes com antecedência; produza o feijão no dia anterior para render melhor.',
    nutricao: { kcal: 600, prot: 32, carb: 55, gord: 28, fibra: 11, sodio: 1050 },
    substituicoes: ['Acém por costelinha suína', 'Couve por brócolis'],
    adequacaoRefeitorio: 80,
  },
  {
    nome: 'Baião de Dois',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'suina',
    tags: ['regional', 'nordestina', 'prato-unico'],
    ingredientes: [
      { item: 'Arroz', unid: 'kg', porPessoa: 0.07 },
      { item: 'Feijão fradinho', unid: 'kg', porPessoa: 0.05 },
      { item: 'Linguiça Calabresa', unid: 'kg', porPessoa: 0.05 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.01 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Couve', unid: 'mç', porPessoa: 0.02 },
      { item: 'Óleo', unid: 'ml', porPessoa: 5 },
    ],
    preparo: [
      'Cozinhe o feijão fradinho até ficar macio e reserve com o caldo.',
      'Refogue cebola, alho e a linguiça em cubos.',
      'Junte o arroz, o feijão e o caldo e cozinhe como um arroz cremoso.',
      'Finalize com couve picada e ajuste o sal.',
    ],
    rendimentoPorcaoG: 380,
    tempoMin: 70,
    complexidade: 'media',
    obsOperacional: 'O ponto cremoso vem do caldo do feijão; reserve líquido suficiente.',
    nutricao: { kcal: 520, prot: 22, carb: 62, gord: 18, fibra: 9, sodio: 780 },
    substituicoes: ['Feijão fradinho por feijão de corda', 'Calabresa por carne de sol'],
    adequacaoRefeitorio: 90,
  },
  {
    nome: 'Arroz Carreteiro',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'bovina',
    tags: ['regional', 'gaucha', 'prato-unico'],
    ingredientes: [
      { item: 'Arroz', unid: 'kg', porPessoa: 0.08 },
      { item: 'Acém', unid: 'kg', porPessoa: 0.1 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.015 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.02 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
    ],
    preparo: [
      'Doure a carne em cubos pequenos até soltar a água e tostar.',
      'Refogue cebola, alho e tomate junto à carne.',
      'Adicione o arroz, refogue e cozinhe com água quente até o ponto.',
      'Acerte o sal e sirva bem soltinho.',
    ],
    rendimentoPorcaoG: 400,
    tempoMin: 60,
    complexidade: 'media',
    obsOperacional: 'Tradicionalmente usa charque; o acém é alternativa econômica em escala.',
    nutricao: { kcal: 540, prot: 28, carb: 58, gord: 20, fibra: 4, sodio: 720 },
    substituicoes: ['Acém por charque dessalgado'],
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Galinhada Caipira',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'frango',
    tags: ['regional', 'mineira', 'prato-unico'],
    ingredientes: [
      { item: 'Arroz', unid: 'kg', porPessoa: 0.08 },
      { item: 'File de frango sem osso', unid: 'kg', porPessoa: 0.11 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.015 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.02 },
      { item: 'Milho', unid: 'lata', porPessoa: 0.05 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
    ],
    preparo: [
      'Doure o frango em pedaços temperado com alho e sal.',
      'Refogue cebola e tomate, junte o arroz e refogue.',
      'Cozinhe com água quente até o arroz ficar macio.',
      'Finalize com milho e açafrão, ajustando o sal.',
    ],
    rendimentoPorcaoG: 400,
    tempoMin: 65,
    complexidade: 'media',
    obsOperacional: 'O açafrão-da-terra dá cor; cozinhe o arroz al dente para não empapar no buffet.',
    nutricao: { kcal: 520, prot: 30, carb: 56, gord: 16, fibra: 4, sodio: 680 },
    substituicoes: ['Filé de frango por sobrecoxa desossada'],
    adequacaoRefeitorio: 90,
  },
  {
    nome: 'Virado à Paulista',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'suina',
    tags: ['regional', 'paulista', 'prato-unico'],
    ingredientes: [
      { item: 'Arroz', unid: 'kg', porPessoa: 0.07 },
      { item: 'Feijão Carioca', unid: 'kg', porPessoa: 0.04 },
      { item: 'Linguiça Toscana', unid: 'kg', porPessoa: 0.06 },
      { item: 'Farinha de mandioca', unid: 'kg', porPessoa: 0.025 },
      { item: 'Couve', unid: 'mç', porPessoa: 0.03 },
      { item: 'Ovos', unid: 'un', porPessoa: 1 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
    ],
    preparo: [
      'Cozinhe o feijão e amasse parte para o virado, engrossando com farinha.',
      'Grelhe a linguiça toscana em rodelas.',
      'Refogue a couve em tiras com alho e frite os ovos.',
      'Monte com arroz, virado de feijão, couve, linguiça e ovo.',
    ],
    rendimentoPorcaoG: 410,
    tempoMin: 70,
    complexidade: 'media',
    obsOperacional: 'Monte os componentes separados no buffet para manter textura.',
    nutricao: { kcal: 580, prot: 26, carb: 60, gord: 24, fibra: 8, sodio: 820 },
    substituicoes: ['Linguiça toscana por bisteca suína'],
    adequacaoRefeitorio: 84,
  },
  {
    nome: 'Yakisoba de Frango',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'frango',
    tags: ['prato-unico', 'comfort'],
    ingredientes: [
      { item: 'Macarrão', unid: 'kg', porPessoa: 0.08 },
      { item: 'File de frango sem osso', unid: 'kg', porPessoa: 0.1 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
    ],
    preparo: [
      'Cozinhe o macarrão al dente e reserve com fio de óleo.',
      'Salteie o frango em tiras em fogo alto.',
      'Junte os legumes em fatias e refogue rápido para manter crocância.',
      'Misture o macarrão e o molho à base de shoyu e finalize.',
    ],
    rendimentoPorcaoG: 400,
    tempoMin: 50,
    complexidade: 'media',
    obsOperacional: 'Salteie em lotes para não cozinhar os legumes no vapor.',
    nutricao: { kcal: 500, prot: 28, carb: 58, gord: 14, fibra: 5, sodio: 900 },
    substituicoes: ['Frango por carne bovina em tiras'],
    adequacaoRefeitorio: 86,
  },
  {
    nome: 'Yakisoba de Carne',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'bovina',
    tags: ['prato-unico', 'comfort'],
    ingredientes: [
      { item: 'Macarrão', unid: 'kg', porPessoa: 0.08 },
      { item: 'Acém', unid: 'kg', porPessoa: 0.1 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
    ],
    preparo: [
      'Cozinhe o macarrão al dente e reserve.',
      'Salteie a carne em tiras finas em fogo bem alto.',
      'Adicione cenoura e cebola, refogando rapidamente.',
      'Incorpore o macarrão e o molho de shoyu, ajustando o sal.',
    ],
    rendimentoPorcaoG: 400,
    tempoMin: 50,
    complexidade: 'media',
    obsOperacional: 'Corte a carne no sentido contrário das fibras para ficar macia.',
    nutricao: { kcal: 520, prot: 29, carb: 57, gord: 17, fibra: 5, sodio: 920 },
    substituicoes: ['Acém por patinho em tiras'],
    adequacaoRefeitorio: 85,
  },
  {
    nome: 'Risoto de Frango',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'frango',
    tags: ['prato-unico', 'comfort'],
    ingredientes: [
      { item: 'Arroz', unid: 'kg', porPessoa: 0.08 },
      { item: 'File de frango sem osso', unid: 'kg', porPessoa: 0.1 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.015 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Creme de Leite', unid: 'lata', porPessoa: 0.04 },
      { item: 'Mussarela', unid: 'kg', porPessoa: 0.02 },
    ],
    preparo: [
      'Refogue cebola e alho e doure o frango em cubos.',
      'Junte o arroz e refogue, adicionando caldo aos poucos.',
      'Cozinhe mexendo até ficar cremoso.',
      'Finalize com creme de leite e queijo ralado.',
    ],
    rendimentoPorcaoG: 390,
    tempoMin: 60,
    complexidade: 'media',
    obsOperacional: 'Em escala use arroz comum com caldo concentrado; mexa para liberar amido.',
    nutricao: { kcal: 540, prot: 30, carb: 55, gord: 20, fibra: 3, sodio: 700 },
    substituicoes: ['Frango por cogumelos para versão vegetariana'],
    adequacaoRefeitorio: 82,
  },
  {
    nome: 'Lasanha à Bolonhesa',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'bovina',
    tags: ['prato-unico', 'comfort'],
    ingredientes: [
      { item: 'Massa de lasanha', unid: 'kg', porPessoa: 0.08 },
      { item: 'Carne Moída', unid: 'kg', porPessoa: 0.1 },
      { item: 'Molho de tomate', unid: 'kg', porPessoa: 0.06 },
      { item: 'Mussarela', unid: 'kg', porPessoa: 0.04 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.01 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
    ],
    preparo: [
      'Prepare o molho bolonhesa refogando carne moída com cebola, alho e tomate.',
      'Monte camadas alternando massa, molho e queijo em assadeiras GN.',
      'Cubra com bastante mussarela.',
      'Asse até gratinar e descanse antes de porcionar.',
    ],
    rendimentoPorcaoG: 380,
    tempoMin: 90,
    complexidade: 'alta',
    obsOperacional: 'Use massa pré-cozida ou de cozimento direto; deixe descansar 15 min para cortar.',
    nutricao: { kcal: 560, prot: 30, carb: 48, gord: 26, fibra: 4, sodio: 850 },
    substituicoes: ['Carne moída por frango desfiado'],
    adequacaoRefeitorio: 84,
  },
  {
    nome: 'Macarronada à Bolonhesa',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'bovina',
    tags: ['prato-unico', 'comfort'],
    ingredientes: [
      { item: 'Macarrão', unid: 'kg', porPessoa: 0.09 },
      { item: 'Carne Moída', unid: 'kg', porPessoa: 0.09 },
      { item: 'Molho de tomate', unid: 'kg', porPessoa: 0.05 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.01 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Mussarela', unid: 'kg', porPessoa: 0.015, opcional: true },
    ],
    preparo: [
      'Cozinhe o macarrão al dente.',
      'Refogue a carne moída com cebola e alho.',
      'Junte o molho de tomate e cozinhe até apurar.',
      'Misture ao macarrão ou sirva por cima, com queijo ralado.',
    ],
    rendimentoPorcaoG: 400,
    tempoMin: 50,
    complexidade: 'baixa',
    obsOperacional: 'Sirva o macarrão e o molho separados no buffet para não grudar.',
    nutricao: { kcal: 520, prot: 26, carb: 62, gord: 18, fibra: 4, sodio: 720 },
    substituicoes: ['Carne moída por proteína de soja hidratada'],
    adequacaoRefeitorio: 90,
  },
  {
    nome: 'Talharim ao Sugo com Almôndegas',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'bovina',
    tags: ['prato-unico', 'comfort', 'molho'],
    ingredientes: [
      { item: 'Macarrão', unid: 'kg', porPessoa: 0.09 },
      { item: 'Carne Moída', unid: 'kg', porPessoa: 0.1 },
      { item: 'Molho de tomate', unid: 'kg', porPessoa: 0.06 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.01 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Ovos', unid: 'un', porPessoa: 0.2 },
    ],
    preparo: [
      'Tempere a carne moída com cebola, alho e ovo e modele as almôndegas.',
      'Doure as almôndegas e cozinhe no molho de tomate.',
      'Cozinhe o talharim al dente.',
      'Sirva o talharim coberto com o sugo e as almôndegas.',
    ],
    rendimentoPorcaoG: 410,
    tempoMin: 70,
    complexidade: 'media',
    obsOperacional: 'Modele as almôndegas em padronização de peso para cocção uniforme.',
    nutricao: { kcal: 540, prot: 28, carb: 58, gord: 20, fibra: 4, sodio: 780 },
    substituicoes: ['Almôndegas de frango'],
    adequacaoRefeitorio: 85,
  },
  {
    nome: 'Escondidinho de Carne Seca',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'bovina',
    tags: ['regional', 'nordestina', 'prato-unico'],
    ingredientes: [
      { item: 'Mandioca', unid: 'kg', porPessoa: 0.18 },
      { item: 'Acém', unid: 'kg', porPessoa: 0.1 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Creme de Leite', unid: 'lata', porPessoa: 0.03 },
      { item: 'Mussarela', unid: 'kg', porPessoa: 0.03 },
    ],
    preparo: [
      'Cozinhe a mandioca e faça um purê cremoso com creme de leite.',
      'Refogue a carne desfiada com cebola e alho.',
      'Monte camadas de purê, carne e purê em GN.',
      'Cubra com queijo e gratine.',
    ],
    rendimentoPorcaoG: 400,
    tempoMin: 90,
    complexidade: 'alta',
    obsOperacional: 'Dessalgue bem a carne; o purê deve ficar firme para porcionar.',
    nutricao: { kcal: 560, prot: 28, carb: 52, gord: 24, fibra: 5, sodio: 950 },
    substituicoes: ['Mandioca por batata', 'Carne seca por carne moída'],
    adequacaoRefeitorio: 82,
  },
  {
    nome: 'Escondidinho de Frango',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'frango',
    tags: ['prato-unico', 'comfort'],
    ingredientes: [
      { item: 'Mandioca', unid: 'kg', porPessoa: 0.18 },
      { item: 'File de frango sem osso', unid: 'kg', porPessoa: 0.11 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Creme de Leite', unid: 'lata', porPessoa: 0.03 },
      { item: 'Mussarela', unid: 'kg', porPessoa: 0.03 },
    ],
    preparo: [
      'Cozinhe a mandioca e faça purê com creme de leite.',
      'Refogue o frango desfiado com cebola, alho e tomate.',
      'Monte purê, frango e purê em assadeira GN.',
      'Cubra com mussarela e gratine.',
    ],
    rendimentoPorcaoG: 400,
    tempoMin: 85,
    complexidade: 'media',
    obsOperacional: 'Cozinhe o frango em caldo para desfiar com mais sabor.',
    nutricao: { kcal: 520, prot: 30, carb: 50, gord: 20, fibra: 5, sodio: 720 },
    substituicoes: ['Mandioca por purê de batata'],
    adequacaoRefeitorio: 86,
  },
  {
    nome: 'Tutu de Feijão à Mineira',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'suina',
    tags: ['regional', 'mineira', 'prato-unico'],
    ingredientes: [
      { item: 'Feijão Carioca', unid: 'kg', porPessoa: 0.05 },
      { item: 'Farinha de mandioca', unid: 'kg', porPessoa: 0.03 },
      { item: 'Linguiça Calabresa', unid: 'kg', porPessoa: 0.04 },
      { item: 'Bacon', unid: 'kg', porPessoa: 0.015 },
      { item: 'Arroz', unid: 'kg', porPessoa: 0.07 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.015 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
    ],
    preparo: [
      'Cozinhe e bata o feijão, depois engrosse com farinha de mandioca mexendo sempre.',
      'Refogue bacon, calabresa, cebola e alho.',
      'Incorpore o refogado ao tutu até dar liga.',
      'Sirva com arroz branco.',
    ],
    rendimentoPorcaoG: 390,
    tempoMin: 75,
    complexidade: 'media',
    obsOperacional: 'Mexa constantemente ao adicionar a farinha para não empelotar.',
    nutricao: { kcal: 540, prot: 22, carb: 60, gord: 22, fibra: 10, sodio: 820 },
    substituicoes: ['Calabresa por torresmo'],
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Vaca Atolada',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'bovina',
    tags: ['regional', 'mineira', 'prato-unico'],
    ingredientes: [
      { item: 'Acém', unid: 'kg', porPessoa: 0.12 },
      { item: 'Mandioca', unid: 'kg', porPessoa: 0.15 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.03 },
      { item: 'Arroz', unid: 'kg', porPessoa: 0.06 },
    ],
    preparo: [
      'Cozinhe a carne em pedaços até ficar macia, refogada com cebola, alho e tomate.',
      'Adicione a mandioca em pedaços e cozinhe até desmanchar parcialmente.',
      'Deixe o caldo encorpar com o amido da mandioca.',
      'Sirva com arroz branco.',
    ],
    rendimentoPorcaoG: 420,
    tempoMin: 110,
    complexidade: 'alta',
    obsOperacional: 'Tradicional com costela; o acém é alternativa econômica e rende caldo.',
    nutricao: { kcal: 560, prot: 30, carb: 50, gord: 24, fibra: 6, sodio: 760 },
    substituicoes: ['Acém por costela bovina'],
    adequacaoRefeitorio: 80,
  },
  {
    nome: 'Cuscuz Paulista',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'peixe',
    tags: ['regional', 'paulista', 'prato-unico'],
    ingredientes: [
      { item: 'Farinha de mandioca', unid: 'kg', porPessoa: 0.06 },
      { item: 'Filé de peixe', unid: 'kg', porPessoa: 0.07 },
      { item: 'Molho de tomate', unid: 'kg', porPessoa: 0.05 },
      { item: 'Ovos', unid: 'un', porPessoa: 1 },
      { item: 'Milho', unid: 'lata', porPessoa: 0.04 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.015 },
    ],
    preparo: [
      'Refogue cebola, tomate, sardinha/peixe e milho num molho temperado.',
      'Hidrate a farinha de milho com o molho até dar liga.',
      'Forre a forma com ovos e legumes para decorar e preencha com a massa.',
      'Pressione, deixe firmar e desenforme para porcionar.',
    ],
    rendimentoPorcaoG: 360,
    tempoMin: 80,
    complexidade: 'media',
    obsOperacional: 'Tradicional com sardinha em lata; firme bem antes de desenformar.',
    nutricao: { kcal: 480, prot: 22, carb: 56, gord: 16, fibra: 6, sodio: 820 },
    substituicoes: ['Peixe por sardinha em lata', 'Versão com frango desfiado'],
    adequacaoRefeitorio: 78,
  },
  {
    nome: 'Maria Isabel',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'bovina',
    tags: ['regional', 'nordestina', 'prato-unico'],
    ingredientes: [
      { item: 'Arroz', unid: 'kg', porPessoa: 0.08 },
      { item: 'Acém', unid: 'kg', porPessoa: 0.1 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.015 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.02 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
    ],
    preparo: [
      'Dessalgue a carne seca e refogue desfiada com cebola e alho.',
      'Junte o arroz e refogue rapidamente.',
      'Cozinhe com água quente até o arroz ficar macio.',
      'Finalize com cheiro-verde e ajuste o sal.',
    ],
    rendimentoPorcaoG: 390,
    tempoMin: 65,
    complexidade: 'media',
    obsOperacional: 'Clássico arroz com carne seca; controle o sal por causa da carne salgada.',
    nutricao: { kcal: 520, prot: 26, carb: 60, gord: 18, fibra: 4, sodio: 980 },
    substituicoes: ['Carne seca por acém cozido desfiado'],
    adequacaoRefeitorio: 86,
  },
  {
    nome: 'Feijão Tropeiro',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'suina',
    tags: ['regional', 'mineira', 'prato-unico'],
    ingredientes: [
      { item: 'Feijão Carioca', unid: 'kg', porPessoa: 0.05 },
      { item: 'Farinha de mandioca', unid: 'kg', porPessoa: 0.03 },
      { item: 'Linguiça Calabresa', unid: 'kg', porPessoa: 0.04 },
      { item: 'Bacon', unid: 'kg', porPessoa: 0.02 },
      { item: 'Ovos', unid: 'un', porPessoa: 1 },
      { item: 'Couve', unid: 'mç', porPessoa: 0.02 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
    ],
    preparo: [
      'Cozinhe o feijão e escorra bem.',
      'Frite bacon e calabresa, junte ovos mexidos e couve.',
      'Adicione o feijão e a farinha, misturando para dar liga.',
      'Ajuste o sal e sirva imediatamente.',
    ],
    rendimentoPorcaoG: 370,
    tempoMin: 60,
    complexidade: 'media',
    obsOperacional: 'Adicione a farinha por último para manter a textura solta.',
    nutricao: { kcal: 550, prot: 24, carb: 52, gord: 26, fibra: 11, sodio: 880 },
    substituicoes: ['Calabresa por linguiça toscana'],
    adequacaoRefeitorio: 87,
  },
  {
    nome: 'Bobó de Camarão',
    categoria: 'principal',
    classe: 'premium',
    proteina: 'peixe',
    tags: ['regional', 'baiana', 'prato-unico'],
    ingredientes: [
      { item: 'Mandioca', unid: 'kg', porPessoa: 0.18 },
      { item: 'Filé de peixe', unid: 'kg', porPessoa: 0.09 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.03 },
      { item: 'Creme de Leite', unid: 'lata', porPessoa: 0.03 },
      { item: 'Arroz', unid: 'kg', porPessoa: 0.06 },
    ],
    preparo: [
      'Cozinhe e bata a mandioca formando um creme.',
      'Refogue camarão/peixe com cebola, alho e tomate.',
      'Junte o creme de mandioca, leite de coco e azeite de dendê.',
      'Cozinhe até encorpar e sirva com arroz branco.',
    ],
    rendimentoPorcaoG: 400,
    tempoMin: 90,
    complexidade: 'alta',
    obsOperacional: 'Use camarão quando viável; o dendê e o leite de coco definem o prato.',
    nutricao: { kcal: 540, prot: 24, carb: 54, gord: 24, fibra: 5, sodio: 760 },
    substituicoes: ['Camarão por filé de peixe em cubos'],
    adequacaoRefeitorio: 74,
  },
  {
    nome: 'Arroz de Forno',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'frango',
    tags: ['prato-unico', 'comfort'],
    ingredientes: [
      { item: 'Arroz', unid: 'kg', porPessoa: 0.08 },
      { item: 'File de frango sem osso', unid: 'kg', porPessoa: 0.09 },
      { item: 'Linguiça Calabresa', unid: 'kg', porPessoa: 0.03 },
      { item: 'Milho', unid: 'lata', porPessoa: 0.04 },
      { item: 'Creme de Leite', unid: 'lata', porPessoa: 0.03 },
      { item: 'Mussarela', unid: 'kg', porPessoa: 0.03 },
    ],
    preparo: [
      'Misture arroz cozido com frango desfiado e calabresa refogada.',
      'Junte milho e creme de leite para dar cremosidade.',
      'Espalhe em GN e cubra com mussarela.',
      'Asse até gratinar.',
    ],
    rendimentoPorcaoG: 380,
    tempoMin: 60,
    complexidade: 'baixa',
    obsOperacional: 'Ótima saída para reaproveitar arroz do dia anterior.',
    nutricao: { kcal: 520, prot: 26, carb: 56, gord: 20, fibra: 3, sodio: 740 },
    substituicoes: ['Frango por presunto e queijo'],
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Strogonoff com Arroz e Batata Palha',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'frango',
    tags: ['prato-unico', 'comfort'],
    ingredientes: [
      { item: 'File de frango sem osso', unid: 'kg', porPessoa: 0.12 },
      { item: 'Creme de Leite', unid: 'lata', porPessoa: 0.05 },
      { item: 'Molho de tomate', unid: 'kg', porPessoa: 0.02 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.015 },
      { item: 'Arroz', unid: 'kg', porPessoa: 0.07 },
      { item: 'Batata Palha', unid: 'pct', porPessoa: 0.02 },
    ],
    preparo: [
      'Doure o frango em cubos com cebola.',
      'Adicione molho de tomate, mostarda e ketchup e refogue.',
      'Finalize com creme de leite sem ferver.',
      'Sirva com arroz branco e batata palha por cima.',
    ],
    rendimentoPorcaoG: 400,
    tempoMin: 55,
    complexidade: 'baixa',
    obsOperacional: 'Adicione o creme de leite por último para não talhar.',
    nutricao: { kcal: 540, prot: 30, carb: 50, gord: 22, fibra: 2, sodio: 720 },
    substituicoes: ['Frango por carne bovina em tiras'],
    adequacaoRefeitorio: 90,
  },
  {
    nome: 'Panqueca de Carne ao Sugo',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'bovina',
    tags: ['prato-unico', 'comfort', 'molho'],
    ingredientes: [
      { item: 'Ovos', unid: 'un', porPessoa: 1 },
      { item: 'Carne Moída', unid: 'kg', porPessoa: 0.09 },
      { item: 'Molho de tomate', unid: 'kg', porPessoa: 0.06 },
      { item: 'Mussarela', unid: 'kg', porPessoa: 0.02 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.01 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
    ],
    preparo: [
      'Prepare a massa fina das panquecas e grelhe os discos.',
      'Refogue a carne moída com cebola e alho para o recheio.',
      'Recheie, enrole e disponha em GN.',
      'Cubra com molho de tomate e queijo e leve ao forno.',
    ],
    rendimentoPorcaoG: 360,
    tempoMin: 75,
    complexidade: 'media',
    obsOperacional: 'Produza os discos com antecedência e monte em lote.',
    nutricao: { kcal: 500, prot: 28, carb: 40, gord: 24, fibra: 3, sodio: 760 },
    substituicoes: ['Recheio de frango', 'Recheio de queijo'],
    adequacaoRefeitorio: 80,
  },
  {
    nome: 'Nhoque ao Sugo com Carne',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'bovina',
    tags: ['prato-unico', 'comfort', 'molho'],
    ingredientes: [
      { item: 'Mandioca', unid: 'kg', porPessoa: 0.1 },
      { item: 'Carne Moída', unid: 'kg', porPessoa: 0.09 },
      { item: 'Molho de tomate', unid: 'kg', porPessoa: 0.06 },
      { item: 'Ovos', unid: 'un', porPessoa: 0.3 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.01 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
    ],
    preparo: [
      'Cozinhe a mandioca/batata, amasse e faça a massa do nhoque com farinha e ovo.',
      'Modele e cozinhe os nhoques em água fervente.',
      'Prepare o molho de carne moída com tomate.',
      'Sirva os nhoques cobertos com o sugo de carne.',
    ],
    rendimentoPorcaoG: 400,
    tempoMin: 80,
    complexidade: 'alta',
    obsOperacional: 'Cozinhe o nhoque em lotes próximo ao serviço para não empapar.',
    nutricao: { kcal: 520, prot: 24, carb: 64, gord: 16, fibra: 5, sodio: 720 },
    substituicoes: ['Molho de carne por sugo simples'],
    adequacaoRefeitorio: 78,
  },
  {
    nome: 'Arroz à Grega com Frango',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'frango',
    tags: ['prato-unico', 'comfort'],
    ingredientes: [
      { item: 'Arroz', unid: 'kg', porPessoa: 0.08 },
      { item: 'File de frango sem osso', unid: 'kg', porPessoa: 0.1 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.03 },
      { item: 'Milho', unid: 'lata', porPessoa: 0.04 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.015 },
      { item: 'Óleo', unid: 'ml', porPessoa: 5 },
    ],
    preparo: [
      'Doure o frango em cubos com cebola.',
      'Junte o arroz e refogue.',
      'Cozinhe com água e adicione cenoura, milho e ervilha.',
      'Finalize com passas, ajustando o sal.',
    ],
    rendimentoPorcaoG: 390,
    tempoMin: 60,
    complexidade: 'baixa',
    obsOperacional: 'Cozinhe os legumes ligeiramente firmes para colorir o prato.',
    nutricao: { kcal: 500, prot: 28, carb: 60, gord: 12, fibra: 5, sodio: 640 },
    substituicoes: ['Frango por presunto em cubos'],
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Frango com Quiabo à Mineira',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'frango',
    tags: ['regional', 'mineira', 'prato-unico'],
    ingredientes: [
      { item: 'File de frango sem osso', unid: 'kg', porPessoa: 0.13 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.03 },
      { item: 'Arroz', unid: 'kg', porPessoa: 0.07 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
    ],
    preparo: [
      'Refogue o frango em pedaços com cebola, alho e tomate.',
      'Salteie o quiabo separado para reduzir a baba.',
      'Junte o quiabo ao frango com um pouco de caldo.',
      'Sirva com arroz e angu, se desejar.',
    ],
    rendimentoPorcaoG: 380,
    tempoMin: 70,
    complexidade: 'media',
    obsOperacional: 'Salteie o quiabo em fogo alto e seco para não soltar viscosidade.',
    nutricao: { kcal: 480, prot: 32, carb: 48, gord: 14, fibra: 6, sodio: 680 },
    substituicoes: ['Frango por costelinha suína'],
    adequacaoRefeitorio: 82,
  },
  {
    nome: 'Moqueca Baiana de Peixe',
    categoria: 'principal',
    classe: 'premium',
    proteina: 'peixe',
    tags: ['regional', 'baiana', 'prato-unico'],
    ingredientes: [
      { item: 'Filé de peixe', unid: 'kg', porPessoa: 0.13 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.025 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.04 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Arroz', unid: 'kg', porPessoa: 0.07 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
    ],
    preparo: [
      'Tempere o peixe com limão, alho e sal.',
      'Monte camadas de cebola, tomate e pimentão em panela larga.',
      'Adicione o peixe, leite de coco e azeite de dendê.',
      'Cozinhe em fogo baixo sem mexer demais e sirva com arroz.',
    ],
    rendimentoPorcaoG: 400,
    tempoMin: 60,
    complexidade: 'media',
    obsOperacional: 'Cozinhe próximo ao serviço para o peixe não desmanchar no buffet.',
    nutricao: { kcal: 480, prot: 30, carb: 46, gord: 18, fibra: 4, sodio: 660 },
    substituicoes: ['Peixe por camarão', 'Versão sem dendê com azeite'],
    adequacaoRefeitorio: 75,
  },
  {
    nome: 'Dobradinha com Feijão Branco',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'bovina',
    tags: ['regional', 'prato-unico'],
    ingredientes: [
      { item: 'Acém', unid: 'kg', porPessoa: 0.12 },
      { item: 'Feijão fradinho', unid: 'kg', porPessoa: 0.05 },
      { item: 'Linguiça Calabresa', unid: 'kg', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.03 },
      { item: 'Arroz', unid: 'kg', porPessoa: 0.06 },
    ],
    preparo: [
      'Limpe e cozinhe a dobradinha (bucho) até ficar macia.',
      'Refogue com cebola, alho, tomate e calabresa.',
      'Junte o feijão branco já cozido e apure o caldo.',
      'Sirva com arroz branco.',
    ],
    rendimentoPorcaoG: 410,
    tempoMin: 120,
    complexidade: 'alta',
    obsOperacional: 'Prato de nicho; limpeza e pré-cozimento longo são essenciais.',
    nutricao: { kcal: 520, prot: 30, carb: 48, gord: 22, fibra: 8, sodio: 880 },
    substituicoes: ['Dobradinha por acém em cubos para versão suave'],
    adequacaoRefeitorio: 70,
  },
  {
    nome: 'Galinha Caipira com Angu',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'frango',
    tags: ['regional', 'mineira', 'prato-unico'],
    ingredientes: [
      { item: 'File de frango sem osso', unid: 'kg', porPessoa: 0.13 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.03 },
      { item: 'Farinha de mandioca', unid: 'kg', porPessoa: 0.04 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
    ],
    preparo: [
      'Refogue o frango em pedaços com cebola, alho e tomate até dourar.',
      'Cozinhe com caldo para formar molho encorpado.',
      'Prepare o angu com fubá e água, mexendo até soltar do fundo.',
      'Sirva o frango com o angu cremoso.',
    ],
    rendimentoPorcaoG: 400,
    tempoMin: 90,
    complexidade: 'media',
    obsOperacional: 'O angu deve ser mexido sem parar; mantenha aquecido para não firmar.',
    nutricao: { kcal: 500, prot: 30, carb: 50, gord: 16, fibra: 4, sodio: 700 },
    substituicoes: ['Angu por polenta cremosa'],
    adequacaoRefeitorio: 80,
  },
  {
    nome: 'Risoto de Legumes',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['prato-unico', 'vegetariano'],
    ingredientes: [
      { item: 'Arroz', unid: 'kg', porPessoa: 0.09 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.04 },
      { item: 'Milho', unid: 'lata', porPessoa: 0.04 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.015 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Creme de Leite', unid: 'lata', porPessoa: 0.04 },
      { item: 'Mussarela', unid: 'kg', porPessoa: 0.02 },
    ],
    preparo: [
      'Refogue cebola e alho e junte o arroz.',
      'Adicione caldo de legumes aos poucos, mexendo.',
      'Incorpore cenoura, ervilha e milho durante o cozimento.',
      'Finalize com creme de leite e queijo.',
    ],
    rendimentoPorcaoG: 380,
    tempoMin: 55,
    complexidade: 'media',
    obsOperacional: 'Boa opção vegetariana de prato-único; mexa para liberar amido.',
    nutricao: { kcal: 460, prot: 14, carb: 64, gord: 16, fibra: 6, sodio: 600 },
    substituicoes: ['Adicionar frango para versão proteica'],
    adequacaoRefeitorio: 82,
  },
  {
    nome: 'Macarrão à Carbonara Simplificada',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'suina',
    tags: ['prato-unico', 'comfort', 'molho'],
    ingredientes: [
      { item: 'Macarrão', unid: 'kg', porPessoa: 0.09 },
      { item: 'Bacon', unid: 'kg', porPessoa: 0.04 },
      { item: 'Ovos', unid: 'un', porPessoa: 1 },
      { item: 'Creme de Leite', unid: 'lata', porPessoa: 0.04 },
      { item: 'Mussarela', unid: 'kg', porPessoa: 0.02 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.01 },
    ],
    preparo: [
      'Cozinhe o macarrão al dente.',
      'Frite o bacon em cubos até dourar.',
      'Misture ovos batidos com creme de leite e queijo fora do fogo.',
      'Una o macarrão quente ao molho e ao bacon para encorpar.',
    ],
    rendimentoPorcaoG: 380,
    tempoMin: 45,
    complexidade: 'media',
    obsOperacional: 'Em escala use creme de leite para estabilizar o molho de ovos.',
    nutricao: { kcal: 560, prot: 22, carb: 58, gord: 26, fibra: 3, sodio: 820 },
    substituicoes: ['Bacon por presunto'],
    adequacaoRefeitorio: 80,
  },
  {
    nome: 'Cuscuz Nordestino com Ovo',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'ovo',
    tags: ['regional', 'nordestina', 'prato-unico'],
    ingredientes: [
      { item: 'Farinha de mandioca', unid: 'kg', porPessoa: 0.08 },
      { item: 'Ovos', unid: 'un', porPessoa: 2 },
      { item: 'Linguiça Calabresa', unid: 'kg', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.01 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.02 },
      { item: 'Óleo', unid: 'ml', porPessoa: 5 },
    ],
    preparo: [
      'Hidrate a flocão de milho com água e sal e cozinhe na cuscuzeira.',
      'Frite ovos mexidos com cebola, tomate e calabresa.',
      'Sirva o cuscuz fatiado com o ovo por cima.',
      'Regue com manteiga, se desejar.',
    ],
    rendimentoPorcaoG: 350,
    tempoMin: 45,
    complexidade: 'baixa',
    obsOperacional: 'Use flocão de milho na cuscuzeira; ponto úmido para não esfarelar.',
    nutricao: { kcal: 480, prot: 18, carb: 56, gord: 20, fibra: 5, sodio: 640 },
    substituicoes: ['Calabresa por charque', 'Versão só com ovo'],
    adequacaoRefeitorio: 84,
  },
  {
    nome: 'Panelada Nordestina',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'bovina',
    tags: ['regional', 'nordestina', 'prato-unico'],
    ingredientes: [
      { item: 'Acém', unid: 'kg', porPessoa: 0.13 },
      { item: 'Mandioca', unid: 'kg', porPessoa: 0.12 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.03 },
      { item: 'Arroz', unid: 'kg', porPessoa: 0.06 },
    ],
    preparo: [
      'Cozinhe as miúdas/carne bovina até amaciar com temperos.',
      'Refogue cebola, alho e tomate e junte à carne.',
      'Adicione mandioca em pedaços e cozinhe até engrossar o caldo.',
      'Sirva com arroz e farinha.',
    ],
    rendimentoPorcaoG: 420,
    tempoMin: 120,
    complexidade: 'alta',
    obsOperacional: 'Prato de nicho; versão com acém facilita a aceitação no refeitório.',
    nutricao: { kcal: 540, prot: 30, carb: 50, gord: 22, fibra: 6, sodio: 820 },
    substituicoes: ['Miúdos por acém em cubos'],
    adequacaoRefeitorio: 70,
  },
  {
    nome: 'Arrumadinho de Carne Seca',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'bovina',
    tags: ['regional', 'nordestina', 'prato-unico'],
    ingredientes: [
      { item: 'Acém', unid: 'kg', porPessoa: 0.1 },
      { item: 'Feijão fradinho', unid: 'kg', porPessoa: 0.05 },
      { item: 'Farinha de mandioca', unid: 'kg', porPessoa: 0.03 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Arroz', unid: 'kg', porPessoa: 0.05 },
    ],
    preparo: [
      'Dessalgue e refogue a carne seca desfiada.',
      'Cozinhe o feijão fradinho e prepare farofa de mandioca.',
      'Faça vinagrete de tomate e cebola.',
      'Monte em camadas: feijão, carne, farofa e vinagrete.',
    ],
    rendimentoPorcaoG: 390,
    tempoMin: 80,
    complexidade: 'media',
    obsOperacional: 'Monte os componentes separados no buffet para o cliente arrumar o prato.',
    nutricao: { kcal: 520, prot: 28, carb: 54, gord: 18, fibra: 9, sodio: 960 },
    substituicoes: ['Carne seca por acém desfiado'],
    adequacaoRefeitorio: 80,
  },
  {
    nome: 'Carne de Sol com Mandioca',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'bovina',
    tags: ['regional', 'nordestina', 'prato-unico'],
    ingredientes: [
      { item: 'Acém', unid: 'kg', porPessoa: 0.13 },
      { item: 'Mandioca', unid: 'kg', porPessoa: 0.18 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
    ],
    preparo: [
      'Dessalgue a carne de sol e grelhe em pedaços.',
      'Cozinhe a mandioca até ficar macia e doure levemente.',
      'Refogue a carne com cebola e alho.',
      'Sirva a carne sobre a mandioca, com manteiga de garrafa, se houver.',
    ],
    rendimentoPorcaoG: 400,
    tempoMin: 90,
    complexidade: 'media',
    obsOperacional: 'Dessalgue bem para controlar o sódio; grelhe próximo ao serviço.',
    nutricao: { kcal: 540, prot: 32, carb: 50, gord: 20, fibra: 4, sodio: 980 },
    substituicoes: ['Mandioca cozida por mandioca frita', 'Acém por carne de sol tradicional'],
    adequacaoRefeitorio: 82,
  },
  {
    nome: 'Sarapatel Regional',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'suina',
    tags: ['regional', 'nordestina', 'prato-unico'],
    ingredientes: [
      { item: 'Acém', unid: 'kg', porPessoa: 0.12 },
      { item: 'Linguiça Toscana', unid: 'kg', porPessoa: 0.04 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.025 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.03 },
      { item: 'Arroz', unid: 'kg', porPessoa: 0.06 },
    ],
    preparo: [
      'Cozinhe as carnes e miúdos suínos temperados até amaciar.',
      'Refogue com cebola, alho, tomate e pimentões.',
      'Apure o caldo bem temperado com cheiro-verde.',
      'Sirva com arroz branco.',
    ],
    rendimentoPorcaoG: 400,
    tempoMin: 110,
    complexidade: 'alta',
    obsOperacional: 'Prato muito regional e de nicho; versão adaptada com carne suína facilita a aceitação.',
    nutricao: { kcal: 520, prot: 30, carb: 46, gord: 24, fibra: 5, sodio: 940 },
    substituicoes: ['Miúdos por carne suína em cubos'],
    adequacaoRefeitorio: 70,
  },
];
