import type { Receita } from './tipos';

export const PRATOS: Receita[] = [
  {
    nome: 'Arroz e Feijão',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['base', 'classico', 'economico', 'fixa'],
    ingredientes: [
      { item: 'Arroz', unid: 'kg', porPessoa: 0.09 },
      { item: 'Feijão Carioca', unid: 'kg', porPessoa: 0.05 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.005 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.01 },
      { item: 'Óleo', unid: 'ml', porPessoa: 8 },
      { item: 'Sal', unid: 'g', porPessoa: 5 },
    ],
    preparo: [
      'Refogue o alho no óleo e cozinhe o arroz com água quente e sal (proporção dobrada) até secar.',
      'Cozinhe o feijão na pressão até ficar macio.',
      'Prepare um refogado de alho e cebola e incorpore parte do feijão amassado para encorpar o caldo.',
      'Junte o restante do feijão, cozinhe até apurar e sirva ao lado do arroz soltinho.',
    ],
    rendimentoPorcaoG: 340,
    tempoMin: 60,
    complexidade: 'media',
    obsOperacional: 'Base do prato feito brasileiro: cozinhar arroz e feijão em lotes separados; manter ambos em rechaud a 65°C.',
    nutricao: { kcal: 380, prot: 14, carb: 72, gord: 5, fibra: 8, sodio: 630 },
    substituicoes: ['Feijão preto no lugar do carioca', 'Arroz integral para mais fibras'],
    adequacaoRefeitorio: 98,
  },
  {
    nome: 'Arroz branco',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['base', 'classico', 'economico'],
    ingredientes: [
      { item: 'Arroz', unid: 'kg', porPessoa: 0.09 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Óleo', unid: 'ml', porPessoa: 5 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Refogue o alho no óleo até dourar.',
      'Adicione o arroz lavado e refogue rapidamente.',
      'Acrescente água quente e sal na proporção dobrada.',
      'Cozinhe em fogo baixo até secar e soltar os grãos.',
    ],
    rendimentoPorcaoG: 160,
    tempoMin: 25,
    complexidade: 'baixa',
    obsOperacional: 'Manter em rechaud a 65°C; soltar com garfo antes de servir.',
    nutricao: { kcal: 205, prot: 4, carb: 44, gord: 2, fibra: 1, sodio: 320 },
    substituicoes: ['Arroz integral para versão mais fibrosa'],
    adequacaoRefeitorio: 96,
  },
  {
    nome: 'Arroz à grega',
    categoria: 'guarnicao',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['colorido', 'classico', 'festivo'],
    ingredientes: [
      { item: 'Arroz', unid: 'kg', porPessoa: 0.09 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.02 },
      { item: 'Milho (lata)', unid: 'lata', porPessoa: 0.05 },
      { item: 'Uva passa', unid: 'g', porPessoa: 8, opcional: true },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Cozinhe o arroz branco soltinho como base.',
      'Refogue a cenoura em cubinhos e o milho escorrido.',
      'Misture os legumes e a uva passa ao arroz.',
      'Ajuste o sal e finalize misturando delicadamente.',
    ],
    rendimentoPorcaoG: 170,
    tempoMin: 35,
    complexidade: 'media',
    nutricao: { kcal: 230, prot: 5, carb: 48, gord: 3, fibra: 3, sodio: 300 },
    substituicoes: ['Sem uva passa para perfil menos doce'],
    adequacaoRefeitorio: 90,
  },
  {
    nome: 'Arroz com brócolis',
    categoria: 'guarnicao',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['base', 'equilibrado', 'verde'],
    ingredientes: [
      { item: 'Arroz', unid: 'kg', porPessoa: 0.09 },
      { item: 'Brócolis', unid: 'kg', porPessoa: 0.04 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Óleo', unid: 'ml', porPessoa: 5 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Cozinhe o arroz branco soltinho.',
      'Branqueie os buquês de brócolis e refogue no alho.',
      'Misture o brócolis ao arroz já cozido.',
      'Ajuste o sal e sirva ainda quente.',
    ],
    rendimentoPorcaoG: 165,
    tempoMin: 30,
    complexidade: 'media',
    nutricao: { kcal: 215, prot: 5, carb: 43, gord: 3, fibra: 3, sodio: 290 },
    adequacaoRefeitorio: 89,
  },
  {
    nome: 'Arroz de forno com queijo',
    categoria: 'guarnicao',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['assado', 'gratinado', 'cremoso'],
    ingredientes: [
      { item: 'Arroz', unid: 'kg', porPessoa: 0.09 },
      { item: 'Mussarela', unid: 'kg', porPessoa: 0.03 },
      { item: 'Creme de Leite', unid: 'g', porPessoa: 20 },
      { item: 'Milho (lata)', unid: 'lata', porPessoa: 0.04 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Misture o arroz cozido com creme de leite e milho.',
      'Transfira para travessa e cubra com mussarela.',
      'Leve ao forno a 200°C até gratinar.',
      'Sirva em porções diretamente da travessa.',
    ],
    rendimentoPorcaoG: 180,
    tempoMin: 45,
    complexidade: 'media',
    obsOperacional: 'Montar em GN para gratinar em lotes; servir quente.',
    nutricao: { kcal: 310, prot: 11, carb: 42, gord: 11, fibra: 2, sodio: 420 },
    adequacaoRefeitorio: 85,
  },
  {
    nome: 'Arroz biro-biro',
    categoria: 'guarnicao',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['classico', 'incrementado', 'crocante'],
    ingredientes: [
      { item: 'Arroz', unid: 'kg', porPessoa: 0.09 },
      { item: 'Bacon', unid: 'kg', porPessoa: 0.02 },
      { item: 'Milho (lata)', unid: 'lata', porPessoa: 0.04 },
      { item: 'Batata', unid: 'kg', porPessoa: 0.04 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Frite o bacon em cubos e a batata palha à parte.',
      'Refogue o milho na gordura do bacon.',
      'Misture tudo ao arroz branco cozido.',
      'Finalize com a batata palha por cima.',
    ],
    rendimentoPorcaoG: 175,
    tempoMin: 40,
    complexidade: 'media',
    nutricao: { kcal: 320, prot: 9, carb: 46, gord: 12, fibra: 2, sodio: 440 },
    adequacaoRefeitorio: 84,
  },
  {
    nome: 'Feijão carioca',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['base', 'classico', 'economico'],
    ingredientes: [
      { item: 'Feijão Carioca', unid: 'kg', porPessoa: 0.05 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.01 },
      { item: 'Óleo', unid: 'ml', porPessoa: 5 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Cozinhe o feijão na pressão até ficar macio.',
      'Prepare um refogado de alho e cebola.',
      'Adicione parte do feijão amassado ao refogado para encorpar o caldo.',
      'Junte o restante e cozinhe até apurar.',
    ],
    rendimentoPorcaoG: 180,
    tempoMin: 55,
    complexidade: 'media',
    obsOperacional: 'Cozinhar em lotes na pressão; manter caldo na consistência.',
    nutricao: { kcal: 175, prot: 10, carb: 28, gord: 3, fibra: 7, sodio: 310 },
    substituicoes: ['Feijão preto como alternativa'],
    adequacaoRefeitorio: 95,
  },
  {
    nome: 'Feijão preto',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['base', 'classico', 'economico'],
    ingredientes: [
      { item: 'Feijão Preto', unid: 'kg', porPessoa: 0.05 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.01 },
      { item: 'Bacon', unid: 'kg', porPessoa: 0.015, opcional: true },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Cozinhe o feijão preto na pressão até amaciar.',
      'Refogue alho, cebola e bacon.',
      'Incorpore o feijão e parte amassada para encorpar.',
      'Cozinhe até o caldo ficar escuro e apurado.',
    ],
    rendimentoPorcaoG: 180,
    tempoMin: 60,
    complexidade: 'media',
    nutricao: { kcal: 190, prot: 11, carb: 28, gord: 4, fibra: 8, sodio: 340 },
    adequacaoRefeitorio: 94,
  },
  {
    nome: 'Tutu de feijão',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['mineiro', 'classico', 'encorpado'],
    ingredientes: [
      { item: 'Feijão Carioca', unid: 'kg', porPessoa: 0.05 },
      { item: 'Farinha de mandioca', unid: 'kg', porPessoa: 0.03 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Bacon', unid: 'kg', porPessoa: 0.015 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Bata o feijão cozido com o caldo até ficar cremoso.',
      'Refogue alho e bacon em panela larga.',
      'Adicione o feijão batido e aqueça.',
      'Incorpore a farinha aos poucos mexendo até engrossar.',
    ],
    rendimentoPorcaoG: 175,
    tempoMin: 50,
    complexidade: 'media',
    nutricao: { kcal: 245, prot: 11, carb: 38, gord: 6, fibra: 7, sodio: 380 },
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Purê de batata',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['cremoso', 'classico', 'conforto'],
    ingredientes: [
      { item: 'Batata', unid: 'kg', porPessoa: 0.16 },
      { item: 'Leite', unid: 'ml', porPessoa: 40 },
      { item: 'Manteiga', unid: 'g', porPessoa: 8 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Cozinhe as batatas até ficarem bem macias.',
      'Amasse ainda quentes formando um purê liso.',
      'Incorpore o leite morno e a manteiga.',
      'Ajuste o sal e mexa até obter textura cremosa.',
    ],
    rendimentoPorcaoG: 180,
    tempoMin: 35,
    complexidade: 'baixa',
    nutricao: { kcal: 215, prot: 5, carb: 36, gord: 6, fibra: 3, sodio: 320 },
    substituicoes: ['Purê de mandioquinha como alternativa'],
    adequacaoRefeitorio: 92,
  },
  {
    nome: 'Purê de mandioquinha',
    categoria: 'guarnicao',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['cremoso', 'conforto', 'raiz'],
    ingredientes: [
      { item: 'Mandioquinha', unid: 'kg', porPessoa: 0.16 },
      { item: 'Leite', unid: 'ml', porPessoa: 40 },
      { item: 'Manteiga', unid: 'g', porPessoa: 8 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Cozinhe a mandioquinha até ficar macia.',
      'Passe pelo espremedor ainda quente.',
      'Acrescente leite morno e manteiga.',
      'Mexa até formar um purê aveludado.',
    ],
    rendimentoPorcaoG: 180,
    tempoMin: 40,
    complexidade: 'baixa',
    nutricao: { kcal: 220, prot: 4, carb: 40, gord: 6, fibra: 3, sodio: 300 },
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Batata rústica assada',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['assado', 'crocante', 'economico'],
    ingredientes: [
      { item: 'Batata', unid: 'kg', porPessoa: 0.16 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Óleo', unid: 'ml', porPessoa: 8 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Corte as batatas em gomos com casca.',
      'Tempere com alho, óleo, sal e ervas.',
      'Disponha em assadeira em camada única.',
      'Asse a 220°C até dourar e ficar crocante.',
    ],
    rendimentoPorcaoG: 170,
    tempoMin: 45,
    complexidade: 'baixa',
    obsOperacional: 'Virar na metade do tempo para dourar por igual.',
    nutricao: { kcal: 200, prot: 4, carb: 34, gord: 6, fibra: 3, sodio: 290 },
    adequacaoRefeitorio: 90,
  },
  {
    nome: 'Batata sauté',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['salteado', 'classico', 'rapido'],
    ingredientes: [
      { item: 'Batata', unid: 'kg', porPessoa: 0.15 },
      { item: 'Manteiga', unid: 'g', porPessoa: 8 },
      { item: 'Salsinha', unid: 'g', porPessoa: 2 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Pré-cozinhe as batatas em cubos até ficarem firmes.',
      'Salteie na manteiga até dourar levemente.',
      'Tempere com sal e salsinha picada.',
      'Sirva imediatamente para manter a textura.',
    ],
    rendimentoPorcaoG: 165,
    tempoMin: 30,
    complexidade: 'baixa',
    nutricao: { kcal: 190, prot: 4, carb: 32, gord: 6, fibra: 3, sodio: 280 },
    adequacaoRefeitorio: 87,
  },
  {
    nome: 'Batata frita',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['frito', 'classico', 'crocante'],
    ingredientes: [
      { item: 'Batata', unid: 'kg', porPessoa: 0.14 },
      { item: 'Óleo', unid: 'ml', porPessoa: 15 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Corte as batatas em palitos e seque bem.',
      'Frite em óleo a 160°C para pré-cozimento.',
      'Aumente para 180°C e frite até dourar.',
      'Escorra, salgue e sirva imediatamente.',
    ],
    rendimentoPorcaoG: 150,
    tempoMin: 30,
    complexidade: 'baixa',
    obsOperacional: 'Servir logo após fritar; não manter em rechaud por muito tempo.',
    nutricao: { kcal: 290, prot: 4, carb: 38, gord: 14, fibra: 3, sodio: 300 },
    adequacaoRefeitorio: 80,
  },
  {
    nome: 'Mandioca cozida',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['cozido', 'raiz', 'economico'],
    ingredientes: [
      { item: 'Mandioca', unid: 'kg', porPessoa: 0.15 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
      { item: 'Manteiga', unid: 'g', porPessoa: 5, opcional: true },
    ],
    preparo: [
      'Descasque e corte a mandioca em pedaços.',
      'Cozinhe na pressão com sal até ficar macia.',
      'Escorra e retire os fiapos centrais.',
      'Finalize com manteiga se desejar.',
    ],
    rendimentoPorcaoG: 170,
    tempoMin: 40,
    complexidade: 'baixa',
    nutricao: { kcal: 230, prot: 2, carb: 50, gord: 3, fibra: 4, sodio: 260 },
    adequacaoRefeitorio: 90,
  },
  {
    nome: 'Mandioca frita',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['frito', 'raiz', 'crocante'],
    ingredientes: [
      { item: 'Mandioca', unid: 'kg', porPessoa: 0.14 },
      { item: 'Óleo', unid: 'ml', porPessoa: 15 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Cozinhe a mandioca até ficar al dente e corte em bastões.',
      'Aqueça o óleo a 180°C.',
      'Frite até dourar e ficar crocante por fora.',
      'Escorra, salgue e sirva quente.',
    ],
    rendimentoPorcaoG: 150,
    tempoMin: 45,
    complexidade: 'media',
    nutricao: { kcal: 300, prot: 2, carb: 48, gord: 12, fibra: 4, sodio: 290 },
    adequacaoRefeitorio: 82,
  },
  {
    nome: 'Polenta cremosa',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['cremoso', 'classico', 'conforto'],
    ingredientes: [
      { item: 'Fubá', unid: 'kg', porPessoa: 0.05 },
      { item: 'Manteiga', unid: 'g', porPessoa: 6 },
      { item: 'Mussarela', unid: 'kg', porPessoa: 0.015, opcional: true },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Dissolva o fubá em água fria.',
      'Leve ao fogo mexendo até engrossar.',
      'Cozinhe em fogo baixo até perder o gosto cru.',
      'Finalize com manteiga e queijo, ajustando o sal.',
    ],
    rendimentoPorcaoG: 180,
    tempoMin: 35,
    complexidade: 'media',
    obsOperacional: 'Mexer constantemente para não empelotar; servir bem quente.',
    nutricao: { kcal: 200, prot: 5, carb: 34, gord: 5, fibra: 2, sodio: 320 },
    substituicoes: ['Polenta frita a partir da mesma base'],
    adequacaoRefeitorio: 90,
  },
  {
    nome: 'Polenta frita',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['frito', 'crocante', 'aperitivo'],
    ingredientes: [
      { item: 'Fubá', unid: 'kg', porPessoa: 0.05 },
      { item: 'Óleo', unid: 'ml', porPessoa: 12 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Prepare uma polenta firme e espalhe em assadeira.',
      'Leve à geladeira até firmar e corte em bastões.',
      'Frite em óleo quente até dourar.',
      'Escorra, salgue e sirva crocante.',
    ],
    rendimentoPorcaoG: 150,
    tempoMin: 50,
    complexidade: 'media',
    nutricao: { kcal: 250, prot: 4, carb: 36, gord: 10, fibra: 2, sodio: 300 },
    adequacaoRefeitorio: 83,
  },
  {
    nome: 'Farofa de bacon',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['classico', 'crocante', 'acompanhamento'],
    ingredientes: [
      { item: 'Farinha de mandioca', unid: 'pct', porPessoa: 0.03 },
      { item: 'Bacon', unid: 'kg', porPessoa: 0.02 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.01 },
      { item: 'Manteiga', unid: 'g', porPessoa: 6 },
      { item: 'Sal', unid: 'g', porPessoa: 2 },
    ],
    preparo: [
      'Frite o bacon em cubos até dourar.',
      'Refogue a cebola na gordura com manteiga.',
      'Adicione a farinha aos poucos mexendo sempre.',
      'Torre até ficar crocante e ajuste o sal.',
    ],
    rendimentoPorcaoG: 130,
    tempoMin: 25,
    complexidade: 'baixa',
    nutricao: { kcal: 240, prot: 6, carb: 30, gord: 11, fibra: 3, sodio: 420 },
    substituicoes: ['Farofa de banana para versão adocicada'],
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Farofa de banana',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['agridoce', 'acompanhamento', 'caseiro'],
    ingredientes: [
      { item: 'Farinha de mandioca', unid: 'pct', porPessoa: 0.03 },
      { item: 'Banana', unid: 'kg', porPessoa: 0.04 },
      { item: 'Manteiga', unid: 'g', porPessoa: 6 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.008 },
      { item: 'Sal', unid: 'g', porPessoa: 2 },
    ],
    preparo: [
      'Refogue a cebola na manteiga.',
      'Adicione a banana em rodelas e doure levemente.',
      'Acrescente a farinha mexendo para torrar.',
      'Ajuste o sal mantendo o contraste agridoce.',
    ],
    rendimentoPorcaoG: 130,
    tempoMin: 25,
    complexidade: 'baixa',
    nutricao: { kcal: 230, prot: 3, carb: 38, gord: 8, fibra: 4, sodio: 280 },
    adequacaoRefeitorio: 86,
  },
  {
    nome: 'Nhoque ao molho de tomate',
    categoria: 'guarnicao',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['massa', 'classico', 'molho'],
    ingredientes: [
      { item: 'Batata', unid: 'kg', porPessoa: 0.12 },
      { item: 'Farinha de trigo', unid: 'kg', porPessoa: 0.04 },
      { item: 'Molho de tomate', unid: 'ml', porPessoa: 60 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Cozinhe e amasse as batatas, formando uma massa com a farinha.',
      'Modele os nhoques e cozinhe em água fervente.',
      'Retire assim que subirem à superfície.',
      'Sirva cobertos com molho de tomate quente.',
    ],
    rendimentoPorcaoG: 190,
    tempoMin: 55,
    complexidade: 'media',
    obsOperacional: 'Cozinhar em lotes pequenos para não grudar; molho à parte.',
    nutricao: { kcal: 280, prot: 7, carb: 54, gord: 4, fibra: 3, sodio: 410 },
    adequacaoRefeitorio: 84,
  },
  {
    nome: 'Macarrão alho e óleo',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['massa', 'classico', 'rapido'],
    ingredientes: [
      { item: 'Macarrão', unid: 'kg', porPessoa: 0.09 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.006 },
      { item: 'Óleo', unid: 'ml', porPessoa: 10 },
      { item: 'Salsinha', unid: 'g', porPessoa: 2 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Cozinhe o macarrão al dente em água com sal.',
      'Doure o alho fatiado no óleo.',
      'Misture o macarrão escorrido ao alho.',
      'Finalize com salsinha e sirva quente.',
    ],
    rendimentoPorcaoG: 180,
    tempoMin: 20,
    complexidade: 'baixa',
    nutricao: { kcal: 300, prot: 9, carb: 56, gord: 6, fibra: 3, sodio: 320 },
    substituicoes: ['Macarrão na manteiga para versão mais suave'],
    adequacaoRefeitorio: 91,
  },
  {
    nome: 'Macarrão ao sugo',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['massa', 'classico', 'molho'],
    ingredientes: [
      { item: 'Macarrão', unid: 'kg', porPessoa: 0.09 },
      { item: 'Molho de tomate', unid: 'ml', porPessoa: 70 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.01 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Prepare o molho refogando alho e cebola e adicionando tomate.',
      'Cozinhe o molho até apurar.',
      'Cozinhe o macarrão al dente.',
      'Misture a massa ao molho e sirva quente.',
    ],
    rendimentoPorcaoG: 190,
    tempoMin: 30,
    complexidade: 'baixa',
    nutricao: { kcal: 300, prot: 9, carb: 58, gord: 4, fibra: 4, sodio: 400 },
    adequacaoRefeitorio: 90,
  },
  {
    nome: 'Macarrão na manteiga',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['massa', 'simples', 'rapido'],
    ingredientes: [
      { item: 'Macarrão', unid: 'kg', porPessoa: 0.09 },
      { item: 'Manteiga', unid: 'g', porPessoa: 10 },
      { item: 'Salsinha', unid: 'g', porPessoa: 2, opcional: true },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Cozinhe o macarrão al dente.',
      'Escorra reservando um pouco da água do cozimento.',
      'Misture a manteiga até derreter e envolver a massa.',
      'Ajuste o sal e finalize com salsinha.',
    ],
    rendimentoPorcaoG: 180,
    tempoMin: 20,
    complexidade: 'baixa',
    nutricao: { kcal: 310, prot: 9, carb: 56, gord: 8, fibra: 3, sodio: 300 },
    adequacaoRefeitorio: 90,
  },
  {
    nome: 'Creme de milho',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['cremoso', 'conforto', 'caseiro'],
    ingredientes: [
      { item: 'Milho (lata)', unid: 'lata', porPessoa: 0.12 },
      { item: 'Leite', unid: 'ml', porPessoa: 40 },
      { item: 'Creme de Leite', unid: 'g', porPessoa: 15 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.008 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Bata o milho com o leite e coe se desejar mais liso.',
      'Refogue a cebola e adicione o creme de milho.',
      'Cozinhe mexendo até engrossar.',
      'Finalize com creme de leite e ajuste o sal.',
    ],
    rendimentoPorcaoG: 170,
    tempoMin: 30,
    complexidade: 'baixa',
    nutricao: { kcal: 210, prot: 5, carb: 32, gord: 7, fibra: 3, sodio: 350 },
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Angu',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['mineiro', 'classico', 'economico'],
    ingredientes: [
      { item: 'Fubá', unid: 'kg', porPessoa: 0.05 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
      { item: 'Óleo', unid: 'ml', porPessoa: 3, opcional: true },
    ],
    preparo: [
      'Dissolva o fubá em água fria.',
      'Leve ao fogo mexendo sem parar.',
      'Cozinhe até engrossar e perder o gosto cru.',
      'Ajuste o sal e sirva bem quente.',
    ],
    rendimentoPorcaoG: 180,
    tempoMin: 30,
    complexidade: 'baixa',
    nutricao: { kcal: 180, prot: 4, carb: 36, gord: 2, fibra: 2, sodio: 280 },
    adequacaoRefeitorio: 90,
  },
  {
    nome: 'Cuscuz de milho',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['nordestino', 'vapor', 'economico'],
    ingredientes: [
      { item: 'Flocão de milho', unid: 'kg', porPessoa: 0.05 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
      { item: 'Manteiga', unid: 'g', porPessoa: 5, opcional: true },
    ],
    preparo: [
      'Hidrate o flocão de milho com água e sal.',
      'Deixe descansar até absorver a água.',
      'Cozinhe na cuscuzeira no vapor.',
      'Solte com garfo e finalize com manteiga.',
    ],
    rendimentoPorcaoG: 160,
    tempoMin: 25,
    complexidade: 'baixa',
    nutricao: { kcal: 195, prot: 4, carb: 40, gord: 3, fibra: 3, sodio: 290 },
    adequacaoRefeitorio: 89,
  },
  {
    nome: 'Pirão',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['caldo', 'acompanhamento', 'caseiro'],
    ingredientes: [
      { item: 'Farinha de mandioca', unid: 'pct', porPessoa: 0.03 },
      { item: 'Caldo de cozimento', unid: 'ml', porPessoa: 80 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.008 },
      { item: 'Sal', unid: 'g', porPessoa: 2 },
    ],
    preparo: [
      'Aqueça o caldo temperado.',
      'Adicione a farinha aos poucos mexendo sempre.',
      'Cozinhe até obter consistência cremosa.',
      'Ajuste o sal e sirva imediatamente.',
    ],
    rendimentoPorcaoG: 150,
    tempoMin: 20,
    complexidade: 'baixa',
    nutricao: { kcal: 170, prot: 3, carb: 32, gord: 3, fibra: 2, sodio: 360 },
    adequacaoRefeitorio: 85,
  },
  {
    nome: 'Lentilha cozida',
    categoria: 'guarnicao',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['grao', 'nutritivo', 'economico'],
    ingredientes: [
      { item: 'Lentilha', unid: 'kg', porPessoa: 0.05 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.01 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.015 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Refogue alho, cebola e cenoura em cubos.',
      'Adicione a lentilha e água suficiente.',
      'Cozinhe até a lentilha ficar macia.',
      'Ajuste o sal mantendo um caldo encorpado.',
    ],
    rendimentoPorcaoG: 170,
    tempoMin: 45,
    complexidade: 'media',
    nutricao: { kcal: 195, prot: 12, carb: 32, gord: 2, fibra: 8, sodio: 300 },
    substituicoes: ['Grão-de-bico refogado como alternativa'],
    adequacaoRefeitorio: 89,
  },
  {
    nome: 'Grão-de-bico refogado',
    categoria: 'guarnicao',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['grao', 'nutritivo', 'refogado'],
    ingredientes: [
      { item: 'Feijão fradinho', unid: 'kg', porPessoa: 0.05 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.01 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Cozinhe o grão-de-bico na pressão até amaciar.',
      'Refogue alho e cebola no óleo.',
      'Adicione o grão-de-bico escorrido e salteie.',
      'Tempere com sal e ervas a gosto.',
    ],
    rendimentoPorcaoG: 165,
    tempoMin: 50,
    complexidade: 'media',
    nutricao: { kcal: 230, prot: 11, carb: 34, gord: 6, fibra: 7, sodio: 310 },
    adequacaoRefeitorio: 87,
  },
  {
    nome: 'Batata doce assada',
    categoria: 'guarnicao',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['assado', 'raiz', 'saudavel'],
    ingredientes: [
      { item: 'Batata doce', unid: 'kg', porPessoa: 0.16 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Corte a batata doce em gomos.',
      'Tempere com óleo e sal.',
      'Disponha em assadeira em camada única.',
      'Asse a 200°C até ficar macia e levemente dourada.',
    ],
    rendimentoPorcaoG: 170,
    tempoMin: 45,
    complexidade: 'baixa',
    nutricao: { kcal: 200, prot: 3, carb: 42, gord: 3, fibra: 5, sodio: 250 },
    adequacaoRefeitorio: 90,
  },
  {
    nome: 'Quibebe de abóbora',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['cremoso', 'raiz', 'caseiro'],
    ingredientes: [
      { item: 'Abóbora', unid: 'kg', porPessoa: 0.16 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.01 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Óleo', unid: 'ml', porPessoa: 5 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Refogue alho e cebola no óleo.',
      'Adicione a abóbora em cubos e um pouco de água.',
      'Cozinhe até desmanchar formando um creme.',
      'Ajuste o sal e finalize com cheiro-verde.',
    ],
    rendimentoPorcaoG: 175,
    tempoMin: 35,
    complexidade: 'baixa',
    nutricao: { kcal: 150, prot: 3, carb: 24, gord: 5, fibra: 4, sodio: 270 },
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Arroz integral',
    categoria: 'guarnicao',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['base', 'integral', 'saudavel'],
    ingredientes: [
      { item: 'Arroz', unid: 'kg', porPessoa: 0.09 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Óleo', unid: 'ml', porPessoa: 5 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Deixe o arroz integral de molho previamente.',
      'Refogue o alho no óleo e adicione o arroz.',
      'Acrescente água quente em proporção maior que o branco.',
      'Cozinhe em fogo baixo até ficar macio.',
    ],
    rendimentoPorcaoG: 160,
    tempoMin: 50,
    complexidade: 'media',
    obsOperacional: 'Demora mais para cozinhar; programar com antecedência.',
    nutricao: { kcal: 195, prot: 5, carb: 40, gord: 3, fibra: 4, sodio: 300 },
    adequacaoRefeitorio: 86,
  },
  {
    nome: 'Brócolis refogado',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['verde', 'refogado', 'saudavel'],
    ingredientes: [
      { item: 'Brócolis', unid: 'kg', porPessoa: 0.1 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
      { item: 'Sal', unid: 'g', porPessoa: 2 },
    ],
    preparo: [
      'Separe os buquês de brócolis e lave bem.',
      'Branqueie por 2 minutos em água fervente com sal.',
      'Refresque em água gelada para manter a cor.',
      'Refogue no alho dourado no óleo e ajuste o sal.',
    ],
    rendimentoPorcaoG: 110,
    tempoMin: 20,
    complexidade: 'baixa',
    obsOperacional: 'Branquear em lotes para não escurecer; terminar no refogo.',
    nutricao: { kcal: 90, prot: 4, carb: 8, gord: 5, fibra: 4, sodio: 200 },
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Abobrinha refogada',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['verde', 'refogado', 'leve'],
    ingredientes: [
      { item: 'Abobrinha', unid: 'kg', porPessoa: 0.12 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.01 },
      { item: 'Óleo', unid: 'ml', porPessoa: 5 },
      { item: 'Sal', unid: 'g', porPessoa: 2 },
    ],
    preparo: [
      'Corte a abobrinha em rodelas ou meias-luas.',
      'Refogue o alho e a cebola no óleo.',
      'Adicione a abobrinha e salteie em fogo alto.',
      'Cozinhe até ficar macia mas ainda firme; ajuste o sal.',
    ],
    rendimentoPorcaoG: 110,
    tempoMin: 15,
    complexidade: 'baixa',
    nutricao: { kcal: 70, prot: 2, carb: 7, gord: 5, fibra: 2, sodio: 200 },
    adequacaoRefeitorio: 87,
  },
  {
    nome: 'Banana frita',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['frito', 'doce', 'acompanhamento'],
    ingredientes: [
      { item: 'Banana', unid: 'kg', porPessoa: 0.1 },
      { item: 'Óleo', unid: 'ml', porPessoa: 10 },
    ],
    preparo: [
      'Corte a banana madura em fatias ou ao meio no sentido do comprimento.',
      'Aqueça o óleo em frigideira larga.',
      'Frite as fatias dos dois lados até dourar.',
      'Escorra em papel absorvente e sirva quente.',
    ],
    rendimentoPorcaoG: 90,
    tempoMin: 15,
    complexidade: 'baixa',
    obsOperacional: 'Usar banana bem madura; a banana da terra precisa de mais tempo.',
    nutricao: { kcal: 140, prot: 1, carb: 22, gord: 6, fibra: 2, sodio: 30 },
    adequacaoRefeitorio: 85,
  },
  {
    nome: 'Berinjela empanada',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['empanado', 'frito', 'classico'],
    ingredientes: [
      { item: 'Berinjela', unid: 'kg', porPessoa: 0.12 },
      { item: 'Farinha de trigo', unid: 'kg', porPessoa: 0.02 },
      { item: 'Ovo', unid: 'un', porPessoa: 0.3 },
      { item: 'Farinha de rosca', unid: 'kg', porPessoa: 0.015 },
      { item: 'Óleo', unid: 'ml', porPessoa: 15 },
      { item: 'Sal', unid: 'g', porPessoa: 2 },
    ],
    preparo: [
      'Fatie a berinjela, salgue e deixe descansar 15 minutos.',
      'Seque as fatias e passe na farinha, ovo batido e farinha de rosca.',
      'Frite em óleo a 180°C até dourar dos dois lados.',
      'Escorra em papel absorvente e sirva quente.',
    ],
    rendimentoPorcaoG: 120,
    tempoMin: 35,
    complexidade: 'media',
    obsOperacional: 'Salgar e secar bem a berinjela evita que fique gordurosa.',
    nutricao: { kcal: 200, prot: 5, carb: 22, gord: 11, fibra: 4, sodio: 320 },
    substituicoes: ['Assar no forno a 220°C para versão menos gordurosa'],
    adequacaoRefeitorio: 83,
  },
  {
    nome: 'Bolinho de arroz',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['frito', 'caseiro', 'aproveitamento'],
    ingredientes: [
      { item: 'Arroz', unid: 'kg', porPessoa: 0.08 },
      { item: 'Farinha de trigo', unid: 'kg', porPessoa: 0.015 },
      { item: 'Ovo', unid: 'un', porPessoa: 0.3 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.008 },
      { item: 'Óleo', unid: 'ml', porPessoa: 12 },
      { item: 'Sal', unid: 'g', porPessoa: 2 },
    ],
    preparo: [
      'Misture o arroz cozido (frio) com ovo, farinha e cebola picada.',
      'Tempere com sal e molde bolinhos.',
      'Frite em óleo quente a 180°C até dourar.',
      'Escorra e sirva imediatamente.',
    ],
    rendimentoPorcaoG: 120,
    tempoMin: 30,
    complexidade: 'baixa',
    obsOperacional: 'Ótimo para aproveitar sobras de arroz do dia anterior.',
    nutricao: { kcal: 230, prot: 5, carb: 32, gord: 10, fibra: 2, sodio: 280 },
    adequacaoRefeitorio: 82,
  },
  {
    nome: 'Caldinho de feijão',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['caldo', 'classico', 'conforto'],
    ingredientes: [
      { item: 'Feijão Carioca', unid: 'kg', porPessoa: 0.04 },
      { item: 'Bacon', unid: 'kg', porPessoa: 0.01, opcional: true },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.008 },
      { item: 'Óleo', unid: 'ml', porPessoa: 4 },
      { item: 'Sal', unid: 'g', porPessoa: 2 },
    ],
    preparo: [
      'Cozinhe o feijão na pressão até ficar muito macio.',
      'Bata no liquidificador até virar um caldo homogêneo.',
      'Refogue alho, cebola e bacon no óleo.',
      'Junte o caldo de feijão, cozinhe e ajuste o sal.',
    ],
    rendimentoPorcaoG: 160,
    tempoMin: 45,
    complexidade: 'baixa',
    obsOperacional: 'Caldo mais liso com peneira; servir quente em rechaud.',
    nutricao: { kcal: 160, prot: 9, carb: 24, gord: 4, fibra: 6, sodio: 300 },
    adequacaoRefeitorio: 86,
  },
  {
    nome: 'Couve refogada',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['verde', 'refogado', 'mineiro'],
    ingredientes: [
      { item: 'Couve', unid: 'mç', porPessoa: 0.15 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Óleo', unid: 'ml', porPessoa: 5 },
      { item: 'Sal', unid: 'g', porPessoa: 2 },
    ],
    preparo: [
      'Retire os talos e role as folhas de couve para fatiar bem fino.',
      'Doure o alho no óleo sem queimar.',
      'Adicione a couve fatiada em fogo alto.',
      'Refogue rapidamente mexendo sempre até murchar e ajuste o sal.',
    ],
    rendimentoPorcaoG: 80,
    tempoMin: 15,
    complexidade: 'baixa',
    obsOperacional: 'Fatiar bem fino e refogar rápido: couve não deve perder a cor.',
    nutricao: { kcal: 70, prot: 3, carb: 5, gord: 5, fibra: 3, sodio: 200 },
    adequacaoRefeitorio: 90,
  },
  {
    nome: 'Creme de batata',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['cremoso', 'sopa', 'conforto'],
    ingredientes: [
      { item: 'Batata', unid: 'kg', porPessoa: 0.14 },
      { item: 'Creme de Leite', unid: 'g', porPessoa: 15 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.01 },
      { item: 'Óleo', unid: 'ml', porPessoa: 5 },
      { item: 'Sal', unid: 'g', porPessoa: 2 },
    ],
    preparo: [
      'Cozinhe as batatas com cebola até ficarem bem macias.',
      'Bata no liquidificador com um pouco da água do cozimento.',
      'Leve ao fogo, adicione o creme de leite e ajuste a consistência.',
      'Tempere com sal e sirva quente.',
    ],
    rendimentoPorcaoG: 170,
    tempoMin: 30,
    complexidade: 'baixa',
    nutricao: { kcal: 190, prot: 4, carb: 32, gord: 7, fibra: 3, sodio: 270 },
    substituicoes: ['Purê de batata para versão mais espessa'],
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Feijão com abóbora',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['cozido', 'nordestino', 'caseiro'],
    ingredientes: [
      { item: 'Feijão Carioca', unid: 'kg', porPessoa: 0.04 },
      { item: 'Abóbora', unid: 'kg', porPessoa: 0.08 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.01 },
      { item: 'Óleo', unid: 'ml', porPessoa: 5 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Cozinhe o feijão na pressão até ficar macio.',
      'Refogue alho e cebola no óleo.',
      'Adicione a abóbora em cubos e o feijão.',
      'Cozinhe até a abóbora desmanchar e o caldo engrossar; ajuste o sal.',
    ],
    rendimentoPorcaoG: 180,
    tempoMin: 50,
    complexidade: 'media',
    nutricao: { kcal: 180, prot: 8, carb: 32, gord: 4, fibra: 7, sodio: 290 },
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Legumes cozidos',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['cozido', 'saudavel', 'leve'],
    ingredientes: [
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.07 },
      { item: 'Abóbora', unid: 'kg', porPessoa: 0.07 },
      { item: 'Manteiga', unid: 'g', porPessoa: 5, opcional: true },
      { item: 'Sal', unid: 'g', porPessoa: 2 },
    ],
    preparo: [
      'Corte a cenoura e a abóbora em cubos uniformes.',
      'Cozinhe em água com sal até ficarem macios mas não desmanchando.',
      'Escorra e finalize com manteiga se desejar.',
      'Ajuste o sal e sirva.',
    ],
    rendimentoPorcaoG: 130,
    tempoMin: 20,
    complexidade: 'baixa',
    nutricao: { kcal: 90, prot: 2, carb: 16, gord: 3, fibra: 4, sodio: 200 },
    substituicoes: ['Abobrinha e batata doce conforme disponibilidade'],
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Batata e cenoura cozidas',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['cozido', 'simples', 'economico'],
    ingredientes: [
      { item: 'Batata', unid: 'kg', porPessoa: 0.08 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.06 },
      { item: 'Manteiga', unid: 'g', porPessoa: 5, opcional: true },
      { item: 'Sal', unid: 'g', porPessoa: 2 },
    ],
    preparo: [
      'Corte batata e cenoura em cubos do mesmo tamanho.',
      'Cozinhe em água fervente com sal até ficarem macios.',
      'Escorra e finalize com manteiga derretida.',
      'Ajuste o sal e sirva quente.',
    ],
    rendimentoPorcaoG: 130,
    tempoMin: 25,
    complexidade: 'baixa',
    nutricao: { kcal: 120, prot: 3, carb: 24, gord: 3, fibra: 3, sodio: 220 },
    adequacaoRefeitorio: 87,
  },
  {
    nome: 'Batata palha',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['frito', 'crocante', 'acompanhamento'],
    ingredientes: [
      { item: 'Batata', unid: 'kg', porPessoa: 0.06 },
      { item: 'Óleo', unid: 'ml', porPessoa: 10 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Ralar a batata bem fina (modo palha) ou usar processador.',
      'Secar bem em pano limpo ou papel absorvente.',
      'Fritar em óleo quente a 180°C mexendo para soltar.',
      'Escorrer, salgar levemente e usar como finalização.',
    ],
    rendimentoPorcaoG: 60,
    tempoMin: 20,
    complexidade: 'baixa',
    obsOperacional: 'Em volume, preferir batata palha industrializada por praticidade.',
    nutricao: { kcal: 210, prot: 3, carb: 26, gord: 11, fibra: 2, sodio: 180 },
    adequacaoRefeitorio: 80,
  },
  {
    nome: 'Purê de mandioca',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['cremoso', 'raiz', 'conforto'],
    ingredientes: [
      { item: 'Mandioca', unid: 'kg', porPessoa: 0.18 },
      { item: 'Leite', unid: 'ml', porPessoa: 40 },
      { item: 'Manteiga', unid: 'g', porPessoa: 8 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Cozinhe a mandioca na pressão até ficar bem macia.',
      'Retire os fiapos e amasse ainda quente.',
      'Incorpore o leite morno e a manteiga.',
      'Bata até obter textura lisa e cremosa; ajuste o sal.',
    ],
    rendimentoPorcaoG: 180,
    tempoMin: 40,
    complexidade: 'baixa',
    obsOperacional: 'Mandioca congelada acelera o processo sem perder qualidade.',
    nutricao: { kcal: 250, prot: 3, carb: 46, gord: 7, fibra: 4, sodio: 300 },
    adequacaoRefeitorio: 90,
  },
  {
    nome: 'Purê de batata doce',
    categoria: 'guarnicao',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['cremoso', 'raiz', 'saudavel'],
    ingredientes: [
      { item: 'Batata doce', unid: 'kg', porPessoa: 0.18 },
      { item: 'Leite', unid: 'ml', porPessoa: 35 },
      { item: 'Manteiga', unid: 'g', porPessoa: 6 },
      { item: 'Sal', unid: 'g', porPessoa: 2 },
    ],
    preparo: [
      'Cozinhe a batata doce até ficar macia.',
      'Amasse ainda quente.',
      'Acrescente leite e manteiga mexendo até ficar cremoso.',
      'Ajuste o sal e sirva quente.',
    ],
    rendimentoPorcaoG: 175,
    tempoMin: 35,
    complexidade: 'baixa',
    nutricao: { kcal: 225, prot: 3, carb: 44, gord: 5, fibra: 5, sodio: 240 },
    adequacaoRefeitorio: 89,
  },
  {
    nome: 'Purê de abóbora',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['cremoso', 'raiz', 'colorido'],
    ingredientes: [
      { item: 'Abóbora', unid: 'kg', porPessoa: 0.18 },
      { item: 'Leite', unid: 'ml', porPessoa: 30 },
      { item: 'Manteiga', unid: 'g', porPessoa: 6 },
      { item: 'Sal', unid: 'g', porPessoa: 2 },
    ],
    preparo: [
      'Cozinhe a abóbora em cubos até ficar bem macia.',
      'Escorra bem a água e amasse.',
      'Adicione manteiga e leite até a consistência cremosa.',
      'Ajuste o sal e sirva.',
    ],
    rendimentoPorcaoG: 170,
    tempoMin: 30,
    complexidade: 'baixa',
    nutricao: { kcal: 140, prot: 3, carb: 26, gord: 5, fibra: 4, sodio: 230 },
    substituicoes: ['Purê de moranga pela mesma receita'],
    adequacaoRefeitorio: 90,
  },
  {
    nome: 'Repolho refogado',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['refogado', 'economico', 'simples'],
    ingredientes: [
      { item: 'Repolho', unid: 'kg', porPessoa: 0.1 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.01 },
      { item: 'Óleo', unid: 'ml', porPessoa: 5 },
      { item: 'Sal', unid: 'g', porPessoa: 2 },
    ],
    preparo: [
      'Retire o miolo e fatie o repolho bem fino.',
      'Refogue alho e cebola no óleo.',
      'Adicione o repolho em fogo alto mexendo sempre.',
      'Cozinhe até murchar mas ainda ter textura; ajuste o sal.',
    ],
    rendimentoPorcaoG: 90,
    tempoMin: 15,
    complexidade: 'baixa',
    nutricao: { kcal: 75, prot: 2, carb: 8, gord: 5, fibra: 3, sodio: 200 },
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Sopa de legumes',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['sopa', 'caseiro', 'conforto'],
    ingredientes: [
      { item: 'Batata', unid: 'kg', porPessoa: 0.07 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.06 },
      { item: 'Abobrinha', unid: 'kg', porPessoa: 0.04 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.01 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Óleo', unid: 'ml', porPessoa: 4 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Refogue alho e cebola no óleo.',
      'Adicione os legumes em cubos e água quente.',
      'Cozinhe até os legumes ficarem macios.',
      'Ajuste o sal e finalize com cheiro-verde.',
    ],
    rendimentoPorcaoG: 200,
    tempoMin: 30,
    complexidade: 'baixa',
    obsOperacional: 'Variar os legumes conforme disponibilidade e preço do dia.',
    nutricao: { kcal: 100, prot: 3, carb: 18, gord: 4, fibra: 4, sodio: 280 },
    adequacaoRefeitorio: 87,
  },
  {
    nome: 'Cenoura com beterraba cozida',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['cozido', 'colorido', 'saudavel'],
    ingredientes: [
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.06 },
      { item: 'Beterraba', unid: 'kg', porPessoa: 0.05 },
      { item: 'Manteiga', unid: 'g', porPessoa: 4, opcional: true },
      { item: 'Sal', unid: 'g', porPessoa: 2 },
    ],
    preparo: [
      'Cozinhe a beterraba em água até ficar macia; descasque e corte.',
      'Cozinhe a cenoura em rodelas ou cubos até ficar al dente.',
      'Combine as duas e finalize com manteiga.',
      'Ajuste o sal e sirva.',
    ],
    rendimentoPorcaoG: 100,
    tempoMin: 35,
    complexidade: 'baixa',
    obsOperacional: 'Cozinhar beterraba separado para não tingir a cenoura.',
    nutricao: { kcal: 80, prot: 2, carb: 14, gord: 3, fibra: 4, sodio: 200 },
    adequacaoRefeitorio: 87,
  },
];
