import type { Receita } from './tipos';

/* =====================================================================
   Molhos quentes/frios e pratos vegetarianos (proteína vegetal) do
   Tatá House. Os molhos entram como guarnição/acompanhamento; os pratos
   vegetarianos são opção principal inclusiva (sem proteína animal).
   ===================================================================== */

export const PRATOS: Receita[] = [
  /* ============================ MOLHOS ============================ */
  {
    nome: 'Molho sugo',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['molho', 'italiano'],
    ingredientes: [
      { item: 'Molho de tomate', unid: 'lt', porPessoa: 0.05 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.015 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Manjericão', unid: 'mç', porPessoa: 0.02, opcional: true },
      { item: 'Óleo', unid: 'ml', porPessoa: 4 },
      { item: 'Sal', unid: 'g', porPessoa: 2 },
    ],
    preparo: [
      'Refogue a cebola picada e o alho no óleo até dourar levemente.',
      'Acrescente o molho de tomate e tempere com sal.',
      'Cozinhe em fogo baixo por cerca de 20 minutos, mexendo de vez em quando.',
      'Finalize com manjericão fresco rasgado antes de servir.',
    ],
    rendimentoPorcaoG: 90,
    tempoMin: 30,
    complexidade: 'baixa',
    obsOperacional: 'Base coringa: rende para massas, polentas e gratinados do dia.',
    nutricao: { kcal: 80, prot: 2, carb: 12, gord: 3, fibra: 2, sodio: 380 },
    substituicoes: ['Tomate fresco maduro no lugar do molho pronto'],
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Molho à bolonhesa de lentilha',
    categoria: 'guarnicao',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['molho', 'vegetariano', 'italiano'],
    ingredientes: [
      { item: 'Molho de tomate', unid: 'lt', porPessoa: 0.04 },
      { item: 'Lentilha', unid: 'kg', porPessoa: 0.025 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.02 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.015 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Óleo', unid: 'ml', porPessoa: 5 },
      { item: 'Sal', unid: 'g', porPessoa: 2 },
    ],
    preparo: [
      'Cozinhe a lentilha em água até ficar macia e escorra.',
      'Refogue cebola, alho e cenoura ralada no óleo.',
      'Junte o molho de tomate e a lentilha cozida, tempere com sal.',
      'Apure em fogo baixo por 15 minutos até encorpar.',
    ],
    rendimentoPorcaoG: 110,
    tempoMin: 45,
    complexidade: 'media',
    obsOperacional: 'A lentilha substitui a carne moída e dá corpo ao molho.',
    nutricao: { kcal: 150, prot: 9, carb: 18, gord: 4, fibra: 4, sodio: 420 },
    substituicoes: ['Grão-de-bico triturado no lugar da lentilha'],
    adequacaoRefeitorio: 84,
  },
  {
    nome: 'Molho branco (bechamel)',
    categoria: 'guarnicao',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['molho', 'cremoso'],
    ingredientes: [
      { item: 'Leite', unid: 'lt', porPessoa: 0.06 },
      { item: 'Farinha de trigo', unid: 'kg', porPessoa: 0.008 },
      { item: 'Creme de Leite', unid: 'lt', porPessoa: 0.02 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.005 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
      { item: 'Sal', unid: 'g', porPessoa: 2 },
    ],
    preparo: [
      'Aqueça o óleo e doure rapidamente a farinha para formar o roux.',
      'Adicione o leite aos poucos, mexendo sempre para não empelotar.',
      'Cozinhe até engrossar e tempere com sal e pitada de noz-moscada.',
      'Finalize com o creme de leite fora do fogo.',
    ],
    rendimentoPorcaoG: 100,
    tempoMin: 25,
    complexidade: 'media',
    obsOperacional: 'Base para gratinados; manter aquecido em banho-maria.',
    nutricao: { kcal: 160, prot: 5, carb: 12, gord: 10, fibra: 1, sodio: 360 },
    substituicoes: ['Leite vegetal para versão sem lactose'],
    adequacaoRefeitorio: 82,
  },
  {
    nome: 'Molho madeira',
    categoria: 'guarnicao',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['molho', 'clássico'],
    ingredientes: [
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Farinha de trigo', unid: 'kg', porPessoa: 0.005 },
      { item: 'Molho de tomate', unid: 'lt', porPessoa: 0.02 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
      { item: 'Sal', unid: 'g', porPessoa: 2 },
    ],
    preparo: [
      'Refogue a cebola até caramelizar bem no óleo.',
      'Polvilhe a farinha e doure para dar cor escura.',
      'Adicione caldo de legumes e o molho de tomate, mexendo.',
      'Cozinhe em fogo baixo até reduzir e ganhar brilho; ajuste o sal.',
    ],
    rendimentoPorcaoG: 80,
    tempoMin: 35,
    complexidade: 'media',
    obsOperacional: 'Combina com bifes e medalhões; coar para textura lisa.',
    nutricao: { kcal: 90, prot: 2, carb: 11, gord: 4, fibra: 1, sodio: 450 },
    substituicoes: ['Cogumelos fatiados para versão mais encorpada'],
    adequacaoRefeitorio: 80,
  },
  {
    nome: 'Molho rosé',
    categoria: 'guarnicao',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['molho', 'cremoso'],
    ingredientes: [
      { item: 'Molho de tomate', unid: 'lt', porPessoa: 0.04 },
      { item: 'Creme de Leite', unid: 'lt', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.01 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.002 },
      { item: 'Óleo', unid: 'ml', porPessoa: 4 },
      { item: 'Sal', unid: 'g', porPessoa: 2 },
    ],
    preparo: [
      'Refogue cebola e alho no óleo até ficarem translúcidos.',
      'Acrescente o molho de tomate e cozinhe por 10 minutos.',
      'Abaixe o fogo e incorpore o creme de leite até atingir cor rosada.',
      'Ajuste o sal e sirva ainda quente.',
    ],
    rendimentoPorcaoG: 90,
    tempoMin: 25,
    complexidade: 'baixa',
    obsOperacional: 'Não ferver após o creme para evitar talhar.',
    nutricao: { kcal: 170, prot: 3, carb: 12, gord: 12, fibra: 2, sodio: 400 },
    substituicoes: ['Creme vegetal para reduzir gordura láctea'],
    adequacaoRefeitorio: 82,
  },
  {
    nome: 'Molho de queijo',
    categoria: 'guarnicao',
    classe: 'premium',
    proteina: 'outros',
    tags: ['molho', 'cremoso', 'gratinado'],
    ingredientes: [
      { item: 'Leite', unid: 'lt', porPessoa: 0.05 },
      { item: 'Mussarela', unid: 'kg', porPessoa: 0.018 },
      { item: 'Farinha de trigo', unid: 'kg', porPessoa: 0.006 },
      { item: 'Creme de Leite', unid: 'lt', porPessoa: 0.02 },
      { item: 'Óleo', unid: 'ml', porPessoa: 5 },
      { item: 'Sal', unid: 'g', porPessoa: 2 },
    ],
    preparo: [
      'Prepare um roux claro com óleo e farinha.',
      'Adicione o leite aos poucos, mexendo até engrossar.',
      'Incorpore a mussarela ralada em fogo baixo até derreter.',
      'Finalize com o creme de leite e ajuste o sal.',
    ],
    rendimentoPorcaoG: 100,
    tempoMin: 30,
    complexidade: 'media',
    obsOperacional: 'Ótimo para gratinar legumes e massas; servir bem quente.',
    nutricao: { kcal: 210, prot: 9, carb: 10, gord: 15, fibra: 1, sodio: 520 },
    substituicoes: ['Queijo prato no lugar da mussarela'],
    adequacaoRefeitorio: 78,
  },
  {
    nome: 'Molho barbecue caseiro',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['molho', 'agridoce', 'defumado'],
    ingredientes: [
      { item: 'Molho de tomate', unid: 'lt', porPessoa: 0.04 },
      { item: 'Barbecue', unid: 'ml', porPessoa: 8 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.01 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.002 },
      { item: 'Mostarda', unid: 'ml', porPessoa: 4 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Refogue cebola e alho até dourar.',
      'Junte o molho de tomate, a base barbecue e a mostarda.',
      'Acrescente um toque de açúcar mascavo para realçar o doce.',
      'Cozinhe em fogo baixo até apurar e ficar brilhante.',
    ],
    rendimentoPorcaoG: 80,
    tempoMin: 25,
    complexidade: 'baixa',
    obsOperacional: 'Acompanha hambúrgueres e legumes grelhados.',
    nutricao: { kcal: 110, prot: 2, carb: 16, gord: 3, fibra: 1, sodio: 600 },
    substituicoes: ['Páprica defumada para reforçar o sabor smoke'],
    adequacaoRefeitorio: 80,
  },
  {
    nome: 'Molho de tomate fresco',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['molho', 'natural', 'leve'],
    ingredientes: [
      { item: 'Tomate', unid: 'kg', porPessoa: 0.12 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.015 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Manjericão', unid: 'mç', porPessoa: 0.02 },
      { item: 'Óleo', unid: 'ml', porPessoa: 5 },
      { item: 'Sal', unid: 'g', porPessoa: 2 },
    ],
    preparo: [
      'Escalde os tomates, retire a pele e pique grosseiramente.',
      'Refogue cebola e alho no óleo até perfumar.',
      'Junte o tomate e cozinhe até desmanchar, formando molho.',
      'Tempere com sal e finalize com manjericão fresco.',
    ],
    rendimentoPorcaoG: 100,
    tempoMin: 35,
    complexidade: 'media',
    obsOperacional: 'Ideal na safra do tomate; menos sódio que molho pronto.',
    nutricao: { kcal: 70, prot: 2, carb: 9, gord: 3, fibra: 2, sodio: 280 },
    substituicoes: ['Molho de tomate pronto fora de safra'],
    adequacaoRefeitorio: 86,
  },
  {
    nome: 'Molho ferrugem',
    categoria: 'guarnicao',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['molho', 'churrasco', 'picante'],
    ingredientes: [
      { item: 'Tomate', unid: 'kg', porPessoa: 0.05 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Pimentão', unid: 'kg', porPessoa: 0.02 },
      { item: 'Mostarda', unid: 'ml', porPessoa: 5 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
      { item: 'Sal', unid: 'g', porPessoa: 2 },
    ],
    preparo: [
      'Pique tomate, cebola e pimentão em cubos bem pequenos.',
      'Misture com mostarda, óleo e tempere com sal.',
      'Acrescente pimenta a gosto e um pouco de vinagre.',
      'Deixe descansar 15 minutos para apurar os sabores.',
    ],
    rendimentoPorcaoG: 80,
    tempoMin: 20,
    complexidade: 'baixa',
    obsOperacional: 'Servir frio; clássico de churrasco para acompanhar carnes.',
    nutricao: { kcal: 90, prot: 2, carb: 8, gord: 6, fibra: 2, sodio: 380 },
    substituicoes: ['Pimenta dedo-de-moça para mais ardência'],
    adequacaoRefeitorio: 76,
  },
  {
    nome: 'Molho de ervas',
    categoria: 'guarnicao',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['molho', 'frio', 'leve'],
    ingredientes: [
      { item: 'Creme de Leite', unid: 'lt', porPessoa: 0.03 },
      { item: 'Manjericão', unid: 'mç', porPessoa: 0.03 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.002 },
      { item: 'Óleo', unid: 'ml', porPessoa: 4 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Pique finamente as ervas frescas e o alho.',
      'Misture ao creme de leite com o óleo.',
      'Tempere com sal e gotas de limão.',
      'Reserve resfriado até o momento de servir.',
    ],
    rendimentoPorcaoG: 70,
    tempoMin: 15,
    complexidade: 'baixa',
    obsOperacional: 'Molho frio versátil para saladas, batatas e grelhados.',
    nutricao: { kcal: 120, prot: 2, carb: 6, gord: 10, fibra: 1, sodio: 220 },
    substituicoes: ['Iogurte natural no lugar de parte do creme'],
    adequacaoRefeitorio: 80,
  },
  {
    nome: 'Molho de mostarda e mel',
    categoria: 'guarnicao',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['molho', 'agridoce', 'frio'],
    ingredientes: [
      { item: 'Mostarda', unid: 'ml', porPessoa: 10 },
      { item: 'Creme de Leite', unid: 'lt', porPessoa: 0.02 },
      { item: 'Óleo', unid: 'ml', porPessoa: 4 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Misture a mostarda com mel até homogeneizar.',
      'Incorpore o creme de leite para suavizar.',
      'Adicione o óleo em fio, batendo para emulsionar.',
      'Ajuste sal e acidez com gotas de limão.',
    ],
    rendimentoPorcaoG: 60,
    tempoMin: 15,
    complexidade: 'baixa',
    obsOperacional: 'Dressing agridoce para saladas e proteínas grelhadas.',
    nutricao: { kcal: 130, prot: 2, carb: 12, gord: 9, fibra: 1, sodio: 500 },
    substituicoes: ['Iogurte no lugar do creme para versão mais leve'],
    adequacaoRefeitorio: 82,
  },
  {
    nome: 'Molho agridoce',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['molho', 'agridoce', 'oriental'],
    ingredientes: [
      { item: 'Molho de tomate', unid: 'lt', porPessoa: 0.03 },
      { item: 'Pimentão', unid: 'kg', porPessoa: 0.02 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.01 },
      { item: 'Farinha de trigo', unid: 'kg', porPessoa: 0.003 },
      { item: 'Óleo', unid: 'ml', porPessoa: 4 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Refogue pimentão e cebola em cubos no óleo.',
      'Junte o molho de tomate, açúcar e vinagre.',
      'Dissolva a farinha em água e adicione para encorpar.',
      'Cozinhe até engrossar e equilibrar o doce com o ácido.',
    ],
    rendimentoPorcaoG: 90,
    tempoMin: 25,
    complexidade: 'baixa',
    obsOperacional: 'Acompanha frituras e bolinhos; balancear vinagre e açúcar.',
    nutricao: { kcal: 100, prot: 2, carb: 16, gord: 4, fibra: 2, sodio: 350 },
    substituicoes: ['Abacaxi em cubos para toque tropical'],
    adequacaoRefeitorio: 78,
  },
  {
    nome: 'Vinagrete para churrasco',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['molho', 'frio', 'churrasco'],
    ingredientes: [
      { item: 'Tomate', unid: 'kg', porPessoa: 0.06 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.025 },
      { item: 'Pimentão', unid: 'kg', porPessoa: 0.02 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
      { item: 'Sal', unid: 'g', porPessoa: 2 },
    ],
    preparo: [
      'Pique tomate, cebola e pimentão em cubos uniformes.',
      'Tempere com vinagre, óleo e sal.',
      'Misture bem e prove o equilíbrio de acidez.',
      'Leve à geladeira por 20 minutos antes de servir.',
    ],
    rendimentoPorcaoG: 90,
    tempoMin: 20,
    complexidade: 'baixa',
    obsOperacional: 'Cortar tudo no mesmo tamanho garante visual e textura.',
    nutricao: { kcal: 80, prot: 2, carb: 7, gord: 6, fibra: 2, sodio: 320 },
    substituicoes: ['Salsa picada para mais frescor'],
    adequacaoRefeitorio: 84,
  },

  /* ===================== PRATOS VEGETARIANOS ===================== */
  {
    nome: 'Escondidinho de proteína de soja',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'outros',
    tags: ['vegetariano', 'prato-unico', 'comfort'],
    ingredientes: [
      { item: 'Mandioca', unid: 'kg', porPessoa: 0.18 },
      { item: 'Proteína de soja', unid: 'kg', porPessoa: 0.05 },
      { item: 'Molho de tomate', unid: 'lt', porPessoa: 0.04 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Mussarela', unid: 'kg', porPessoa: 0.02 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Cozinhe e amasse a mandioca formando um purê encorpado.',
      'Hidrate a proteína de soja e refogue com cebola, alho e molho de tomate.',
      'Monte em assadeira: recheio embaixo, purê por cima.',
      'Cubra com mussarela e leve ao forno para gratinar.',
    ],
    rendimentoPorcaoG: 340,
    tempoMin: 55,
    complexidade: 'media',
    obsOperacional: 'Montar em GNs e gratinar em lotes; render bem em escala.',
    nutricao: { kcal: 380, prot: 18, carb: 45, gord: 12, fibra: 6, sodio: 560 },
    substituicoes: ['Purê de batata no lugar da mandioca'],
    adequacaoRefeitorio: 86,
  },
  {
    nome: 'Estrogonofe de cogumelos',
    categoria: 'principal',
    classe: 'premium',
    proteina: 'outros',
    tags: ['vegetariano', 'cremoso'],
    ingredientes: [
      { item: 'Cogumelo', unid: 'kg', porPessoa: 0.1 },
      { item: 'Creme de Leite', unid: 'lt', porPessoa: 0.04 },
      { item: 'Molho de tomate', unid: 'lt', porPessoa: 0.02 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Mostarda', unid: 'ml', porPessoa: 5 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Fatie os cogumelos e refogue com cebola até dourar.',
      'Adicione molho de tomate e mostarda, temperando com sal.',
      'Abaixe o fogo e incorpore o creme de leite.',
      'Aqueça sem ferver e sirva com arroz e batata palha.',
    ],
    rendimentoPorcaoG: 280,
    tempoMin: 35,
    complexidade: 'media',
    obsOperacional: 'Misturar variedades de cogumelo enriquece sabor e textura.',
    nutricao: { kcal: 260, prot: 10, carb: 20, gord: 16, fibra: 5, sodio: 480 },
    substituicoes: ['Palmito em rodelas no lugar de parte dos cogumelos'],
    adequacaoRefeitorio: 80,
  },
  {
    nome: 'Feijoada vegetariana',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'outros',
    tags: ['vegetariano', 'regional', 'prato-unico'],
    ingredientes: [
      { item: 'Feijão preto', unid: 'kg', porPessoa: 0.06 },
      { item: 'Abóbora', unid: 'kg', porPessoa: 0.08 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.05 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Cozinhe o feijão preto até ficar macio.',
      'Refogue cebola e alho, junte abóbora e cenoura em cubos.',
      'Misture os legumes ao feijão e cozinhe até encorpar.',
      'Ajuste o sal e sirva com arroz, couve e laranja.',
    ],
    rendimentoPorcaoG: 350,
    tempoMin: 60,
    complexidade: 'media',
    obsOperacional: 'Deixar o feijão de molho na véspera acelera o cozimento.',
    nutricao: { kcal: 340, prot: 16, carb: 50, gord: 7, fibra: 12, sodio: 520 },
    substituicoes: ['Tofu defumado em cubos para reforçar o sabor'],
    adequacaoRefeitorio: 84,
  },
  {
    nome: 'Grão-de-bico ao curry',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'outros',
    tags: ['vegetariano', 'indiano', 'prato-unico'],
    ingredientes: [
      { item: 'Grão-de-bico', unid: 'kg', porPessoa: 0.06 },
      { item: 'Molho de tomate', unid: 'lt', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Coco ralado', unid: 'kg', porPessoa: 0.01 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Cozinhe o grão-de-bico até ficar macio e escorra.',
      'Refogue cebola e alho com curry no óleo.',
      'Junte molho de tomate, o grão-de-bico e o leite de coco.',
      'Cozinhe por 15 minutos até apurar; ajuste o sal.',
    ],
    rendimentoPorcaoG: 300,
    tempoMin: 45,
    complexidade: 'media',
    obsOperacional: 'Curry em pó padroniza o tempero em grande volume.',
    nutricao: { kcal: 330, prot: 14, carb: 42, gord: 11, fibra: 10, sodio: 460 },
    substituicoes: ['Lentilha no lugar do grão-de-bico'],
    adequacaoRefeitorio: 86,
  },
  {
    nome: 'Lentilha refogada com legumes',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'outros',
    tags: ['vegetariano', 'leve', 'prato-unico'],
    ingredientes: [
      { item: 'Lentilha', unid: 'kg', porPessoa: 0.06 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.05 },
      { item: 'Pimentão', unid: 'kg', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Cozinhe a lentilha al dente e escorra.',
      'Refogue cebola, alho, cenoura e pimentão em cubos.',
      'Misture a lentilha aos legumes e tempere com sal.',
      'Finalize com cheiro-verde picado.',
    ],
    rendimentoPorcaoG: 290,
    tempoMin: 40,
    complexidade: 'baixa',
    obsOperacional: 'A lentilha cozinha rápido sem necessidade de remolho.',
    nutricao: { kcal: 300, prot: 16, carb: 44, gord: 6, fibra: 11, sodio: 420 },
    substituicoes: ['Ervilha partida no lugar da lentilha'],
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Omelete de forno de legumes',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['vegetariano', 'forno', 'rápido'],
    ingredientes: [
      { item: 'Ovo', unid: 'un', porPessoa: 2 },
      { item: 'Pimentão', unid: 'kg', porPessoa: 0.03 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.015 },
      { item: 'Mussarela', unid: 'kg', porPessoa: 0.015 },
      { item: 'Óleo', unid: 'ml', porPessoa: 4 },
      { item: 'Sal', unid: 'g', porPessoa: 2 },
    ],
    preparo: [
      'Bata os ovos e tempere com sal.',
      'Misture os legumes picados e o queijo aos ovos.',
      'Despeje em assadeira untada.',
      'Asse até dourar e firmar; corte em quadrados para servir.',
    ],
    rendimentoPorcaoG: 250,
    tempoMin: 35,
    complexidade: 'baixa',
    obsOperacional: 'Assar em GN facilita o porcionamento em pedaços iguais.',
    nutricao: { kcal: 280, prot: 20, carb: 12, gord: 18, fibra: 4, sodio: 480 },
    substituicoes: ['Abobrinha e brócolis no lugar do pimentão'],
    adequacaoRefeitorio: 84,
  },
  {
    nome: 'Quibe de abóbora assado',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'outros',
    tags: ['vegetariano', 'forno', 'árabe'],
    ingredientes: [
      { item: 'Abóbora', unid: 'kg', porPessoa: 0.12 },
      { item: 'Trigo para quibe', unid: 'kg', porPessoa: 0.04 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Hortelã', unid: 'mç', porPessoa: 0.02 },
      { item: 'Óleo', unid: 'ml', porPessoa: 5 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Cozinhe e amasse a abóbora.',
      'Hidrate o trigo e misture com a abóbora, cebola e hortelã.',
      'Tempere com sal e modele em assadeira untada.',
      'Regue com óleo e asse até firmar e dourar.',
    ],
    rendimentoPorcaoG: 280,
    tempoMin: 50,
    complexidade: 'media',
    obsOperacional: 'Escorrer bem a abóbora evita massa mole.',
    nutricao: { kcal: 290, prot: 9, carb: 48, gord: 7, fibra: 8, sodio: 440 },
    substituicoes: ['Mandioquinha no lugar de parte da abóbora'],
    adequacaoRefeitorio: 82,
  },
  {
    nome: 'Berinjela à parmegiana',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['vegetariano', 'forno', 'italiano'],
    ingredientes: [
      { item: 'Berinjela', unid: 'kg', porPessoa: 0.12 },
      { item: 'Molho de tomate', unid: 'lt', porPessoa: 0.05 },
      { item: 'Mussarela', unid: 'kg', porPessoa: 0.025 },
      { item: 'Farinha de trigo', unid: 'kg', porPessoa: 0.01 },
      { item: 'Óleo', unid: 'ml', porPessoa: 8 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Fatie a berinjela, salgue e deixe perder o amargor.',
      'Passe na farinha e doure no forno ou na chapa.',
      'Monte camadas com molho de tomate e mussarela.',
      'Leve ao forno para gratinar até o queijo derreter.',
    ],
    rendimentoPorcaoG: 320,
    tempoMin: 55,
    complexidade: 'media',
    obsOperacional: 'Assar as fatias em vez de fritar reduz óleo e trabalho.',
    nutricao: { kcal: 320, prot: 14, carb: 28, gord: 17, fibra: 7, sodio: 580 },
    substituicoes: ['Abobrinha no lugar da berinjela'],
    adequacaoRefeitorio: 82,
  },
  {
    nome: 'Strogonoff de palmito',
    categoria: 'principal',
    classe: 'premium',
    proteina: 'outros',
    tags: ['vegetariano', 'cremoso'],
    ingredientes: [
      { item: 'Palmito', unid: 'kg', porPessoa: 0.09 },
      { item: 'Creme de Leite', unid: 'lt', porPessoa: 0.04 },
      { item: 'Molho de tomate', unid: 'lt', porPessoa: 0.02 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Mostarda', unid: 'ml', porPessoa: 5 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Corte o palmito em rodelas e refogue com cebola.',
      'Acrescente molho de tomate e mostarda, temperando.',
      'Reduza o fogo e adicione o creme de leite.',
      'Aqueça sem ferver e sirva com arroz e batata palha.',
    ],
    rendimentoPorcaoG: 270,
    tempoMin: 35,
    complexidade: 'media',
    obsOperacional: 'Escorrer e enxaguar o palmito remove excesso de acidez.',
    nutricao: { kcal: 250, prot: 9, carb: 18, gord: 16, fibra: 6, sodio: 500 },
    substituicoes: ['Cogumelos no lugar de parte do palmito'],
    adequacaoRefeitorio: 78,
  },
  {
    nome: 'Hambúrguer de grão-de-bico',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'outros',
    tags: ['vegetariano', 'forno', 'prato-unico'],
    ingredientes: [
      { item: 'Grão-de-bico', unid: 'kg', porPessoa: 0.06 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.015 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Farinha de trigo', unid: 'kg', porPessoa: 0.015 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Cozinhe o grão-de-bico e processe formando uma massa.',
      'Misture cebola, alho e farinha para dar liga.',
      'Tempere, modele os discos e disponha na assadeira.',
      'Asse virando na metade do tempo até dourar.',
    ],
    rendimentoPorcaoG: 250,
    tempoMin: 45,
    complexidade: 'media',
    obsOperacional: 'Modelar com aro padroniza o tamanho das porções.',
    nutricao: { kcal: 310, prot: 14, carb: 40, gord: 10, fibra: 9, sodio: 450 },
    substituicoes: ['Feijão branco no lugar do grão-de-bico'],
    adequacaoRefeitorio: 84,
  },
  {
    nome: 'Chili vegetariano',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'outros',
    tags: ['vegetariano', 'picante', 'prato-unico'],
    ingredientes: [
      { item: 'Feijão vermelho', unid: 'kg', porPessoa: 0.05 },
      { item: 'Milho', unid: 'kg', porPessoa: 0.04 },
      { item: 'Molho de tomate', unid: 'lt', porPessoa: 0.04 },
      { item: 'Pimentão', unid: 'kg', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Cozinhe o feijão vermelho até ficar macio.',
      'Refogue cebola e pimentão com cominho e páprica.',
      'Junte molho de tomate, milho e o feijão cozido.',
      'Cozinhe em fogo baixo até apurar; ajuste sal e pimenta.',
    ],
    rendimentoPorcaoG: 320,
    tempoMin: 50,
    complexidade: 'media',
    obsOperacional: 'Controlar a pimenta para agradar todos os comensais.',
    nutricao: { kcal: 320, prot: 15, carb: 48, gord: 8, fibra: 11, sodio: 520 },
    substituicoes: ['Proteína de soja para deixar mais encorpado'],
    adequacaoRefeitorio: 84,
  },
  {
    nome: 'Legumes ao curry com leite de coco',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['vegetariano', 'indiano', 'leve'],
    ingredientes: [
      { item: 'Abóbora', unid: 'kg', porPessoa: 0.08 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.05 },
      { item: 'Batata', unid: 'kg', porPessoa: 0.06 },
      { item: 'Coco ralado', unid: 'kg', porPessoa: 0.015 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Corte os legumes em cubos uniformes.',
      'Refogue cebola com curry no óleo.',
      'Junte os legumes e o leite de coco.',
      'Cozinhe até os legumes ficarem macios; ajuste o sal.',
    ],
    rendimentoPorcaoG: 300,
    tempoMin: 40,
    complexidade: 'media',
    obsOperacional: 'Cortes iguais garantem cozimento uniforme em escala.',
    nutricao: { kcal: 280, prot: 9, carb: 38, gord: 12, fibra: 8, sodio: 440 },
    substituicoes: ['Grão-de-bico para aumentar a proteína'],
    adequacaoRefeitorio: 84,
  },
  {
    nome: 'Torta de legumes',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['vegetariano', 'forno', 'comfort'],
    ingredientes: [
      { item: 'Farinha de trigo', unid: 'kg', porPessoa: 0.04 },
      { item: 'Ovo', unid: 'un', porPessoa: 1 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.04 },
      { item: 'Milho', unid: 'kg', porPessoa: 0.03 },
      { item: 'Pimentão', unid: 'kg', porPessoa: 0.02 },
      { item: 'Leite', unid: 'lt', porPessoa: 0.04 },
      { item: 'Óleo', unid: 'ml', porPessoa: 8 },
      { item: 'Sal', unid: 'g', porPessoa: 3 },
    ],
    preparo: [
      'Bata a massa líquida com farinha, ovo, leite, óleo e sal.',
      'Refogue os legumes picados e tempere.',
      'Monte em assadeira: metade da massa, recheio e o restante por cima.',
      'Asse até dourar e firmar; corte em fatias.',
    ],
    rendimentoPorcaoG: 280,
    tempoMin: 50,
    complexidade: 'media',
    obsOperacional: 'Massa líquida agiliza a produção em GN para muitas porções.',
    nutricao: { kcal: 340, prot: 12, carb: 46, gord: 13, fibra: 5, sodio: 520 },
    substituicoes: ['Brócolis e ervilha no recheio conforme a safra'],
    adequacaoRefeitorio: 82,
  },
];
