import type { Receita } from './tipos';

export const PRATOS: Receita[] = [
  {
    nome: 'Filé de tilápia grelhado ao limão',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'peixe',
    tags: ['grelhado', 'leve', 'fitness'],
    ingredientes: [
      { item: 'Tilápia', unid: 'kg', porPessoa: 0.16 },
      { item: 'Limão', unid: 'un', porPessoa: 0.5 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004, opcional: true },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.01 },
      { item: 'Sal', unid: 'kg', porPessoa: 0.003, opcional: true },
    ],
    preparo: [
      'Tempere os filés com sal, alho e suco de limão e deixe descansar 15 minutos.',
      'Aqueça a chapa com um fio de óleo até dourar.',
      'Grelhe os filés 3 a 4 minutos de cada lado até firmar a carne.',
      'Finalize com raspas de limão e sirva imediatamente.',
    ],
    rendimentoPorcaoG: 200,
    tempoMin: 30,
    complexidade: 'media',
    obsOperacional: 'Grelhar em lotes pequenos para não soltar água e cozinhar por igual.',
    nutricao: { kcal: 230, prot: 36, carb: 2, gord: 8, fibra: 0, sodio: 320 },
    substituicoes: ['Trocar tilápia por merluza', 'Usar filé de peixe genérico'],
    adequacaoRefeitorio: 90,
  },
  {
    nome: 'Tilápia assada com legumes',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'peixe',
    tags: ['assado', 'forno', 'leve'],
    ingredientes: [
      { item: 'Tilápia', unid: 'kg', porPessoa: 0.16 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.05 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.04 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.05 },
      { item: 'Limão', unid: 'un', porPessoa: 0.5 },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.01 },
      { item: 'Sal', unid: 'kg', porPessoa: 0.003, opcional: true },
    ],
    preparo: [
      'Tempere os filés com sal e limão.',
      'Forre a assadeira com cenoura, cebola e tomate em rodelas.',
      'Disponha os filés sobre os legumes e regue com óleo.',
      'Asse a 200 °C por cerca de 25 minutos até o peixe firmar.',
    ],
    rendimentoPorcaoG: 240,
    tempoMin: 45,
    complexidade: 'media',
    obsOperacional: 'Cortar legumes em espessura uniforme para assarem junto com o peixe.',
    nutricao: { kcal: 250, prot: 34, carb: 10, gord: 8, fibra: 3, sodio: 340 },
    substituicoes: ['Trocar tilápia por merluza'],
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Peixe ao molho de tomate',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'peixe',
    tags: ['molho', 'forno', 'caseiro'],
    ingredientes: [
      { item: 'Filé de peixe', unid: 'kg', porPessoa: 0.16 },
      { item: 'Molho de tomate', unid: 'lt', porPessoa: 0.04 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.04 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.01 },
      { item: 'Sal', unid: 'kg', porPessoa: 0.003, opcional: true },
    ],
    preparo: [
      'Refogue cebola e alho no óleo até dourar.',
      'Acrescente o molho de tomate e cozinhe por 5 minutos.',
      'Acomode os filés temperados no molho e cozinhe em fogo baixo.',
      'Tampe e finalize por cerca de 12 minutos até o peixe cozinhar.',
    ],
    rendimentoPorcaoG: 220,
    tempoMin: 35,
    complexidade: 'media',
    nutricao: { kcal: 240, prot: 33, carb: 8, gord: 8, fibra: 2, sodio: 480 },
    substituicoes: ['Trocar filé por posta de merluza'],
    adequacaoRefeitorio: 85,
  },
  {
    nome: 'Filé de merluza à dorê',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'peixe',
    tags: ['frito', 'empanado', 'comfort'],
    ingredientes: [
      { item: 'Merluza', unid: 'kg', porPessoa: 0.16 },
      { item: 'Farinha de trigo', unid: 'kg', porPessoa: 0.03 },
      { item: 'Ovos', unid: 'un', porPessoa: 0.5 },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.03 },
      { item: 'Limão', unid: 'un', porPessoa: 0.3 },
      { item: 'Sal', unid: 'kg', porPessoa: 0.003, opcional: true },
    ],
    preparo: [
      'Tempere a merluza com sal e limão.',
      'Passe os filés na farinha e depois no ovo batido.',
      'Frite em óleo quente até dourar dos dois lados.',
      'Escorra sobre papel e mantenha aquecido até servir.',
    ],
    rendimentoPorcaoG: 200,
    tempoMin: 35,
    complexidade: 'media',
    obsOperacional: 'Manter o óleo a cerca de 180 °C e fritar em pequenas porções.',
    nutricao: { kcal: 320, prot: 30, carb: 14, gord: 16, fibra: 1, sodio: 420 },
    substituicoes: ['Trocar merluza por tilápia'],
    adequacaoRefeitorio: 76,
  },
  {
    nome: 'Isca de peixe empanada',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'peixe',
    tags: ['frito', 'empanado', 'comfort'],
    ingredientes: [
      { item: 'Filé de peixe', unid: 'kg', porPessoa: 0.16 },
      { item: 'Farinha de trigo', unid: 'kg', porPessoa: 0.03 },
      { item: 'Ovos', unid: 'un', porPessoa: 0.5 },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.03 },
      { item: 'Limão', unid: 'un', porPessoa: 0.3 },
      { item: 'Sal', unid: 'kg', porPessoa: 0.003, opcional: true },
    ],
    preparo: [
      'Corte os filés em tiras e tempere com sal e limão.',
      'Empane passando na farinha, no ovo e novamente na farinha.',
      'Frite em óleo quente até ficarem douradas e crocantes.',
      'Escorra bem e sirva com gomos de limão.',
    ],
    rendimentoPorcaoG: 190,
    tempoMin: 35,
    complexidade: 'media',
    obsOperacional: 'Empanar todas as iscas antes de iniciar a fritura para agilizar a produção.',
    nutricao: { kcal: 330, prot: 29, carb: 16, gord: 16, fibra: 1, sodio: 440 },
    substituicoes: ['Trocar filé por merluza'],
    adequacaoRefeitorio: 74,
  },
  {
    nome: 'Escondidinho de peixe',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'peixe',
    tags: ['forno', 'prato-unico', 'comfort'],
    ingredientes: [
      { item: 'Filé de peixe', unid: 'kg', porPessoa: 0.15 },
      { item: 'Batata', unid: 'kg', porPessoa: 0.18 },
      { item: 'Leite', unid: 'lt', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.04 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.01 },
      { item: 'Sal', unid: 'kg', porPessoa: 0.003, opcional: true },
    ],
    preparo: [
      'Cozinhe e amasse as batatas com leite formando um purê.',
      'Refogue cebola e alho e acrescente o peixe desfiado e temperado.',
      'Monte em camadas com o purê por cima.',
      'Leve ao forno a 200 °C até gratinar a superfície.',
    ],
    rendimentoPorcaoG: 250,
    tempoMin: 50,
    complexidade: 'media',
    obsOperacional: 'Montar em GNs grandes e gratinar em bloco para servir em porções.',
    nutricao: { kcal: 300, prot: 30, carb: 18, gord: 10, fibra: 2, sodio: 420 },
    substituicoes: ['Trocar batata por aipim', 'Trocar filé por merluza'],
    adequacaoRefeitorio: 84,
  },
  {
    nome: 'Moqueca de peixe',
    categoria: 'principal',
    classe: 'premium',
    proteina: 'peixe',
    tags: ['regional', 'molho', 'prato-unico'],
    ingredientes: [
      { item: 'Filé de peixe', unid: 'kg', porPessoa: 0.16 },
      { item: 'Creme de Leite', unid: 'lt', porPessoa: 0.03 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.05 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.05 },
      { item: 'Pimentão', unid: 'kg', porPessoa: 0.04 },
      { item: 'Coentro', unid: 'mç', porPessoa: 0.05, opcional: true },
      { item: 'Limão', unid: 'un', porPessoa: 0.3 },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.01 },
    ],
    preparo: [
      'Tempere os filés com sal e limão.',
      'Faça camadas de cebola, tomate e pimentão na panela.',
      'Adicione o peixe e regue com leite de coco e óleo.',
      'Cozinhe tampado em fogo baixo e finalize com coentro.',
    ],
    rendimentoPorcaoG: 250,
    tempoMin: 50,
    complexidade: 'alta',
    obsOperacional: 'Não mexer durante o cozimento para o peixe não desmanchar.',
    nutricao: { kcal: 300, prot: 32, carb: 8, gord: 16, fibra: 2, sodio: 460 },
    substituicoes: ['Usar leite de coco no lugar do creme de leite'],
    adequacaoRefeitorio: 80,
  },
  {
    nome: 'Peixe ensopado com batata',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'peixe',
    tags: ['ensopado', 'caseiro', 'prato-unico'],
    ingredientes: [
      { item: 'Merluza', unid: 'kg', porPessoa: 0.16 },
      { item: 'Batata', unid: 'kg', porPessoa: 0.06 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.05 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.04 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.01 },
      { item: 'Sal', unid: 'kg', porPessoa: 0.003, opcional: true },
    ],
    preparo: [
      'Refogue cebola, alho e tomate no óleo.',
      'Acrescente a batata em cubos e água, cozinhando até amaciar.',
      'Adicione as postas de merluza temperadas.',
      'Cozinhe em fogo baixo até o peixe ficar firme.',
    ],
    rendimentoPorcaoG: 250,
    tempoMin: 45,
    complexidade: 'media',
    nutricao: { kcal: 260, prot: 30, carb: 16, gord: 7, fibra: 2, sodio: 400 },
    substituicoes: ['Trocar merluza por filé de peixe'],
    adequacaoRefeitorio: 83,
  },
  {
    nome: 'Sardinha assada',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'peixe',
    tags: ['assado', 'forno', 'leve'],
    ingredientes: [
      { item: 'Sardinha', unid: 'kg', porPessoa: 0.18 },
      { item: 'Limão', unid: 'un', porPessoa: 0.5 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.04 },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.01 },
      { item: 'Sal', unid: 'kg', porPessoa: 0.003, opcional: true },
    ],
    preparo: [
      'Tempere as sardinhas limpas com sal, alho e limão.',
      'Disponha em assadeira com rodelas de cebola.',
      'Regue com óleo e asse a 200 °C por cerca de 25 minutos.',
      'Sirva com gomos de limão.',
    ],
    rendimentoPorcaoG: 200,
    tempoMin: 40,
    complexidade: 'media',
    obsOperacional: 'Pedir sardinha já limpa para reduzir tempo de pré-preparo.',
    nutricao: { kcal: 280, prot: 32, carb: 2, gord: 16, fibra: 0, sodio: 420 },
    substituicoes: ['Trocar sardinha por filé de peixe'],
    adequacaoRefeitorio: 78,
  },
  {
    nome: 'Filé à belle meunière',
    categoria: 'principal',
    classe: 'premium',
    proteina: 'peixe',
    tags: ['molho', 'grelhado', 'classico'],
    ingredientes: [
      { item: 'Filé de peixe', unid: 'kg', porPessoa: 0.16 },
      { item: 'Farinha de trigo', unid: 'kg', porPessoa: 0.02 },
      { item: 'Limão', unid: 'un', porPessoa: 0.4 },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.02 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.03 },
      { item: 'Sal', unid: 'kg', porPessoa: 0.003, opcional: true },
    ],
    preparo: [
      'Tempere e passe os filés levemente na farinha.',
      'Doure os filés na frigideira com óleo.',
      'Prepare um molho com suco de limão e tomate em cubos.',
      'Regue os filés com o molho e sirva quente.',
    ],
    rendimentoPorcaoG: 210,
    tempoMin: 40,
    complexidade: 'alta',
    nutricao: { kcal: 300, prot: 32, carb: 8, gord: 14, fibra: 1, sodio: 380 },
    substituicoes: ['Trocar filé por merluza'],
    adequacaoRefeitorio: 79,
  },
  {
    nome: 'Filé de peixe com crosta de ervas',
    categoria: 'principal',
    classe: 'premium',
    proteina: 'peixe',
    tags: ['assado', 'forno', 'gourmet'],
    ingredientes: [
      { item: 'Filé de peixe', unid: 'kg', porPessoa: 0.16 },
      { item: 'Farinha de trigo', unid: 'kg', porPessoa: 0.02 },
      { item: 'Coentro', unid: 'mç', porPessoa: 0.04, opcional: true },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Limão', unid: 'un', porPessoa: 0.3 },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.01 },
      { item: 'Sal', unid: 'kg', porPessoa: 0.003, opcional: true },
    ],
    preparo: [
      'Tempere os filés com sal, alho e limão.',
      'Misture farinha com ervas picadas e óleo formando a crosta.',
      'Cubra os filés com a mistura.',
      'Asse a 200 °C por cerca de 20 minutos até dourar a crosta.',
    ],
    rendimentoPorcaoG: 200,
    tempoMin: 40,
    complexidade: 'media',
    nutricao: { kcal: 270, prot: 34, carb: 8, gord: 10, fibra: 1, sodio: 360 },
    substituicoes: ['Trocar filé por tilápia'],
    adequacaoRefeitorio: 85,
  },
  {
    nome: 'Posta de peixe ao forno',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'peixe',
    tags: ['assado', 'forno', 'leve'],
    ingredientes: [
      { item: 'Filé de peixe', unid: 'kg', porPessoa: 0.17 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.04 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.05 },
      { item: 'Limão', unid: 'un', porPessoa: 0.5 },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.01 },
      { item: 'Sal', unid: 'kg', porPessoa: 0.003, opcional: true },
    ],
    preparo: [
      'Tempere as postas com sal e limão.',
      'Acomode em assadeira com cebola e tomate em rodelas.',
      'Regue com óleo e cubra com papel-alumínio.',
      'Asse a 200 °C por cerca de 30 minutos.',
    ],
    rendimentoPorcaoG: 230,
    tempoMin: 45,
    complexidade: 'baixa',
    obsOperacional: 'Assar coberto preserva a umidade do peixe em grandes volumes.',
    nutricao: { kcal: 240, prot: 35, carb: 6, gord: 8, fibra: 1, sodio: 320 },
    substituicoes: ['Trocar filé por merluza'],
    adequacaoRefeitorio: 87,
  },
  {
    nome: 'Bobó de peixe',
    categoria: 'principal',
    classe: 'premium',
    proteina: 'peixe',
    tags: ['regional', 'molho', 'prato-unico'],
    ingredientes: [
      { item: 'Filé de peixe', unid: 'kg', porPessoa: 0.15 },
      { item: 'Batata', unid: 'kg', porPessoa: 0.06 },
      { item: 'Creme de Leite', unid: 'lt', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.04 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.04 },
      { item: 'Coentro', unid: 'mç', porPessoa: 0.04, opcional: true },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.01 },
    ],
    preparo: [
      'Cozinhe e bata a batata formando um creme.',
      'Refogue cebola e tomate, junte o creme e o leite de coco.',
      'Acrescente o peixe em cubos e cozinhe em fogo baixo.',
      'Finalize com coentro picado.',
    ],
    rendimentoPorcaoG: 250,
    tempoMin: 50,
    complexidade: 'alta',
    obsOperacional: 'Mexer com cuidado para o creme ficar liso e o peixe inteiro.',
    nutricao: { kcal: 310, prot: 30, carb: 16, gord: 14, fibra: 2, sodio: 460 },
    substituicoes: ['Usar leite de coco no lugar do creme de leite'],
    adequacaoRefeitorio: 78,
  },
  {
    nome: 'Peixe ao molho de coco',
    categoria: 'principal',
    classe: 'premium',
    proteina: 'peixe',
    tags: ['molho', 'regional', 'cremoso'],
    ingredientes: [
      { item: 'Filé de peixe', unid: 'kg', porPessoa: 0.16 },
      { item: 'Creme de Leite', unid: 'lt', porPessoa: 0.04 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.04 },
      { item: 'Pimentão', unid: 'kg', porPessoa: 0.03 },
      { item: 'Coentro', unid: 'mç', porPessoa: 0.04, opcional: true },
      { item: 'Limão', unid: 'un', porPessoa: 0.3 },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.01 },
    ],
    preparo: [
      'Tempere os filés com sal e limão.',
      'Refogue cebola e pimentão no óleo.',
      'Adicione o leite de coco e deixe apurar.',
      'Acomode o peixe no molho e cozinhe em fogo baixo até firmar.',
    ],
    rendimentoPorcaoG: 230,
    tempoMin: 40,
    complexidade: 'media',
    nutricao: { kcal: 300, prot: 31, carb: 6, gord: 16, fibra: 1, sodio: 420 },
    substituicoes: ['Usar leite de coco no lugar do creme de leite'],
    adequacaoRefeitorio: 81,
  },
  {
    nome: 'Tilápia grelhada com purê',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'peixe',
    tags: ['grelhado', 'prato-unico', 'comfort'],
    ingredientes: [
      { item: 'Tilápia', unid: 'kg', porPessoa: 0.15 },
      { item: 'Batata', unid: 'kg', porPessoa: 0.18 },
      { item: 'Leite', unid: 'lt', porPessoa: 0.03 },
      { item: 'Limão', unid: 'un', porPessoa: 0.3 },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.01 },
      { item: 'Sal', unid: 'kg', porPessoa: 0.003, opcional: true },
    ],
    preparo: [
      'Cozinhe e amasse a batata com leite formando o purê.',
      'Tempere a tilápia com sal e limão.',
      'Grelhe os filés na chapa até dourar dos dois lados.',
      'Sirva o filé sobre o purê quente.',
    ],
    rendimentoPorcaoG: 250,
    tempoMin: 45,
    complexidade: 'media',
    nutricao: { kcal: 290, prot: 33, carb: 18, gord: 9, fibra: 2, sodio: 360 },
    substituicoes: ['Trocar tilápia por merluza'],
    adequacaoRefeitorio: 86,
  },
  {
    nome: 'Filé de peixe grelhado ao alho',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'peixe',
    tags: ['grelhado', 'leve', 'fitness'],
    ingredientes: [
      { item: 'Filé de peixe', unid: 'kg', porPessoa: 0.16 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.005 },
      { item: 'Limão', unid: 'un', porPessoa: 0.4 },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.01 },
      { item: 'Coentro', unid: 'mç', porPessoa: 0.03, opcional: true },
      { item: 'Sal', unid: 'kg', porPessoa: 0.003, opcional: true },
    ],
    preparo: [
      'Tempere os filés com alho, sal e limão.',
      'Aqueça a chapa com um fio de óleo.',
      'Grelhe os filés por 3 a 4 minutos de cada lado.',
      'Finalize com coentro picado e sirva.',
    ],
    rendimentoPorcaoG: 200,
    tempoMin: 30,
    complexidade: 'baixa',
    nutricao: { kcal: 230, prot: 36, carb: 2, gord: 8, fibra: 0, sodio: 300 },
    substituicoes: ['Trocar filé por tilápia'],
    adequacaoRefeitorio: 91,
  },
  {
    nome: 'Caldeirada de peixe',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'peixe',
    tags: ['ensopado', 'prato-unico', 'caseiro'],
    ingredientes: [
      { item: 'Filé de peixe', unid: 'kg', porPessoa: 0.16 },
      { item: 'Batata', unid: 'kg', porPessoa: 0.06 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.04 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.04 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.04 },
      { item: 'Pimentão', unid: 'kg', porPessoa: 0.03 },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.01 },
    ],
    preparo: [
      'Refogue cebola, alho, tomate e pimentão.',
      'Junte batata e cenoura em cubos e cubra com água.',
      'Cozinhe os legumes até quase amaciarem.',
      'Acrescente o peixe e finalize o cozimento sem mexer demais.',
    ],
    rendimentoPorcaoG: 250,
    tempoMin: 50,
    complexidade: 'media',
    obsOperacional: 'Adicionar o peixe por último para que não se desfaça no caldo.',
    nutricao: { kcal: 270, prot: 32, carb: 16, gord: 8, fibra: 3, sodio: 420 },
    substituicoes: ['Trocar filé por merluza'],
    adequacaoRefeitorio: 84,
  },
  {
    nome: 'Peixe à portuguesa',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'peixe',
    tags: ['assado', 'forno', 'classico'],
    ingredientes: [
      { item: 'Filé de peixe', unid: 'kg', porPessoa: 0.16 },
      { item: 'Batata', unid: 'kg', porPessoa: 0.06 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.05 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.05 },
      { item: 'Ovos', unid: 'un', porPessoa: 0.4 },
      { item: 'Óleo', unid: 'lt', porPessoa: 0.01 },
      { item: 'Sal', unid: 'kg', porPessoa: 0.003, opcional: true },
    ],
    preparo: [
      'Cozinhe levemente a batata e os ovos e corte em rodelas.',
      'Monte a assadeira em camadas com cebola, tomate, batata e peixe.',
      'Regue com óleo e distribua as rodelas de ovo por cima.',
      'Asse a 200 °C por cerca de 30 minutos.',
    ],
    rendimentoPorcaoG: 250,
    tempoMin: 55,
    complexidade: 'media',
    obsOperacional: 'Montar em camadas firmes para fatiar porções uniformes na distribuição.',
    nutricao: { kcal: 290, prot: 32, carb: 16, gord: 11, fibra: 2, sodio: 440 },
    substituicoes: ['Trocar filé por merluza'],
    adequacaoRefeitorio: 85,
  },
];
