import type { Receita } from './tipos';

export const PRATOS: Receita[] = [
  // ===================== SALADAS FRIAS =====================
  {
    nome: 'Salada de Alface com Tomate',
    categoria: 'salada',
    classe: 'economica',
    proteina: 'outros',
    tags: ['fria', 'folhas', 'refrescante'],
    ingredientes: [
      { item: 'Alface', unid: 'kg', porPessoa: 0.06 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.05 },
      { item: 'Óleo', unid: 'ml', porPessoa: 3 },
      { item: 'Limão', unid: 'un', porPessoa: 0.1 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Higienize a alface, escorra bem e rasgue em pedaços.',
      'Corte o tomate em meias-luas.',
      'Misture, tempere com óleo, limão e sal apenas no momento de servir.',
    ],
    rendimentoPorcaoG: 100,
    tempoMin: 15,
    complexidade: 'baixa',
    obsOperacional: 'Temperar só na hora para não murchar as folhas.',
    nutricao: { kcal: 55, prot: 2, carb: 6, gord: 3, fibra: 2, sodio: 140 },
    substituicoes: ['Alface americano no lugar da alface lisa'],
    adequacaoRefeitorio: 94,
  },
  {
    nome: 'Salada de Repolho com Cenoura',
    categoria: 'salada',
    classe: 'economica',
    proteina: 'outros',
    tags: ['fria', 'fibra', 'refrescante'],
    ingredientes: [
      { item: 'Repolho', unid: 'kg', porPessoa: 0.07 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.04 },
      { item: 'Limão', unid: 'un', porPessoa: 0.15 },
      { item: 'Óleo', unid: 'ml', porPessoa: 3 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Fatie o repolho bem fino.',
      'Rale a cenoura no ralo grosso.',
      'Misture os dois e tempere com limão, óleo e sal.',
    ],
    rendimentoPorcaoG: 110,
    tempoMin: 18,
    complexidade: 'baixa',
    nutricao: { kcal: 60, prot: 2, carb: 9, gord: 2, fibra: 3, sodio: 150 },
    adequacaoRefeitorio: 92,
  },
  {
    nome: 'Vinagrete',
    categoria: 'salada',
    classe: 'economica',
    proteina: 'outros',
    tags: ['fria', 'refrescante', 'molho'],
    ingredientes: [
      { item: 'Tomate', unid: 'kg', porPessoa: 0.05 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Pimentão', unid: 'kg', porPessoa: 0.02 },
      { item: 'Óleo', unid: 'ml', porPessoa: 4 },
      { item: 'Limão', unid: 'un', porPessoa: 0.15 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Corte tomate, cebola e pimentão em cubos pequenos.',
      'Junte tudo numa cuba e tempere com óleo, limão e sal.',
      'Deixe descansar refrigerado por 20 minutos antes de servir.',
    ],
    rendimentoPorcaoG: 90,
    tempoMin: 20,
    complexidade: 'baixa',
    nutricao: { kcal: 65, prot: 1, carb: 7, gord: 4, fibra: 2, sodio: 160 },
    adequacaoRefeitorio: 93,
  },
  {
    nome: 'Salada de Beterraba Cozida',
    categoria: 'salada',
    classe: 'economica',
    proteina: 'outros',
    tags: ['fria', 'legume', 'fibra'],
    ingredientes: [
      { item: 'Beterraba', unid: 'kg', porPessoa: 0.08 },
      { item: 'Limão', unid: 'un', porPessoa: 0.15 },
      { item: 'Óleo', unid: 'ml', porPessoa: 3 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Cozinhe as beterrabas inteiras até ficarem macias.',
      'Descasque e corte em cubos ou rodelas.',
      'Tempere frio com limão, óleo e sal.',
    ],
    rendimentoPorcaoG: 100,
    tempoMin: 35,
    complexidade: 'baixa',
    obsOperacional: 'Cozinhar com casca preserva a cor; resfriar antes de cortar.',
    nutricao: { kcal: 75, prot: 2, carb: 14, gord: 2, fibra: 3, sodio: 170 },
    adequacaoRefeitorio: 90,
  },
  {
    nome: 'Salada de Cenoura Ralada',
    categoria: 'salada',
    classe: 'economica',
    proteina: 'outros',
    tags: ['fria', 'legume', 'refrescante'],
    ingredientes: [
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.08 },
      { item: 'Limão', unid: 'un', porPessoa: 0.2 },
      { item: 'Óleo', unid: 'ml', porPessoa: 3 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Rale a cenoura no ralo fino.',
      'Tempere com suco de limão, óleo e sal.',
      'Sirva gelada.',
    ],
    rendimentoPorcaoG: 90,
    tempoMin: 15,
    complexidade: 'baixa',
    nutricao: { kcal: 70, prot: 1, carb: 12, gord: 2, fibra: 3, sodio: 130 },
    adequacaoRefeitorio: 91,
  },
  {
    nome: 'Salada de Pepino',
    categoria: 'salada',
    classe: 'economica',
    proteina: 'outros',
    tags: ['fria', 'refrescante', 'legume'],
    ingredientes: [
      { item: 'Pepino', unid: 'kg', porPessoa: 0.08 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Limão', unid: 'un', porPessoa: 0.15 },
      { item: 'Óleo', unid: 'ml', porPessoa: 3 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Fatie o pepino em rodelas finas.',
      'Adicione a cebola em fatias finas.',
      'Tempere com limão, óleo e sal pouco antes de servir.',
    ],
    rendimentoPorcaoG: 95,
    tempoMin: 15,
    complexidade: 'baixa',
    obsOperacional: 'O pepino solta água; temperar próximo ao serviço.',
    nutricao: { kcal: 45, prot: 1, carb: 5, gord: 2, fibra: 1, sodio: 120 },
    adequacaoRefeitorio: 90,
  },
  {
    nome: 'Salpicão de Frango',
    categoria: 'salada',
    classe: 'equilibrada',
    proteina: 'frango',
    tags: ['fria', 'prato-unico', 'fibra'],
    ingredientes: [
      { item: 'Peito de Frango', unid: 'kg', porPessoa: 0.06 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.03 },
      { item: 'Milho (lata)', unid: 'lata', porPessoa: 0.08 },
      { item: 'Maionese', unid: 'kg', porPessoa: 0.025 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Cozinhe o peito de frango e desfie.',
      'Rale a cenoura e escorra o milho.',
      'Misture tudo com a maionese e ajuste o sal.',
      'Resfrie antes de servir.',
    ],
    rendimentoPorcaoG: 120,
    tempoMin: 35,
    complexidade: 'baixa',
    obsOperacional: 'Manter sob refrigeração; produto sensível por conter maionese.',
    nutricao: { kcal: 175, prot: 10, carb: 12, gord: 10, fibra: 2, sodio: 320 },
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Maionese de Legumes',
    categoria: 'salada',
    classe: 'economica',
    proteina: 'outros',
    tags: ['fria', 'legume', 'fibra'],
    ingredientes: [
      { item: 'Batata', unid: 'kg', porPessoa: 0.06 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.03 },
      { item: 'Milho (lata)', unid: 'lata', porPessoa: 0.06 },
      { item: 'Maionese', unid: 'kg', porPessoa: 0.025 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Cozinhe batata e cenoura em cubos até ficarem macias e firmes.',
      'Resfrie completamente e escorra o milho.',
      'Misture com a maionese e ajuste o sal.',
    ],
    rendimentoPorcaoG: 120,
    tempoMin: 35,
    complexidade: 'baixa',
    obsOperacional: 'Resfriar os legumes antes de adicionar a maionese.',
    nutricao: { kcal: 150, prot: 3, carb: 18, gord: 8, fibra: 3, sodio: 300 },
    adequacaoRefeitorio: 89,
  },
  {
    nome: 'Salada Tropical de Alface com Manga',
    categoria: 'salada',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['fria', 'folhas', 'refrescante'],
    ingredientes: [
      { item: 'Alface', unid: 'kg', porPessoa: 0.05 },
      { item: 'Manga', unid: 'kg', porPessoa: 0.05 },
      { item: 'Cebola roxa', unid: 'kg', porPessoa: 0.015 },
      { item: 'Limão', unid: 'un', porPessoa: 0.15 },
      { item: 'Óleo', unid: 'ml', porPessoa: 3 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Rasgue a alface higienizada e disponha na cuba.',
      'Corte a manga em cubos e a cebola roxa em fatias finas.',
      'Distribua sobre as folhas e regue com limão, óleo e sal.',
    ],
    rendimentoPorcaoG: 105,
    tempoMin: 18,
    complexidade: 'baixa',
    nutricao: { kcal: 90, prot: 1, carb: 16, gord: 3, fibra: 2, sodio: 110 },
    adequacaoRefeitorio: 87,
  },
  {
    nome: 'Tabule',
    categoria: 'salada',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['fria', 'fibra', 'refrescante'],
    ingredientes: [
      { item: 'Tomate', unid: 'kg', porPessoa: 0.05 },
      { item: 'Pepino', unid: 'kg', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Limão', unid: 'un', porPessoa: 0.2 },
      { item: 'Óleo', unid: 'ml', porPessoa: 4 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Hidrate o trigo para quibe e escorra bem.',
      'Pique tomate, pepino e cebola em cubos pequenos.',
      'Misture com o trigo e tempere com limão, óleo e sal.',
    ],
    rendimentoPorcaoG: 110,
    tempoMin: 30,
    complexidade: 'baixa',
    obsOperacional: 'Escorrer bem o trigo para o tabule não ficar encharcado.',
    nutricao: { kcal: 130, prot: 3, carb: 20, gord: 4, fibra: 4, sodio: 180 },
    adequacaoRefeitorio: 86,
  },
  {
    nome: 'Salada de Grão-de-Bico',
    categoria: 'salada',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['fria', 'fibra', 'vegetariano'],
    ingredientes: [
      { item: 'Grão-de-bico', unid: 'kg', porPessoa: 0.06 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.03 },
      { item: 'Cebola roxa', unid: 'kg', porPessoa: 0.015 },
      { item: 'Óleo', unid: 'ml', porPessoa: 4 },
      { item: 'Limão', unid: 'un', porPessoa: 0.15 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Cozinhe o grão-de-bico até ficar macio e escorra.',
      'Pique o tomate e a cebola roxa em cubos.',
      'Misture frio e tempere com óleo, limão e sal.',
    ],
    rendimentoPorcaoG: 120,
    tempoMin: 40,
    complexidade: 'baixa',
    obsOperacional: 'Deixar o grão de molho na véspera reduz o tempo de cocção.',
    nutricao: { kcal: 165, prot: 8, carb: 20, gord: 6, fibra: 5, sodio: 200 },
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Salada de Batata',
    categoria: 'salada',
    classe: 'economica',
    proteina: 'outros',
    tags: ['fria', 'legume', 'fibra'],
    ingredientes: [
      { item: 'Batata', unid: 'kg', porPessoa: 0.09 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Maionese', unid: 'kg', porPessoa: 0.02 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Cozinhe a batata em cubos até ficar firme e macia.',
      'Resfrie e misture com a cebola bem picada.',
      'Adicione a maionese e ajuste o sal.',
    ],
    rendimentoPorcaoG: 130,
    tempoMin: 35,
    complexidade: 'baixa',
    obsOperacional: 'Não cozinhar demais para a batata não desmanchar.',
    nutricao: { kcal: 160, prot: 3, carb: 22, gord: 7, fibra: 2, sodio: 260 },
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Coleslaw',
    categoria: 'salada',
    classe: 'economica',
    proteina: 'outros',
    tags: ['fria', 'fibra', 'refrescante'],
    ingredientes: [
      { item: 'Repolho', unid: 'kg', porPessoa: 0.06 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.03 },
      { item: 'Maionese', unid: 'kg', porPessoa: 0.025 },
      { item: 'Limão', unid: 'un', porPessoa: 0.1 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Fatie o repolho bem fino e rale a cenoura.',
      'Misture a maionese com o suco de limão e o sal.',
      'Incorpore o molho aos vegetais e resfrie antes de servir.',
    ],
    rendimentoPorcaoG: 110,
    tempoMin: 20,
    complexidade: 'baixa',
    nutricao: { kcal: 130, prot: 2, carb: 10, gord: 9, fibra: 3, sodio: 290 },
    adequacaoRefeitorio: 89,
  },
  {
    nome: 'Salada de Folhas com Milho',
    categoria: 'salada',
    classe: 'economica',
    proteina: 'outros',
    tags: ['fria', 'folhas', 'refrescante'],
    ingredientes: [
      { item: 'Alface', unid: 'kg', porPessoa: 0.05 },
      { item: 'Rúcula', unid: 'kg', porPessoa: 0.02 },
      { item: 'Milho (lata)', unid: 'lata', porPessoa: 0.07 },
      { item: 'Óleo', unid: 'ml', porPessoa: 3 },
      { item: 'Limão', unid: 'un', porPessoa: 0.1 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Higienize e rasgue alface e rúcula.',
      'Escorra o milho e distribua sobre as folhas.',
      'Tempere com óleo, limão e sal na hora de servir.',
    ],
    rendimentoPorcaoG: 100,
    tempoMin: 18,
    complexidade: 'baixa',
    nutricao: { kcal: 80, prot: 2, carb: 11, gord: 3, fibra: 2, sodio: 170 },
    adequacaoRefeitorio: 91,
  },
  {
    nome: 'Salada Caprese Simples',
    categoria: 'salada',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['fria', 'refrescante'],
    ingredientes: [
      { item: 'Tomate', unid: 'kg', porPessoa: 0.08 },
      { item: 'Óleo', unid: 'ml', porPessoa: 4 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Corte o tomate em rodelas e intercale com fatias de muçarela.',
      'Distribua folhas de manjericão por cima.',
      'Regue com azeite e finalize com sal.',
    ],
    rendimentoPorcaoG: 100,
    tempoMin: 15,
    complexidade: 'baixa',
    obsOperacional: 'Montar em camadas na cuba para facilitar o autosserviço.',
    nutricao: { kcal: 120, prot: 6, carb: 5, gord: 9, fibra: 1, sodio: 240 },
    substituicoes: ['Tomate em rodelas com queijo branco'],
    adequacaoRefeitorio: 84,
  },
  {
    nome: 'Salada de Acelga',
    categoria: 'salada',
    classe: 'economica',
    proteina: 'outros',
    tags: ['fria', 'folhas', 'refrescante'],
    ingredientes: [
      { item: 'Acelga', unid: 'kg', porPessoa: 0.07 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.03 },
      { item: 'Limão', unid: 'un', porPessoa: 0.15 },
      { item: 'Óleo', unid: 'ml', porPessoa: 3 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Fatie a acelga em tiras finas e higienize.',
      'Rale a cenoura e misture com a acelga.',
      'Tempere com limão, óleo e sal.',
    ],
    rendimentoPorcaoG: 105,
    tempoMin: 18,
    complexidade: 'baixa',
    nutricao: { kcal: 50, prot: 2, carb: 7, gord: 2, fibra: 3, sodio: 150 },
    adequacaoRefeitorio: 90,
  },
  {
    nome: 'Mix de Folhas com Cenoura',
    categoria: 'salada',
    classe: 'economica',
    proteina: 'outros',
    tags: ['fria', 'folhas', 'fibra'],
    ingredientes: [
      { item: 'Alface americano', unid: 'kg', porPessoa: 0.04 },
      { item: 'Agrião', unid: 'kg', porPessoa: 0.02 },
      { item: 'Rúcula', unid: 'kg', porPessoa: 0.02 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.03 },
      { item: 'Óleo', unid: 'ml', porPessoa: 3 },
      { item: 'Limão', unid: 'un', porPessoa: 0.1 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Higienize todas as folhas e escorra bem.',
      'Misture as folhas com a cenoura ralada.',
      'Tempere com óleo, limão e sal no momento do serviço.',
    ],
    rendimentoPorcaoG: 95,
    tempoMin: 20,
    complexidade: 'baixa',
    nutricao: { kcal: 55, prot: 2, carb: 6, gord: 3, fibra: 2, sodio: 130 },
    adequacaoRefeitorio: 92,
  },
  {
    nome: 'Salada de Pepino com Iogurte',
    categoria: 'salada',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['fria', 'refrescante', 'legume'],
    ingredientes: [
      { item: 'Pepino', unid: 'kg', porPessoa: 0.08 },
      { item: 'Limão', unid: 'un', porPessoa: 0.1 },
      { item: 'Óleo', unid: 'ml', porPessoa: 2 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Fatie o pepino em rodelas finas e escorra o excesso de água.',
      'Misture o iogurte natural com limão, óleo e sal.',
      'Combine o molho com o pepino e resfrie antes de servir.',
    ],
    rendimentoPorcaoG: 100,
    tempoMin: 18,
    complexidade: 'baixa',
    obsOperacional: 'Manter refrigerado por conter laticínio.',
    nutricao: { kcal: 70, prot: 4, carb: 7, gord: 3, fibra: 1, sodio: 160 },
    adequacaoRefeitorio: 86,
  },
  {
    nome: 'Salada de Tomate com Cebola',
    categoria: 'salada',
    classe: 'economica',
    proteina: 'outros',
    tags: ['fria', 'refrescante'],
    ingredientes: [
      { item: 'Tomate', unid: 'kg', porPessoa: 0.08 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Óleo', unid: 'ml', porPessoa: 4 },
      { item: 'Limão', unid: 'un', porPessoa: 0.1 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Corte o tomate em meias-luas e a cebola em fatias finas.',
      'Misture numa cuba.',
      'Tempere com óleo, limão e sal e deixe descansar 10 minutos.',
    ],
    rendimentoPorcaoG: 100,
    tempoMin: 15,
    complexidade: 'baixa',
    nutricao: { kcal: 60, prot: 1, carb: 7, gord: 4, fibra: 2, sodio: 150 },
    adequacaoRefeitorio: 91,
  },
  {
    nome: 'Salada Agridoce de Repolho Roxo',
    categoria: 'salada',
    classe: 'economica',
    proteina: 'outros',
    tags: ['fria', 'fibra', 'refrescante'],
    ingredientes: [
      { item: 'Repolho roxo', unid: 'kg', porPessoa: 0.07 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.03 },
      { item: 'Limão', unid: 'un', porPessoa: 0.15 },
      { item: 'Óleo', unid: 'ml', porPessoa: 3 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Fatie o repolho roxo bem fino e rale a cenoura.',
      'Tempere com limão, óleo, sal e uma pitada de açúcar.',
      'Deixe marinar refrigerado por 20 minutos.',
    ],
    rendimentoPorcaoG: 110,
    tempoMin: 20,
    complexidade: 'baixa',
    obsOperacional: 'A acidez do limão realça a cor do repolho roxo.',
    nutricao: { kcal: 65, prot: 2, carb: 10, gord: 2, fibra: 3, sodio: 140 },
    adequacaoRefeitorio: 90,
  },

  // ===================== LEGUMES QUENTES (GUARNIÇÃO) =====================
  {
    nome: 'Legumes Refogados',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['legume', 'fibra'],
    ingredientes: [
      { item: 'Abobrinha', unid: 'kg', porPessoa: 0.05 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.04 },
      { item: 'Chuchu', unid: 'kg', porPessoa: 0.05 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Óleo', unid: 'ml', porPessoa: 4 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Corte todos os legumes em cubos uniformes.',
      'Refogue a cebola no óleo e acrescente os legumes mais firmes primeiro.',
      'Cozinhe em fogo médio até ficarem al dente e ajuste o sal.',
    ],
    rendimentoPorcaoG: 120,
    tempoMin: 25,
    complexidade: 'baixa',
    obsOperacional: 'Adicionar os legumes por ordem de cocção mantém a textura.',
    nutricao: { kcal: 90, prot: 2, carb: 11, gord: 4, fibra: 3, sodio: 200 },
    adequacaoRefeitorio: 92,
  },
  {
    nome: 'Abobrinha Refogada',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['legume', 'fibra'],
    ingredientes: [
      { item: 'Abobrinha', unid: 'kg', porPessoa: 0.1 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Óleo', unid: 'ml', porPessoa: 4 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Corte a abobrinha em meias-luas.',
      'Refogue a cebola no óleo e junte a abobrinha.',
      'Cozinhe em fogo alto rapidamente para manter a firmeza e tempere com sal.',
    ],
    rendimentoPorcaoG: 110,
    tempoMin: 20,
    complexidade: 'baixa',
    obsOperacional: 'Fogo alto e rápido evita que a abobrinha solte muita água.',
    nutricao: { kcal: 70, prot: 2, carb: 7, gord: 4, fibra: 2, sodio: 190 },
    adequacaoRefeitorio: 91,
  },
  {
    nome: 'Cenoura Cozida Amanteigada',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['legume', 'fibra'],
    ingredientes: [
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.1 },
      { item: 'Óleo', unid: 'ml', porPessoa: 3 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Corte a cenoura em rodelas.',
      'Cozinhe em água com sal até ficar macia e escorra.',
      'Finalize com manteiga ou óleo e ajuste o tempero.',
    ],
    rendimentoPorcaoG: 110,
    tempoMin: 25,
    complexidade: 'baixa',
    nutricao: { kcal: 95, prot: 1, carb: 14, gord: 4, fibra: 3, sodio: 200 },
    adequacaoRefeitorio: 90,
  },
  {
    nome: 'Couve Refogada',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['legume', 'folhas', 'fibra'],
    ingredientes: [
      { item: 'Couve', unid: 'kg', porPessoa: 0.06 },
      { item: 'Óleo', unid: 'ml', porPessoa: 4 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Corte a couve em tiras bem finas.',
      'Refogue rapidamente no óleo com alho.',
      'Tempere com sal e sirva imediatamente.',
    ],
    rendimentoPorcaoG: 90,
    tempoMin: 18,
    complexidade: 'baixa',
    obsOperacional: 'Refogar em pequenas levas para a couve não cozinhar demais.',
    nutricao: { kcal: 75, prot: 3, carb: 7, gord: 4, fibra: 3, sodio: 190 },
    adequacaoRefeitorio: 92,
  },
  {
    nome: 'Brócolis no Alho',
    categoria: 'guarnicao',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['legume', 'fibra'],
    ingredientes: [
      { item: 'Brócolis', unid: 'kg', porPessoa: 0.09 },
      { item: 'Óleo', unid: 'ml', porPessoa: 4 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Separe o brócolis em buquês e cozinhe rapidamente em água com sal.',
      'Escorra e refresque para manter a cor.',
      'Salteie no óleo com alho e ajuste o sal.',
    ],
    rendimentoPorcaoG: 100,
    tempoMin: 22,
    complexidade: 'baixa',
    obsOperacional: 'Branquear e refrescar preserva a cor verde vibrante.',
    nutricao: { kcal: 80, prot: 4, carb: 7, gord: 4, fibra: 4, sodio: 200 },
    adequacaoRefeitorio: 91,
  },
  {
    nome: 'Couve-Flor Gratinada',
    categoria: 'guarnicao',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['legume', 'comfort'],
    ingredientes: [
      { item: 'Couve-flor', unid: 'kg', porPessoa: 0.1 },
      { item: 'Óleo', unid: 'ml', porPessoa: 3 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Separe a couve-flor em buquês e cozinhe até ficar firme.',
      'Disponha em assadeira e cubra com molho branco e queijo.',
      'Leve ao forno para gratinar até dourar.',
    ],
    rendimentoPorcaoG: 130,
    tempoMin: 35,
    complexidade: 'baixa',
    obsOperacional: 'Não cozinhar demais antes de gratinar para não desmanchar.',
    nutricao: { kcal: 150, prot: 6, carb: 12, gord: 9, fibra: 3, sodio: 280 },
    adequacaoRefeitorio: 87,
  },
  {
    nome: 'Berinjela Refogada',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['legume', 'fibra'],
    ingredientes: [
      { item: 'Berinjela', unid: 'kg', porPessoa: 0.09 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Óleo', unid: 'ml', porPessoa: 5 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Corte a berinjela em cubos e refogue a cebola no óleo.',
      'Adicione a berinjela e o tomate picado.',
      'Cozinhe em fogo médio até ficar macia e ajuste o sal.',
    ],
    rendimentoPorcaoG: 110,
    tempoMin: 25,
    complexidade: 'baixa',
    obsOperacional: 'A berinjela absorve bastante óleo; controlar a quantidade.',
    nutricao: { kcal: 100, prot: 2, carb: 10, gord: 6, fibra: 3, sodio: 200 },
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Chuchu Refogado',
    categoria: 'guarnicao',
    classe: 'economica',
    proteina: 'outros',
    tags: ['legume', 'fibra'],
    ingredientes: [
      { item: 'Chuchu', unid: 'kg', porPessoa: 0.1 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Óleo', unid: 'ml', porPessoa: 3 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Descasque e corte o chuchu em cubos.',
      'Refogue a cebola no óleo e acrescente o chuchu.',
      'Cozinhe em fogo médio até ficar macio e tempere com sal.',
    ],
    rendimentoPorcaoG: 110,
    tempoMin: 22,
    complexidade: 'baixa',
    nutricao: { kcal: 65, prot: 1, carb: 8, gord: 3, fibra: 3, sodio: 190 },
    adequacaoRefeitorio: 89,
  },
  {
    nome: 'Ratatouille',
    categoria: 'guarnicao',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['legume', 'fibra', 'vegetariano'],
    ingredientes: [
      { item: 'Abobrinha', unid: 'kg', porPessoa: 0.05 },
      { item: 'Berinjela', unid: 'kg', porPessoa: 0.05 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.04 },
      { item: 'Pimentão', unid: 'kg', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Óleo', unid: 'ml', porPessoa: 5 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Corte todos os legumes em cubos uniformes.',
      'Refogue cebola e pimentão, junte berinjela, abobrinha e tomate.',
      'Cozinhe lentamente em fogo baixo até apurar e ajuste o sal.',
    ],
    rendimentoPorcaoG: 130,
    tempoMin: 40,
    complexidade: 'baixa',
    obsOperacional: 'Cozimento lento concentra o sabor dos legumes.',
    nutricao: { kcal: 120, prot: 2, carb: 12, gord: 7, fibra: 4, sodio: 220 },
    adequacaoRefeitorio: 86,
  },
  {
    nome: 'Mix de Legumes Assados',
    categoria: 'guarnicao',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['legume', 'fibra'],
    ingredientes: [
      { item: 'Abobrinha', unid: 'kg', porPessoa: 0.04 },
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.04 },
      { item: 'Berinjela', unid: 'kg', porPessoa: 0.04 },
      { item: 'Pimentão', unid: 'kg', porPessoa: 0.03 },
      { item: 'Óleo', unid: 'ml', porPessoa: 5 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Corte os legumes em pedaços médios e regue com óleo e sal.',
      'Distribua em assadeira em camada única.',
      'Asse em forno alto, virando na metade, até dourarem.',
    ],
    rendimentoPorcaoG: 120,
    tempoMin: 38,
    complexidade: 'baixa',
    obsOperacional: 'Camada única na assadeira garante que assem em vez de cozinhar.',
    nutricao: { kcal: 130, prot: 2, carb: 13, gord: 7, fibra: 4, sodio: 210 },
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Salada de abobrinha',
    categoria: 'salada',
    classe: 'economica',
    proteina: 'outros',
    tags: ['fria', 'legume', 'leve'],
    ingredientes: [
      { item: 'Abobrinha', unid: 'kg', porPessoa: 0.1 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.04 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.01 },
      { item: 'Óleo', unid: 'ml', porPessoa: 4 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Corte a abobrinha em rodelas finas e o tomate em cubos.',
      'Fatie a cebola bem fina.',
      'Misture e tempere com óleo, sal e um fio de limão.',
      'Pode servir crua ou levemente grelhada para mais sabor.',
    ],
    rendimentoPorcaoG: 100,
    tempoMin: 10,
    complexidade: 'baixa',
    nutricao: { kcal: 60, prot: 2, carb: 7, gord: 4, fibra: 2, sodio: 130 },
    adequacaoRefeitorio: 86,
  },
  {
    nome: 'Salada de chuchu',
    categoria: 'salada',
    classe: 'economica',
    proteina: 'outros',
    tags: ['cozida', 'legume', 'leve'],
    ingredientes: [
      { item: 'Chuchu', unid: 'kg', porPessoa: 0.12 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Óleo', unid: 'ml', porPessoa: 4 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Descasque e corte o chuchu em cubos ou palitos.',
      'Cozinhe em água com sal até ficar macio mas firme.',
      'Escorra e tempere com alho, óleo e sal.',
      'Sirva morno ou em temperatura ambiente.',
    ],
    rendimentoPorcaoG: 100,
    tempoMin: 20,
    complexidade: 'baixa',
    nutricao: { kcal: 55, prot: 1, carb: 8, gord: 4, fibra: 2, sodio: 130 },
    adequacaoRefeitorio: 85,
  },
  {
    nome: 'Salada verde com agrião',
    categoria: 'salada',
    classe: 'economica',
    proteina: 'outros',
    tags: ['fria', 'folhas', 'refrescante'],
    ingredientes: [
      { item: 'Agrião', unid: 'mç', porPessoa: 0.1 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.04 },
      { item: 'Óleo', unid: 'ml', porPessoa: 3 },
      { item: 'Limão', unid: 'un', porPessoa: 0.1 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Higienize o agrião e retire os caules mais grossos.',
      'Corte o tomate em meias-luas.',
      'Misture e tempere na hora com óleo, limão e sal.',
    ],
    rendimentoPorcaoG: 80,
    tempoMin: 10,
    complexidade: 'baixa',
    obsOperacional: 'Temperar só no momento de servir para não murchar.',
    nutricao: { kcal: 45, prot: 2, carb: 4, gord: 3, fibra: 2, sodio: 130 },
    adequacaoRefeitorio: 90,
  },
  {
    nome: 'Salada verde com rúcula',
    categoria: 'salada',
    classe: 'economica',
    proteina: 'outros',
    tags: ['fria', 'folhas', 'refrescante'],
    ingredientes: [
      { item: 'Rúcula', unid: 'mç', porPessoa: 0.08 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.04 },
      { item: 'Óleo', unid: 'ml', porPessoa: 3 },
      { item: 'Limão', unid: 'un', porPessoa: 0.1 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Higienize a rúcula e escorra bem.',
      'Corte o tomate em cubos.',
      'Tempere na hora com óleo, limão e sal.',
    ],
    rendimentoPorcaoG: 75,
    tempoMin: 10,
    complexidade: 'baixa',
    nutricao: { kcal: 40, prot: 2, carb: 4, gord: 3, fibra: 2, sodio: 120 },
    adequacaoRefeitorio: 90,
  },
  {
    nome: 'Salada de repolho com manga',
    categoria: 'salada',
    classe: 'economica',
    proteina: 'outros',
    tags: ['fria', 'agridoce', 'fruta'],
    ingredientes: [
      { item: 'Repolho', unid: 'kg', porPessoa: 0.07 },
      { item: 'Manga', unid: 'kg', porPessoa: 0.04 },
      { item: 'Óleo', unid: 'ml', porPessoa: 3 },
      { item: 'Limão', unid: 'un', porPessoa: 0.1 },
      { item: 'Sal', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Fatie o repolho bem fino.',
      'Corte a manga em cubos.',
      'Misture e tempere com óleo, limão e sal.',
      'Deixar descansar 15 minutos para amaciar levemente o repolho.',
    ],
    rendimentoPorcaoG: 100,
    tempoMin: 15,
    complexidade: 'baixa',
    nutricao: { kcal: 65, prot: 1, carb: 12, gord: 3, fibra: 3, sodio: 130 },
    adequacaoRefeitorio: 85,
  },
];
