import type { Receita } from './tipos';

export const PRATOS: Receita[] = [
  {
    nome: 'Arroz doce com canela',
    categoria: 'sobremesa',
    classe: 'economica',
    proteina: 'outros',
    tags: ['doce', 'quente', 'classico'],
    ingredientes: [
      { item: 'Arroz', unid: 'kg', porPessoa: 0.02 },
      { item: 'Leite', unid: 'lt', porPessoa: 0.05 },
      { item: 'Leite condensado', unid: 'bag', porPessoa: 0.02 },
      { item: 'Açúcar', unid: 'g', porPessoa: 8 },
      { item: 'Canela em pó', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Cozinhe o arroz em água até ficar bem macio.',
      'Junte o leite e o leite condensado e cozinhe em fogo baixo mexendo.',
      'Ajuste o açúcar e cozinhe até encorpar.',
      'Distribua em cubas e polvilhe canela por cima.',
    ],
    rendimentoPorcaoG: 130,
    tempoMin: 45,
    complexidade: 'media',
    obsOperacional: 'Mexa com frequência no fim para não grudar no fundo da panela.',
    nutricao: { kcal: 230, prot: 5, carb: 42, gord: 5, fibra: 1, sodio: 70 },
    substituicoes: ['Leite condensado por açúcar e mais leite'],
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Pudim de leite condensado',
    categoria: 'sobremesa',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['doce', 'frio', 'classico'],
    ingredientes: [
      { item: 'Leite condensado', unid: 'bag', porPessoa: 0.03 },
      { item: 'Leite', unid: 'lt', porPessoa: 0.04 },
      { item: 'Ovos', unid: 'un', porPessoa: 0.5 },
      { item: 'Açúcar', unid: 'g', porPessoa: 12 },
    ],
    preparo: [
      'Faça a calda derretendo o açúcar até dourar e forre as formas.',
      'Bata leite condensado, leite e ovos até homogêneo.',
      'Asse em banho-maria até firmar.',
      'Resfrie bem antes de desenformar e porcionar.',
    ],
    rendimentoPorcaoG: 110,
    tempoMin: 60,
    complexidade: 'media',
    obsOperacional: 'Coe a mistura antes de assar para um pudim mais liso.',
    nutricao: { kcal: 240, prot: 7, carb: 38, gord: 8, fibra: 0, sodio: 90 },
    adequacaoRefeitorio: 84,
  },
  {
    nome: 'Mousse de chocolate',
    categoria: 'sobremesa',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['doce', 'frio', 'classico'],
    ingredientes: [
      { item: 'Mousse de chocolate', unid: 'pct', porPessoa: 0.015 },
      { item: 'Leite', unid: 'lt', porPessoa: 0.05 },
      { item: 'Creme de Leite', unid: 'lata', porPessoa: 0.02 },
    ],
    preparo: [
      'Bata o pó de mousse com o leite gelado até crescer.',
      'Incorpore o creme de leite delicadamente.',
      'Porcione em taças ou cubas e leve à geladeira para firmar.',
    ],
    rendimentoPorcaoG: 100,
    tempoMin: 20,
    complexidade: 'baixa',
    nutricao: { kcal: 210, prot: 4, carb: 28, gord: 10, fibra: 1, sodio: 80 },
    adequacaoRefeitorio: 82,
  },
  {
    nome: 'Mousse de maracujá',
    categoria: 'sobremesa',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['doce', 'frio', 'fruta'],
    ingredientes: [
      { item: 'Suco de maracujá', unid: 'lt', porPessoa: 0.03 },
      { item: 'Leite condensado', unid: 'bag', porPessoa: 0.02 },
      { item: 'Creme de Leite', unid: 'lata', porPessoa: 0.02 },
    ],
    preparo: [
      'Bata suco de maracujá, leite condensado e creme de leite.',
      'Porcione em taças e leve à geladeira por algumas horas.',
      'Finalize com fios de calda de maracujá, se houver.',
    ],
    rendimentoPorcaoG: 100,
    tempoMin: 20,
    complexidade: 'baixa',
    nutricao: { kcal: 220, prot: 4, carb: 34, gord: 8, fibra: 1, sodio: 60 },
    adequacaoRefeitorio: 85,
  },
  {
    nome: 'Gelatina colorida',
    categoria: 'sobremesa',
    classe: 'economica',
    proteina: 'outros',
    tags: ['doce', 'frio', 'fruta'],
    ingredientes: [
      { item: 'Gelatina', unid: 'pct', porPessoa: 0.01 },
      { item: 'Água', unid: 'ml', porPessoa: 90 },
    ],
    preparo: [
      'Dissolva a gelatina em água quente conforme a proporção.',
      'Complete com água fria e misture as cores em camadas.',
      'Leve à geladeira até firmar e porcione em cubos.',
    ],
    rendimentoPorcaoG: 90,
    tempoMin: 15,
    complexidade: 'baixa',
    obsOperacional: 'Prepare na véspera para garantir firmeza no serviço.',
    nutricao: { kcal: 120, prot: 2, carb: 27, gord: 0, fibra: 0, sodio: 45 },
    adequacaoRefeitorio: 90,
  },
  {
    nome: 'Salada de frutas',
    categoria: 'sobremesa',
    classe: 'economica',
    proteina: 'outros',
    tags: ['fruta', 'frio', 'classico'],
    ingredientes: [
      { item: 'Banana', unid: 'kg', porPessoa: 0.05 },
      { item: 'Maçã', unid: 'kg', porPessoa: 0.05 },
      { item: 'Mamão', unid: 'kg', porPessoa: 0.05 },
      { item: 'Laranja', unid: 'kg', porPessoa: 0.04 },
    ],
    preparo: [
      'Lave e descasque as frutas e corte em cubos uniformes.',
      'Misture e regue com suco de laranja para conservar.',
      'Mantenha gelado até o serviço.',
    ],
    rendimentoPorcaoG: 150,
    tempoMin: 30,
    complexidade: 'baixa',
    obsOperacional: 'Adicione a banana por último para não escurecer.',
    nutricao: { kcal: 130, prot: 2, carb: 30, gord: 1, fibra: 4, sodio: 30 },
    adequacaoRefeitorio: 95,
  },
  {
    nome: 'Curau de milho verde',
    categoria: 'sobremesa',
    classe: 'economica',
    proteina: 'outros',
    tags: ['doce', 'quente', 'classico'],
    ingredientes: [
      { item: 'Milho', unid: 'lata', porPessoa: 0.05 },
      { item: 'Leite', unid: 'lt', porPessoa: 0.05 },
      { item: 'Açúcar', unid: 'g', porPessoa: 12 },
      { item: 'Canela em pó', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Bata o milho com o leite e coe o líquido.',
      'Leve ao fogo com açúcar mexendo até engrossar.',
      'Porcione e polvilhe canela.',
    ],
    rendimentoPorcaoG: 130,
    tempoMin: 35,
    complexidade: 'media',
    nutricao: { kcal: 200, prot: 5, carb: 38, gord: 4, fibra: 2, sodio: 65 },
    adequacaoRefeitorio: 86,
  },
  {
    nome: 'Canjica branca',
    categoria: 'sobremesa',
    classe: 'economica',
    proteina: 'outros',
    tags: ['doce', 'quente', 'classico'],
    ingredientes: [
      { item: 'Canjica de milho', unid: 'kg', porPessoa: 0.03 },
      { item: 'Leite', unid: 'lt', porPessoa: 0.05 },
      { item: 'Leite condensado', unid: 'bag', porPessoa: 0.02 },
      { item: 'Coco ralado', unid: 'g', porPessoa: 5 },
    ],
    preparo: [
      'Deixe a canjica de molho e cozinhe até amaciar.',
      'Adicione leite, leite condensado e coco e cozinhe.',
      'Sirva quente polvilhada com canela.',
    ],
    rendimentoPorcaoG: 140,
    tempoMin: 60,
    complexidade: 'media',
    obsOperacional: 'Deixe de molho na véspera para reduzir o tempo de cozimento.',
    nutricao: { kcal: 250, prot: 6, carb: 44, gord: 6, fibra: 2, sodio: 70 },
    adequacaoRefeitorio: 85,
  },
  {
    nome: 'Doce de banana em calda',
    categoria: 'sobremesa',
    classe: 'economica',
    proteina: 'outros',
    tags: ['doce', 'fruta', 'quente'],
    ingredientes: [
      { item: 'Banana', unid: 'kg', porPessoa: 0.08 },
      { item: 'Açúcar', unid: 'g', porPessoa: 15 },
      { item: 'Canela em pó', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Disponha as bananas em camadas com açúcar e canela.',
      'Cozinhe em fogo baixo até formar calda e amaciar.',
      'Sirva morno ou gelado.',
    ],
    rendimentoPorcaoG: 120,
    tempoMin: 40,
    complexidade: 'baixa',
    nutricao: { kcal: 180, prot: 2, carb: 44, gord: 1, fibra: 3, sodio: 35 },
    adequacaoRefeitorio: 88,
  },
  {
    nome: 'Paçoca cremosa de banana',
    categoria: 'sobremesa',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['doce', 'frio', 'fruta'],
    ingredientes: [
      { item: 'Banana', unid: 'kg', porPessoa: 0.06 },
      { item: 'Paçoca', unid: 'g', porPessoa: 12 },
      { item: 'Creme de Leite', unid: 'lata', porPessoa: 0.02 },
    ],
    preparo: [
      'Amasse parte da banana e fatie o restante.',
      'Alterne camadas de banana, paçoca esfarelada e creme de leite.',
      'Resfrie e finalize com paçoca por cima.',
    ],
    rendimentoPorcaoG: 110,
    tempoMin: 25,
    complexidade: 'baixa',
    nutricao: { kcal: 260, prot: 5, carb: 38, gord: 11, fibra: 3, sodio: 80 },
    adequacaoRefeitorio: 80,
  },
  {
    nome: 'Cocada cremosa',
    categoria: 'sobremesa',
    classe: 'economica',
    proteina: 'outros',
    tags: ['doce', 'quente', 'classico'],
    ingredientes: [
      { item: 'Coco ralado', unid: 'g', porPessoa: 15 },
      { item: 'Leite condensado', unid: 'bag', porPessoa: 0.02 },
      { item: 'Leite', unid: 'lt', porPessoa: 0.03 },
    ],
    preparo: [
      'Misture coco, leite condensado e leite em panela.',
      'Cozinhe em fogo baixo mexendo até cremoso.',
      'Porcione ainda morno.',
    ],
    rendimentoPorcaoG: 90,
    tempoMin: 30,
    complexidade: 'baixa',
    nutricao: { kcal: 250, prot: 4, carb: 36, gord: 11, fibra: 2, sodio: 60 },
    adequacaoRefeitorio: 81,
  },
  {
    nome: 'Bolo de fubá',
    categoria: 'sobremesa',
    classe: 'economica',
    proteina: 'outros',
    tags: ['doce', 'classico'],
    ingredientes: [
      { item: 'Fubá', unid: 'kg', porPessoa: 0.03 },
      { item: 'Leite', unid: 'lt', porPessoa: 0.04 },
      { item: 'Ovos', unid: 'un', porPessoa: 0.4 },
      { item: 'Açúcar', unid: 'g', porPessoa: 15 },
    ],
    preparo: [
      'Bata os líquidos com ovos e açúcar.',
      'Incorpore o fubá e a farinha até obter massa lisa.',
      'Asse em assadeira untada até dourar e corte em pedaços.',
    ],
    rendimentoPorcaoG: 100,
    tempoMin: 50,
    complexidade: 'media',
    nutricao: { kcal: 240, prot: 5, carb: 42, gord: 6, fibra: 2, sodio: 110 },
    adequacaoRefeitorio: 84,
  },
  {
    nome: 'Bolo de cenoura com cobertura de chocolate',
    categoria: 'sobremesa',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['doce', 'classico'],
    ingredientes: [
      { item: 'Cenoura', unid: 'kg', porPessoa: 0.03 },
      { item: 'Ovos', unid: 'un', porPessoa: 0.4 },
      { item: 'Açúcar', unid: 'g', porPessoa: 15 },
      { item: 'Chocolate em pó', unid: 'g', porPessoa: 6 },
    ],
    preparo: [
      'Bata a cenoura com ovos, açúcar e óleo.',
      'Misture a farinha e o fermento e asse a massa.',
      'Cubra com calda de chocolate e porcione.',
    ],
    rendimentoPorcaoG: 110,
    tempoMin: 55,
    complexidade: 'media',
    nutricao: { kcal: 290, prot: 5, carb: 48, gord: 9, fibra: 2, sodio: 120 },
    adequacaoRefeitorio: 83,
  },
  {
    nome: 'Creme de abacate',
    categoria: 'sobremesa',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['fruta', 'frio', 'doce'],
    ingredientes: [
      { item: 'Abacate', unid: 'kg', porPessoa: 0.07 },
      { item: 'Açúcar', unid: 'g', porPessoa: 10 },
      { item: 'Limão', unid: 'un', porPessoa: 0.1 },
    ],
    preparo: [
      'Bata a polpa do abacate com açúcar e suco de limão.',
      'Ajuste o ponto cremoso e porcione em taças.',
      'Sirva bem gelado.',
    ],
    rendimentoPorcaoG: 110,
    tempoMin: 15,
    complexidade: 'baixa',
    obsOperacional: 'Prepare próximo ao serviço para manter a cor verde.',
    nutricao: { kcal: 200, prot: 3, carb: 22, gord: 13, fibra: 4, sodio: 30 },
    adequacaoRefeitorio: 87,
  },
  {
    nome: 'Manjar de coco com calda',
    categoria: 'sobremesa',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['doce', 'frio', 'classico'],
    ingredientes: [
      { item: 'Leite', unid: 'lt', porPessoa: 0.05 },
      { item: 'Leite condensado', unid: 'bag', porPessoa: 0.02 },
      { item: 'Coco ralado', unid: 'g', porPessoa: 8 },
      { item: 'Amido de milho', unid: 'g', porPessoa: 8 },
    ],
    preparo: [
      'Cozinhe leite, leite condensado e amido até engrossar.',
      'Junte o coco, despeje em formas e leve à geladeira.',
      'Desenforme e sirva com calda de ameixa ou frutas.',
    ],
    rendimentoPorcaoG: 120,
    tempoMin: 35,
    complexidade: 'media',
    nutricao: { kcal: 240, prot: 5, carb: 40, gord: 7, fibra: 1, sodio: 70 },
    adequacaoRefeitorio: 84,
  },
  {
    nome: 'Pavê de bolacha',
    categoria: 'sobremesa',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['doce', 'frio', 'classico'],
    ingredientes: [
      { item: 'Bolacha maisena', unid: 'pct', porPessoa: 0.015 },
      { item: 'Leite', unid: 'lt', porPessoa: 0.05 },
      { item: 'Leite condensado', unid: 'bag', porPessoa: 0.02 },
      { item: 'Creme de Leite', unid: 'lata', porPessoa: 0.02 },
    ],
    preparo: [
      'Prepare um creme cozinhando leite, leite condensado e amido.',
      'Monte em cubas alternando creme e bolacha umedecida.',
      'Finalize com chocolate e leve à geladeira.',
    ],
    rendimentoPorcaoG: 120,
    tempoMin: 40,
    complexidade: 'media',
    obsOperacional: 'Monte na véspera para a bolacha amaciar por igual.',
    nutricao: { kcal: 300, prot: 6, carb: 46, gord: 11, fibra: 1, sodio: 130 },
    adequacaoRefeitorio: 80,
  },
  {
    nome: 'Sagu de uva',
    categoria: 'sobremesa',
    classe: 'economica',
    proteina: 'outros',
    tags: ['doce', 'frio', 'fruta'],
    ingredientes: [
      { item: 'Sagu', unid: 'kg', porPessoa: 0.02 },
      { item: 'Suco de uva', unid: 'lt', porPessoa: 0.06 },
      { item: 'Açúcar', unid: 'g', porPessoa: 10 },
    ],
    preparo: [
      'Cozinhe o sagu no suco de uva até ficar translúcido.',
      'Acerte o açúcar e cozinhe mais alguns minutos.',
      'Resfrie até firmar e porcione.',
    ],
    rendimentoPorcaoG: 120,
    tempoMin: 40,
    complexidade: 'media',
    nutricao: { kcal: 190, prot: 2, carb: 46, gord: 0, fibra: 1, sodio: 35 },
    adequacaoRefeitorio: 86,
  },
  {
    nome: 'Banana caramelizada',
    categoria: 'sobremesa',
    classe: 'economica',
    proteina: 'outros',
    tags: ['fruta', 'quente', 'doce'],
    ingredientes: [
      { item: 'Banana', unid: 'kg', porPessoa: 0.08 },
      { item: 'Açúcar', unid: 'g', porPessoa: 12 },
      { item: 'Canela em pó', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Caramelize o açúcar em frigideira larga.',
      'Doure as fatias de banana dos dois lados.',
      'Polvilhe canela e sirva morno.',
    ],
    rendimentoPorcaoG: 110,
    tempoMin: 20,
    complexidade: 'baixa',
    nutricao: { kcal: 170, prot: 1, carb: 40, gord: 1, fibra: 3, sodio: 30 },
    adequacaoRefeitorio: 85,
  },
  {
    nome: 'Doce de abóbora com coco',
    categoria: 'sobremesa',
    classe: 'economica',
    proteina: 'outros',
    tags: ['doce', 'quente', 'classico'],
    ingredientes: [
      { item: 'Abóbora', unid: 'kg', porPessoa: 0.08 },
      { item: 'Açúcar', unid: 'g', porPessoa: 15 },
      { item: 'Coco ralado', unid: 'g', porPessoa: 8 },
    ],
    preparo: [
      'Cozinhe a abóbora em cubos com açúcar até desmanchar.',
      'Adicione o coco e cozinhe até o ponto de doce.',
      'Resfrie e porcione.',
    ],
    rendimentoPorcaoG: 100,
    tempoMin: 50,
    complexidade: 'media',
    nutricao: { kcal: 200, prot: 2, carb: 42, gord: 4, fibra: 3, sodio: 40 },
    adequacaoRefeitorio: 83,
  },
  {
    nome: 'Pé de moleque de panela',
    categoria: 'sobremesa',
    classe: 'economica',
    proteina: 'outros',
    tags: ['doce', 'classico'],
    ingredientes: [
      { item: 'Amendoim torrado', unid: 'g', porPessoa: 15 },
      { item: 'Açúcar', unid: 'g', porPessoa: 15 },
      { item: 'Leite condensado', unid: 'bag', porPessoa: 0.01 },
    ],
    preparo: [
      'Derreta o açúcar até formar caramelo claro.',
      'Junte o amendoim e o leite condensado mexendo.',
      'Espalhe em superfície untada e corte ao esfriar.',
    ],
    rendimentoPorcaoG: 80,
    tempoMin: 30,
    complexidade: 'media',
    obsOperacional: 'Trabalhe rápido pois o caramelo endurece ao esfriar.',
    nutricao: { kcal: 280, prot: 7, carb: 38, gord: 12, fibra: 2, sodio: 50 },
    adequacaoRefeitorio: 78,
  },
  {
    nome: 'Brigadeiro de colher',
    categoria: 'sobremesa',
    classe: 'equilibrada',
    proteina: 'outros',
    tags: ['doce', 'frio', 'classico'],
    ingredientes: [
      { item: 'Leite condensado', unid: 'bag', porPessoa: 0.03 },
      { item: 'Chocolate em pó', unid: 'g', porPessoa: 8 },
      { item: 'Creme de Leite', unid: 'lata', porPessoa: 0.01 },
    ],
    preparo: [
      'Cozinhe leite condensado com chocolate e manteiga até soltar.',
      'Finalize com creme de leite fora do fogo.',
      'Porcione em copinhos e leve à geladeira.',
    ],
    rendimentoPorcaoG: 90,
    tempoMin: 25,
    complexidade: 'baixa',
    nutricao: { kcal: 270, prot: 5, carb: 44, gord: 9, fibra: 1, sodio: 70 },
    adequacaoRefeitorio: 80,
  },
  {
    nome: 'Flan de baunilha',
    categoria: 'sobremesa',
    classe: 'economica',
    proteina: 'outros',
    tags: ['doce', 'frio', 'classico'],
    ingredientes: [
      { item: 'Pudim', unid: 'pct', porPessoa: 0.012 },
      { item: 'Leite', unid: 'lt', porPessoa: 0.06 },
    ],
    preparo: [
      'Dissolva o pó de flan no leite e leve ao fogo mexendo.',
      'Ferva até engrossar e despeje nas formas com calda.',
      'Resfrie até firmar e desenforme.',
    ],
    rendimentoPorcaoG: 100,
    tempoMin: 25,
    complexidade: 'baixa',
    nutricao: { kcal: 150, prot: 4, carb: 28, gord: 3, fibra: 0, sodio: 90 },
    adequacaoRefeitorio: 86,
  },
  {
    nome: 'Gelatina com creme',
    categoria: 'sobremesa',
    classe: 'economica',
    proteina: 'outros',
    tags: ['doce', 'frio', 'fruta'],
    ingredientes: [
      { item: 'Gelatina', unid: 'pct', porPessoa: 0.01 },
      { item: 'Leite', unid: 'lt', porPessoa: 0.04 },
      { item: 'Creme de Leite', unid: 'lata', porPessoa: 0.02 },
    ],
    preparo: [
      'Prepare a gelatina de fruta e deixe firmar em cubos.',
      'Bata leite com creme de leite e pó de pudim para o creme.',
      'Monte em camadas de creme e gelatina e resfrie.',
    ],
    rendimentoPorcaoG: 120,
    tempoMin: 30,
    complexidade: 'baixa',
    nutricao: { kcal: 190, prot: 4, carb: 30, gord: 6, fibra: 0, sodio: 60 },
    adequacaoRefeitorio: 84,
  },
  {
    nome: 'Fruta da estação porcionada',
    categoria: 'sobremesa',
    classe: 'economica',
    proteina: 'outros',
    tags: ['fruta', 'frio', 'classico'],
    ingredientes: [
      { item: 'Melancia', unid: 'kg', porPessoa: 0.1 },
      { item: 'Mamão', unid: 'kg', porPessoa: 0.05 },
    ],
    preparo: [
      'Lave e higienize as frutas da estação.',
      'Corte em fatias ou cubos para porcionamento individual.',
      'Mantenha refrigerada até o serviço.',
    ],
    rendimentoPorcaoG: 140,
    tempoMin: 20,
    complexidade: 'baixa',
    obsOperacional: 'Varie a fruta conforme a melhor oferta e preço do dia.',
    nutricao: { kcal: 120, prot: 2, carb: 26, gord: 1, fibra: 3, sodio: 30 },
    adequacaoRefeitorio: 95,
  },
  {
    nome: 'Arroz de leite com canela',
    categoria: 'sobremesa',
    classe: 'economica',
    proteina: 'outros',
    tags: ['doce', 'quente', 'classico'],
    ingredientes: [
      { item: 'Arroz', unid: 'kg', porPessoa: 0.02 },
      { item: 'Leite', unid: 'lt', porPessoa: 0.06 },
      { item: 'Açúcar', unid: 'g', porPessoa: 12 },
      { item: 'Canela em pó', unid: 'g', porPessoa: 1 },
    ],
    preparo: [
      'Cozinhe o arroz já macio no leite em fogo baixo.',
      'Adoce e mexa até obter consistência cremosa.',
      'Sirva polvilhado com canela.',
    ],
    rendimentoPorcaoG: 130,
    tempoMin: 40,
    complexidade: 'media',
    nutricao: { kcal: 220, prot: 5, carb: 40, gord: 4, fibra: 1, sodio: 60 },
    adequacaoRefeitorio: 87,
  },
];
