/* =====================================================================
   Receitas SUÍNAS e à base de OVO do Tatá House (refeitório corporativo).

   18 pratos principais suínos + 6 pratos principais à base de ovo
   (tortas, fritadas, suflê, ovos ao molho) adequados para almoço.

   Regra operacional: prato suíno entra no máximo 2× por semana; pratos
   de ovo são usados com moderação, como apoio no rodízio.
   ===================================================================== */

import type { Receita } from './tipos';

export const PRATOS: Receita[] = [
  /* ===================== SUÍNOS (18) ===================== */
  {
    nome: 'Lombo suíno assado fatiado',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'suina',
    tags: ['forno', 'classico'],
    ingredientes: [
      { item: 'Lombo suíno', unid: 'kg', porPessoa: 0.15 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Óleo', unid: 'ml', porPessoa: 5 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Tempere o lombo com alho, sal e um fio de óleo e deixe pegar gosto.',
      'Disponha em assadeiras com cebola em rodelas e um pouco de água.',
      'Asse coberto até cozinhar por dentro e doure no final destampado.',
      'Descanse a peça e fatie em fatias uniformes para a cuba.',
    ],
    rendimentoPorcaoG: 210,
    tempoMin: 80,
    complexidade: 'media',
    obsOperacional: 'Fatiar só após descanso evita perda de suco; mantenha em banho-maria.',
    nutricao: { kcal: 360, prot: 30, carb: 3, gord: 24, fibra: 1, sodio: 520 },
    substituicoes: ['Trocar lombo por pernil de porco fatiado'],
    adequacaoRefeitorio: 82,
  },
  {
    nome: 'Bisteca suína acebolada',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'suina',
    tags: ['frigideira', 'caseiro'],
    ingredientes: [
      { item: 'Bisteca suína', unid: 'kg', porPessoa: 0.16 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.05 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Tempere as bistecas com alho e sal com antecedência.',
      'Sele as peças na chapa quente dos dois lados.',
      'Refogue bastante cebola em meias-luas até murchar.',
      'Junte as bistecas à cebola e finalize por alguns minutos.',
    ],
    rendimentoPorcaoG: 200,
    tempoMin: 45,
    complexidade: 'baixa',
    obsOperacional: 'Selar em lotes para não soltar água e cozinhar no vapor.',
    nutricao: { kcal: 410, prot: 28, carb: 5, gord: 30, fibra: 1, sodio: 560 },
    substituicoes: ['Trocar bisteca por lombo suíno em medalhões'],
    adequacaoRefeitorio: 78,
  },
  {
    nome: 'Costelinha suína ao barbecue',
    categoria: 'principal',
    classe: 'premium',
    proteina: 'suina',
    tags: ['forno', 'agridoce', 'molho'],
    ingredientes: [
      { item: 'Costelinha suína', unid: 'kg', porPessoa: 0.16 },
      { item: 'Barbecue', unid: 'kg', porPessoa: 0.025 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Sal', unid: 'g', porPessoa: 3, opcional: true },
    ],
    preparo: [
      'Tempere a costelinha com alho e sal e asse coberta até ficar macia.',
      'Pincele generosamente com molho barbecue.',
      'Volte ao forno destampado para caramelizar a superfície.',
      'Corte entre os ossos e regue com mais molho ao servir.',
    ],
    rendimentoPorcaoG: 220,
    tempoMin: 90,
    complexidade: 'media',
    obsOperacional: 'Pré-cozinhar coberto garante maciez antes de glacear.',
    nutricao: { kcal: 450, prot: 26, carb: 16, gord: 30, fibra: 1, sodio: 720 },
    substituicoes: ['Usar costelinha de pernil em tiras'],
    adequacaoRefeitorio: 75,
  },
  {
    nome: 'Pernil de porco assado',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'suina',
    tags: ['forno', 'festivo'],
    ingredientes: [
      { item: 'Pernil de porco fatiado', unid: 'kg', porPessoa: 0.15 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.005 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Óleo', unid: 'ml', porPessoa: 5 },
      { item: 'Sal', unid: 'g', porPessoa: 4, opcional: true },
    ],
    preparo: [
      'Marine o pernil com alho, sal e cebola por algumas horas.',
      'Asse coberto com a marinada e um pouco de água.',
      'Destampe e doure, regando com o próprio caldo.',
      'Fatie e disponha na cuba com o molho do assado.',
    ],
    rendimentoPorcaoG: 210,
    tempoMin: 85,
    complexidade: 'media',
    obsOperacional: 'Aproveitar o caldo do assado como molho reduz desperdício.',
    nutricao: { kcal: 380, prot: 31, carb: 3, gord: 26, fibra: 1, sodio: 540 },
    substituicoes: ['Substituir por lombo suíno assado'],
    adequacaoRefeitorio: 80,
  },
  {
    nome: 'Linguiça toscana acebolada',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'suina',
    tags: ['frigideira', 'caseiro'],
    ingredientes: [
      { item: 'Linguiça Toscana', unid: 'kg', porPessoa: 0.14 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.05 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Óleo', unid: 'ml', porPessoa: 4 },
    ],
    preparo: [
      'Corte a linguiça em rodelas grossas.',
      'Doure bem na chapa até soltar gordura e ganhar cor.',
      'Acrescente cebola em meias-luas e refogue.',
      'Ajuste o ponto e sirva com bastante cebola.',
    ],
    rendimentoPorcaoG: 190,
    tempoMin: 35,
    complexidade: 'baixa',
    obsOperacional: 'Escorrer parte da gordura liberada deixa o prato mais leve.',
    nutricao: { kcal: 420, prot: 24, carb: 4, gord: 34, fibra: 1, sodio: 780 },
    substituicoes: ['Trocar por linguiça calabresa'],
    adequacaoRefeitorio: 70,
  },
  {
    nome: 'Lombo suíno ao molho de mostarda',
    categoria: 'principal',
    classe: 'premium',
    proteina: 'suina',
    tags: ['molho', 'cremoso'],
    ingredientes: [
      { item: 'Lombo suíno', unid: 'kg', porPessoa: 0.15 },
      { item: 'Mostarda', unid: 'kg', porPessoa: 0.02 },
      { item: 'Creme de Leite', unid: 'kg', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
    ],
    preparo: [
      'Sele medalhões de lombo temperados na chapa.',
      'Na mesma panela refogue cebola e alho.',
      'Junte mostarda e creme de leite e forme um molho liso.',
      'Volte a carne ao molho e aqueça sem ferver demais.',
    ],
    rendimentoPorcaoG: 205,
    tempoMin: 55,
    complexidade: 'media',
    obsOperacional: 'Adicionar creme em fogo baixo evita talhar o molho.',
    nutricao: { kcal: 400, prot: 29, carb: 6, gord: 28, fibra: 1, sodio: 600 },
    substituicoes: ['Trocar lombo por filé de frango'],
    adequacaoRefeitorio: 76,
  },
  {
    nome: 'Bisteca suína à milanesa',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'suina',
    tags: ['empanado', 'crocante'],
    ingredientes: [
      { item: 'Bisteca suína', unid: 'kg', porPessoa: 0.15 },
      { item: 'Ovos', unid: 'un', porPessoa: 0.5 },
      { item: 'Farinha de trigo', unid: 'kg', porPessoa: 0.03 },
      { item: 'Óleo', unid: 'ml', porPessoa: 12 },
      { item: 'Sal', unid: 'g', porPessoa: 3, opcional: true },
    ],
    preparo: [
      'Tempere as bistecas e passe por farinha, ovo e farinha de novo.',
      'Frite em óleo quente até dourar dos dois lados.',
      'Escorra sobre grade para manter a crocância.',
      'Finalize no forno se necessário para garantir o cozimento interno.',
    ],
    rendimentoPorcaoG: 200,
    tempoMin: 60,
    complexidade: 'alta',
    obsOperacional: 'Empanar em estação separada e fritar em lotes pequenos.',
    nutricao: { kcal: 440, prot: 28, carb: 18, gord: 28, fibra: 1, sodio: 580 },
    substituicoes: ['Trocar bisteca por filé de frango'],
    adequacaoRefeitorio: 72,
  },
  {
    nome: 'Costelinha suína com mandioca',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'suina',
    tags: ['regional', 'comfort'],
    ingredientes: [
      { item: 'Costelinha suína', unid: 'kg', porPessoa: 0.15 },
      { item: 'Mandioca', unid: 'kg', porPessoa: 0.08 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Óleo', unid: 'ml', porPessoa: 5 },
    ],
    preparo: [
      'Refogue a costelinha temperada até dourar.',
      'Cubra com água e cozinhe até ficar macia.',
      'Acrescente a mandioca em pedaços e cozinhe junto.',
      'Acerte o caldo e sirva a costelinha sobre a mandioca.',
    ],
    rendimentoPorcaoG: 240,
    tempoMin: 75,
    complexidade: 'media',
    obsOperacional: 'Cozinhar a mandioca no caldo da carne concentra o sabor.',
    nutricao: { kcal: 430, prot: 25, carb: 17, gord: 28, fibra: 2, sodio: 560 },
    substituicoes: ['Trocar mandioca por batata'],
    adequacaoRefeitorio: 74,
  },
  {
    nome: 'Lombo suíno recheado',
    categoria: 'principal',
    classe: 'premium',
    proteina: 'suina',
    tags: ['forno', 'festivo'],
    ingredientes: [
      { item: 'Lombo suíno', unid: 'kg', porPessoa: 0.15 },
      { item: 'Bacon', unid: 'kg', porPessoa: 0.02 },
      { item: 'Mussarela', unid: 'kg', porPessoa: 0.025 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Sal', unid: 'g', porPessoa: 3, opcional: true },
    ],
    preparo: [
      'Abra o lombo em manta e tempere por dentro.',
      'Recheie com bacon e mussarela e enrole firme.',
      'Amarre ou prenda e asse coberto até o cozimento.',
      'Doure, descanse e fatie em rodelas com o recheio.',
    ],
    rendimentoPorcaoG: 215,
    tempoMin: 85,
    complexidade: 'alta',
    obsOperacional: 'Amarrar bem evita o recheio escapar na fatia.',
    nutricao: { kcal: 460, prot: 32, carb: 2, gord: 34, fibra: 0, sodio: 700 },
    substituicoes: ['Recheio de presunto e queijo'],
    adequacaoRefeitorio: 73,
  },
  {
    nome: 'Linguiça calabresa com pimentões',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'suina',
    tags: ['frigideira', 'colorido'],
    ingredientes: [
      { item: 'Linguiça Calabresa', unid: 'kg', porPessoa: 0.13 },
      { item: 'Pimentão', unid: 'kg', porPessoa: 0.06 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.04 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Óleo', unid: 'ml', porPessoa: 4 },
    ],
    preparo: [
      'Corte a calabresa em rodelas e doure na chapa.',
      'Junte cebola e pimentões coloridos em tiras.',
      'Refogue até os legumes ficarem al dente.',
      'Misture tudo e finalize com o sabor da linguiça.',
    ],
    rendimentoPorcaoG: 195,
    tempoMin: 35,
    complexidade: 'baixa',
    obsOperacional: 'Pimentão em tiras grossas mantém textura no aquecimento.',
    nutricao: { kcal: 400, prot: 24, carb: 7, gord: 31, fibra: 2, sodio: 800 },
    substituicoes: ['Trocar por linguiça toscana'],
    adequacaoRefeitorio: 68,
  },
  {
    nome: 'Pernil de porco ao molho',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'suina',
    tags: ['molho', 'caseiro'],
    ingredientes: [
      { item: 'Pernil de porco fatiado', unid: 'kg', porPessoa: 0.15 },
      { item: 'Molho de tomate', unid: 'lt', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Óleo', unid: 'ml', porPessoa: 5 },
    ],
    preparo: [
      'Doure o pernil temperado em panela ampla.',
      'Refogue cebola e alho no mesmo fundo.',
      'Junte molho de tomate e um pouco de água.',
      'Cozinhe até a carne ficar macia e o molho encorpar.',
    ],
    rendimentoPorcaoG: 220,
    tempoMin: 70,
    complexidade: 'media',
    obsOperacional: 'Cozimento lento no molho deixa a carne desmanchando.',
    nutricao: { kcal: 370, prot: 30, carb: 8, gord: 24, fibra: 2, sodio: 580 },
    substituicoes: ['Trocar pernil por lombo em cubos'],
    adequacaoRefeitorio: 79,
  },
  {
    nome: 'Torresmo de panela',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'suina',
    tags: ['regional', 'crocante'],
    ingredientes: [
      { item: 'Bacon', unid: 'kg', porPessoa: 0.12 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Sal', unid: 'g', porPessoa: 3, opcional: true },
    ],
    preparo: [
      'Corte o bacon em cubos grandes uniformes.',
      'Frite em panela própria liberando a gordura aos poucos.',
      'Cozinhe até os cubos ficarem crocantes por fora.',
      'Escorra bem e tempere com alho frito ao servir.',
    ],
    rendimentoPorcaoG: 170,
    tempoMin: 50,
    complexidade: 'media',
    obsOperacional: 'Servir como prato de apoio; controlar bem a fritura por segurança.',
    nutricao: { kcal: 470, prot: 24, carb: 0, gord: 34, fibra: 0, sodio: 820 },
    substituicoes: ['Usar barriga suína em cubos'],
    adequacaoRefeitorio: 65,
  },
  {
    nome: 'Lombo defumado refogado',
    categoria: 'principal',
    classe: 'premium',
    proteina: 'suina',
    tags: ['defumado', 'frigideira'],
    ingredientes: [
      { item: 'Lombo suíno', unid: 'kg', porPessoa: 0.14 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.04 },
      { item: 'Pimentão', unid: 'kg', porPessoa: 0.03 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Óleo', unid: 'ml', porPessoa: 4 },
    ],
    preparo: [
      'Corte o lombo defumado em tiras finas.',
      'Salteie rapidamente na chapa quente.',
      'Acrescente cebola e pimentão e refogue.',
      'Finalize mantendo as tiras suculentas.',
    ],
    rendimentoPorcaoG: 195,
    tempoMin: 40,
    complexidade: 'baixa',
    obsOperacional: 'Por ser curado, o defumado já é salgado; evitar sal extra.',
    nutricao: { kcal: 350, prot: 30, carb: 5, gord: 22, fibra: 1, sodio: 800 },
    substituicoes: ['Trocar por lombo fresco em tiras'],
    adequacaoRefeitorio: 71,
  },
  {
    nome: 'Costelinha suína agridoce',
    categoria: 'principal',
    classe: 'premium',
    proteina: 'suina',
    tags: ['agridoce', 'molho', 'forno'],
    ingredientes: [
      { item: 'Costelinha suína', unid: 'kg', porPessoa: 0.16 },
      { item: 'Molho de tomate', unid: 'lt', porPessoa: 0.02 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Pimentão', unid: 'kg', porPessoa: 0.03 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
    ],
    preparo: [
      'Pré-cozinhe a costelinha temperada até amaciar.',
      'Prepare um molho agridoce com tomate, cebola e pimentão.',
      'Envolva a costelinha no molho.',
      'Leve ao forno para glacear e apurar o sabor.',
    ],
    rendimentoPorcaoG: 225,
    tempoMin: 85,
    complexidade: 'media',
    obsOperacional: 'Reduzir o molho separado evita aguar a costelinha.',
    nutricao: { kcal: 440, prot: 26, carb: 14, gord: 30, fibra: 2, sodio: 640 },
    substituicoes: ['Trocar costelinha por pernil em cubos'],
    adequacaoRefeitorio: 73,
  },
  {
    nome: 'Lombo suíno em cubos refogado',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'suina',
    tags: ['frigideira', 'caseiro'],
    ingredientes: [
      { item: 'Lombo suíno', unid: 'kg', porPessoa: 0.15 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.04 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Pimentão', unid: 'kg', porPessoa: 0.03 },
      { item: 'Óleo', unid: 'ml', porPessoa: 5 },
    ],
    preparo: [
      'Corte o lombo em cubos médios e tempere.',
      'Sele os cubos em panela quente em lotes.',
      'Refogue cebola, alho e pimentão.',
      'Reúna tudo e cozinhe até os cubos ficarem macios.',
    ],
    rendimentoPorcaoG: 200,
    tempoMin: 50,
    complexidade: 'baixa',
    obsOperacional: 'Selar em lotes garante dourado em vez de cozido.',
    nutricao: { kcal: 360, prot: 30, carb: 5, gord: 23, fibra: 1, sodio: 500 },
    substituicoes: ['Trocar lombo por pernil em cubos'],
    adequacaoRefeitorio: 80,
  },
  {
    nome: 'Bisteca suína ao molho de tomate',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'suina',
    tags: ['molho', 'caseiro'],
    ingredientes: [
      { item: 'Bisteca suína', unid: 'kg', porPessoa: 0.15 },
      { item: 'Molho de tomate', unid: 'lt', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.004 },
      { item: 'Óleo', unid: 'ml', porPessoa: 5 },
    ],
    preparo: [
      'Sele as bistecas temperadas dos dois lados.',
      'Refogue cebola e alho no mesmo fundo.',
      'Adicione molho de tomate e um pouco de água.',
      'Cozinhe as bistecas no molho até ficarem macias.',
    ],
    rendimentoPorcaoG: 210,
    tempoMin: 55,
    complexidade: 'baixa',
    obsOperacional: 'Braseado no molho recupera a maciez de cortes mais firmes.',
    nutricao: { kcal: 390, prot: 27, carb: 9, gord: 26, fibra: 2, sodio: 540 },
    substituicoes: ['Trocar bisteca por lombo em medalhões'],
    adequacaoRefeitorio: 77,
  },
  {
    nome: 'Linguiça toscana com batatas',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'suina',
    tags: ['forno', 'comfort'],
    ingredientes: [
      { item: 'Linguiça Toscana', unid: 'kg', porPessoa: 0.13 },
      { item: 'Batata', unid: 'kg', porPessoa: 0.08 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Óleo', unid: 'ml', porPessoa: 6 },
    ],
    preparo: [
      'Corte a linguiça em rodelas e as batatas em cubos.',
      'Tempere tudo com alho, cebola e óleo.',
      'Espalhe em assadeira e leve ao forno.',
      'Asse mexendo até a linguiça dourar e as batatas ficarem macias.',
    ],
    rendimentoPorcaoG: 230,
    tempoMin: 60,
    complexidade: 'baixa',
    obsOperacional: 'Pré-cozinhar a batata acelera o assamento conjunto.',
    nutricao: { kcal: 430, prot: 24, carb: 18, gord: 30, fibra: 2, sodio: 760 },
    substituicoes: ['Trocar batata por mandioca'],
    adequacaoRefeitorio: 70,
  },
  {
    nome: 'Pernil de porco à milanesa',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'suina',
    tags: ['empanado', 'crocante'],
    ingredientes: [
      { item: 'Pernil de porco fatiado', unid: 'kg', porPessoa: 0.15 },
      { item: 'Ovos', unid: 'un', porPessoa: 0.5 },
      { item: 'Farinha de trigo', unid: 'kg', porPessoa: 0.03 },
      { item: 'Óleo', unid: 'ml', porPessoa: 12 },
      { item: 'Sal', unid: 'g', porPessoa: 3, opcional: true },
    ],
    preparo: [
      'Achate as fatias de pernil e tempere.',
      'Empane passando por farinha, ovo e farinha.',
      'Frite em óleo quente até dourar.',
      'Escorra em grade e finalize no forno se necessário.',
    ],
    rendimentoPorcaoG: 200,
    tempoMin: 65,
    complexidade: 'alta',
    obsOperacional: 'Manter estação de empanar separada da fritura por higiene.',
    nutricao: { kcal: 450, prot: 29, carb: 18, gord: 28, fibra: 1, sodio: 560 },
    substituicoes: ['Trocar pernil por bisteca suína'],
    adequacaoRefeitorio: 72,
  },

  /* ===================== OVO (6) ===================== */
  {
    nome: 'Torta de legumes de forno',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'ovo',
    tags: ['forno', 'vegetariano'],
    ingredientes: [
      { item: 'Ovos', unid: 'un', porPessoa: 2 },
      { item: 'Farinha de trigo', unid: 'kg', porPessoa: 0.04 },
      { item: 'Leite', unid: 'lt', porPessoa: 0.05 },
      { item: 'Pimentão', unid: 'kg', porPessoa: 0.04 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Óleo', unid: 'ml', porPessoa: 5 },
    ],
    preparo: [
      'Refogue cebola e pimentão e reserve.',
      'Bata ovos, leite, farinha e óleo formando uma massa líquida.',
      'Misture os legumes refogados à massa.',
      'Despeje em assadeira untada e asse até firmar e dourar.',
    ],
    rendimentoPorcaoG: 210,
    tempoMin: 55,
    complexidade: 'baixa',
    obsOperacional: 'Massa líquida tipo liquidificador rende bem em escala.',
    nutricao: { kcal: 260, prot: 13, carb: 20, gord: 14, fibra: 2, sodio: 460 },
    substituicoes: ['Acrescentar mussarela à massa'],
    adequacaoRefeitorio: 68,
  },
  {
    nome: 'Fritada de forno com calabresa',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'ovo',
    tags: ['forno', 'comfort'],
    ingredientes: [
      { item: 'Ovos', unid: 'un', porPessoa: 2.5 },
      { item: 'Linguiça Calabresa', unid: 'kg', porPessoa: 0.04 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Batata', unid: 'kg', porPessoa: 0.04 },
      { item: 'Óleo', unid: 'ml', porPessoa: 4 },
    ],
    preparo: [
      'Doure a calabresa em cubos com cebola e batata cozida.',
      'Bata os ovos e tempere.',
      'Junte o refogado aos ovos e despeje em assadeira.',
      'Asse até firmar e dourar a superfície.',
    ],
    rendimentoPorcaoG: 200,
    tempoMin: 50,
    complexidade: 'baixa',
    obsOperacional: 'Assar em assadeira rasa garante cozimento uniforme.',
    nutricao: { kcal: 300, prot: 18, carb: 10, gord: 20, fibra: 1, sodio: 600 },
    substituicoes: ['Trocar calabresa por bacon em cubos'],
    adequacaoRefeitorio: 65,
  },
  {
    nome: 'Omelete de forno recheada',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'ovo',
    tags: ['forno', 'rapido'],
    ingredientes: [
      { item: 'Ovos', unid: 'un', porPessoa: 2.5 },
      { item: 'Mussarela', unid: 'kg', porPessoa: 0.03 },
      { item: 'Tomate', unid: 'kg', porPessoa: 0.04 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.02 },
      { item: 'Leite', unid: 'lt', porPessoa: 0.02 },
    ],
    preparo: [
      'Bata os ovos com o leite e tempere.',
      'Espalhe tomate e cebola picados na assadeira.',
      'Cubra com os ovos e a mussarela.',
      'Asse até firmar e gratinar levemente.',
    ],
    rendimentoPorcaoG: 190,
    tempoMin: 40,
    complexidade: 'baixa',
    obsOperacional: 'Forno alto no final ajuda a gratinar sem ressecar.',
    nutricao: { kcal: 280, prot: 19, carb: 5, gord: 20, fibra: 1, sodio: 480 },
    substituicoes: ['Recheio de presunto e queijo'],
    adequacaoRefeitorio: 70,
  },
  {
    nome: 'Suflê de queijo',
    categoria: 'principal',
    classe: 'premium',
    proteina: 'ovo',
    tags: ['forno', 'cremoso'],
    ingredientes: [
      { item: 'Ovos', unid: 'un', porPessoa: 2 },
      { item: 'Mussarela', unid: 'kg', porPessoa: 0.04 },
      { item: 'Leite', unid: 'lt', porPessoa: 0.06 },
      { item: 'Farinha de trigo', unid: 'kg', porPessoa: 0.02 },
      { item: 'Sal', unid: 'g', porPessoa: 2, opcional: true },
    ],
    preparo: [
      'Prepare um creme base com leite e farinha.',
      'Misture o queijo e as gemas ao creme morno.',
      'Bata as claras em neve e incorpore delicadamente.',
      'Asse em forma untada até crescer e dourar.',
    ],
    rendimentoPorcaoG: 180,
    tempoMin: 60,
    complexidade: 'alta',
    obsOperacional: 'Servir logo após assar; o suflé murcha ao esfriar.',
    nutricao: { kcal: 320, prot: 20, carb: 12, gord: 22, fibra: 0, sodio: 540 },
    substituicoes: ['Acrescentar legumes picados ao creme'],
    adequacaoRefeitorio: 55,
  },
  {
    nome: 'Ovos ao molho de tomate',
    categoria: 'principal',
    classe: 'economica',
    proteina: 'ovo',
    tags: ['molho', 'rapido'],
    ingredientes: [
      { item: 'Ovos', unid: 'un', porPessoa: 2 },
      { item: 'Molho de tomate', unid: 'lt', porPessoa: 0.04 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.03 },
      { item: 'Alho', unid: 'kg', porPessoa: 0.003 },
      { item: 'Óleo', unid: 'ml', porPessoa: 4 },
    ],
    preparo: [
      'Refogue cebola e alho e adicione o molho de tomate.',
      'Deixe o molho apurar com um pouco de água.',
      'Quebre os ovos sobre o molho fervente.',
      'Cozinhe tampado até as claras firmarem.',
    ],
    rendimentoPorcaoG: 200,
    tempoMin: 35,
    complexidade: 'baixa',
    obsOperacional: 'Em escala, escalfar os ovos em assadeira no forno facilita.',
    nutricao: { kcal: 220, prot: 14, carb: 8, gord: 14, fibra: 2, sodio: 500 },
    substituicoes: ['Acrescentar pimentão ao molho'],
    adequacaoRefeitorio: 66,
  },
  {
    nome: 'Quiche de alho-poró simplificada',
    categoria: 'principal',
    classe: 'equilibrada',
    proteina: 'ovo',
    tags: ['forno', 'cremoso'],
    ingredientes: [
      { item: 'Ovos', unid: 'un', porPessoa: 2 },
      { item: 'Creme de Leite', unid: 'kg', porPessoa: 0.03 },
      { item: 'Cebola', unid: 'kg', porPessoa: 0.04 },
      { item: 'Mussarela', unid: 'kg', porPessoa: 0.02 },
      { item: 'Farinha de trigo', unid: 'kg', porPessoa: 0.03 },
    ],
    preparo: [
      'Refogue a cebola fatiada até murchar.',
      'Bata ovos com creme de leite e tempere.',
      'Monte em assadeira com base de massa e o refogado.',
      'Cubra com queijo e asse até dourar e firmar o recheio.',
    ],
    rendimentoPorcaoG: 195,
    tempoMin: 65,
    complexidade: 'media',
    obsOperacional: 'Recheio sem fundo crocante simplifica o preparo em volume.',
    nutricao: { kcal: 310, prot: 15, carb: 16, gord: 21, fibra: 1, sodio: 520 },
    substituicoes: ['Trocar alho-poró por cebola refogada'],
    adequacaoRefeitorio: 67,
  },
];
